### ISSUE TITLE
Implement gamemode switching between worlds (as part of the WorldBuilder)

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#1]
(Hurrah to issue #1 on SpongeCommon!)

@bloodmc 

When we pull over the world management impl to common, we need to implement switching gamemodes between worlds.

I think we considered making a permission in-which a player can override the gamemode switch. Something like

    sponge.gamemode.override

?

**Comment by ryantheleach** [comment]
If this is to have a creative world, and a survival world in the same server, wouldn't it make more sense to either remember the last used gametype per world, or going further and having the option to keep seperate userdata/inventory/falldamage/statistics per universe?

I've used multiverses gametype enforcing before and both allowing users to have an override permission allowing them to bring creative from creative to survival, or not having the override permission and suddenly dying as they teleport to their last known flying position in a survival world (due to being in creative in the survival world before going to the creative world) seem annoying.

**Comment by Zidane** [comment]
We won't be keeping inventory/etc isolated per world. Remember we want to try and keep things mostly Vanilla gameplay.

With that said, having gamemode in the builder does complicate things. Namely cause it does break vanilla gameplay doesn't it.

@SpongePowered/developers thoughts?

**Comment by ryantheleach** [comment]
If I understand correctly from reading the spongedocs, in sponge a world is a collection of dimensions, unlike Bukkit which relocated the dimensions into their own worlds?

So cross-dimension same world teleports is the "vanilla" behaviour and thus is why gamemode is preserved.

When is the players gamemode set in vanilla (without command intervention)? Is it a once off thing that gets remembered and maintained? 

As far as I can see, the only difference a worlds gamemode makes, is what players who data is first generated gets assigned, changing the gamemode of the world (and not player) would just result in the player maintaining their original gamemode.

Also in singleplayer when a player changes worlds, it then loads the playerdata associated with that world. So bringing true multi-world support into servers means that inventories and everything would be   separate by default? players teleport across dimensions, but join and leave worlds.

**Comment by Zidane** [comment]
@ryantheleach 

In Sponge, each world has its own dimension and are treated as true worlds. The only reason why world and DIM1/-1 seem "linked" is cause of their portal targets.

As I mentioned above, we have to mostly keep vanilla functionality:

* We won't isolate inventory per world. Plugin can do this.
* Gamemode is tricky. In vanilla currently, you keep your gamemode.

So its probably better that we don't interfere here. If a plugin wants to isolate gamemode per world, we should let them do so.

**Comment by gabizou** [comment]
Considering this is partially handled by data, during the event being thrown for someone transferring between worlds, this shouldn't be much of an issue from the implementation side.

That being said, I do believe it should be handled as vanilla deems fit, and plugins interacting with the player (setting game mode in the event) will take priority for obvious reasons.

**Comment by Zidane** [comment]
Closing this as we follow what Vanilla does. Plugins can easily change the GameMode during events. I'll be removing it from the WorldBuilder.
