### ISSUE TITLE
Correct biomes matching dimensions rather than terrain.

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeCommon#10]
Currently when you create a world with a certain GeneratorType and a different Dimension Type (for example overworld terrain in a nether dimension), the final biomes of the world match the dimension rather than the terrain. This should be the reverse with the biomes matching the terrain.

This is easy to see using the WorldTest and traveling to any of the mixed worlds (netherend, endnether, overend, endover, netherover, overnether).

**Comment by Zidane** [comment]
This was fixed in the merge of unified world changes.
