### ISSUE TITLE
Not able to connect to sponge server behind BungeeCord proxy

### ISSUE THREAD

**Issue by ghacproductions** [SpongePowered/SpongeCommon#104]
It's not able to connect to a sponge server which is behind a BungeeCord proxy. The sponge server does not give out any information of a try of connection to the server.

There are no error-messages, the player simply does not connect to the server. The bungeecord-proxy says, that the player connected but also shows that he disconnected in the next message. There are no logs at the sponge server.

Sponge-Version: sponge-1.8-1487-2.1DEV-523
BungeeCord-Version: Build 1​07​6

**Comment by JBYoshi** [comment]
I'm unable to reproduce it. Could you provide your configs (Bungee config.yml and Sponge server.properties)?

**Comment by progwml6** [comment]
several staff members have managed to reproduce it

**Comment by me4502** [comment]
Make sure ip forwarding is disabled.

**Comment by ghacproductions** [comment]
It works with disabled ip-forwarding.

**Comment by Mumfrey** [comment]
Closing since this is a duplicate of #65
