### ISSUE TITLE
Build sponge-1.8-1487-2.1DEV-524 unable to initialize

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#106]
No plugins - just forge 1487 and dev-524              (  dev-523 downgrade no problem)
FML Loader crashes with an IllegalStateException
http://pastebin.com/zEicL2K0

crashlog:
http://pastebin.com/N8sckEQ8

**Comment by Zidane** [comment]
I noticed this earlier, thanks for the report.

We'll get it fixed up.
