### ISSUE TITLE
Biome terrain height usability

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeCommon#107]
Currently the min and max heights in BiomeType are the internal values used by the generator which do not translate into usable numbers very well. It would be good to change these values to a more usable value which can be translated to actual Y values.

For reference the current height values are
```
height_Default = (0.1F, 0.2F)
height_ShallowWaters = (-0.5F, 0.0F)
height_Oceans = (-1.0F, 0.1F)
height_DeepOceans = (-1.8F, 0.1F)
height_LowPlains = (0.125F, 0.05F)
height_MidPlains = (0.2F, 0.2F)
height_LowHills = (0.45F, 0.3F)
height_HighPlateaus = (1.5F, 0.025F)
height_MidHills = (1.0F, 0.5F)
height_Shores = (0.0F, 0.025F)
height_RockyWaters = (0.1F, 0.8F)
height_LowIslands = (0.2F, 0.3F)
height_PartiallySubmerged = (-0.2F, 0.1F)
```

**Comment by JBYoshi** [comment]
> a more usable value which can be translated to actual Y values

Sounds a lot like raw Y values to me.

**Comment by Zidane** [comment]
@JBYoshi 

Do you come onto IRC at all? If so, what is your handle?

**Comment by JBYoshi** [comment]
No I don't.

**Comment by Zidane** [comment]
@JBYoshi 

I'd like to talk to you "face to face" sometime. Do you do TS perhaps?

**Comment by JBYoshi** [comment]
Unfortunately, I don't have that either.

**Comment by Zidane** [comment]
@JBYoshi 

Could you get one or the either perhaps? Or maybe an email chain? You can reach me at zidane@spongepowered.org

**Comment by Deamon5550** [comment]
@JBYoshi yeah thats one option, but not very viable.

The final height is based on:
- the min and max from the surrounding 5x5 area averaged with a 2D parabolic field
- an offset and weight from the world settings
- a multiplier if the world is amplified
- a whole lot of magic modifiers
- a whole lot of noise functions

[For reference](https://gist.github.com/Deamon5550/86cd02987bcc7fba3e19)

**Comment by JBYoshi** [comment]
@Deamon5550 ...Whoa.

**Comment by JBYoshi** [comment]
@Zidane I'll get an IRC handle in a couple days.

**Comment by JBYoshi** [comment]
@Zidane Would we be able to meet on IRC tomorrow (August 6) evening? I should be available around 8 PM central.

**Comment by gabizou** [comment]
@Deamon5550 would this be likely resolved with your world generation changes (in any of the phases)?

**Comment by Deamon5550** [comment]
Sure but the issue is more how to resolve it...

**Comment by Deamon5550** [comment]
I think that there probably isn't a way that we can better represent these values, other than changing their names at least because min and max height is completely wrong.
