### ISSUE TITLE
World data files inconsistent with vanilla (and forge)

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#116]
Comparison table : http://imgur.com/hESNLki

![image](https://cloud.githubusercontent.com/assets/141554/9020329/02882c12-3845-11e5-9d80-f231f435fc07.png)

Of note: DIM1 & DIM-1 level.dat's empty playerdata folders, and village_nether.dat Fortress.dat

Tested on Minecraft 1.8.8 vs forge-1.8-11.14.3.1499-universal vs sponge-1.8-1499-2.1DEV-532 vs https://github.com/SpongePowered/SpongeVanilla/commit/c2b9cb18e728f100d1fdebc830e3e663c8733227

**Comment by Zidane** [comment]
@bloodmc 

You know more about these files than I. Please comment on the above.

**Comment by bloodmc** [comment]
As I stated on IRC, level.dat files are intended to be different in Sponge as we use a savehandler per world unlike Vanilla/Forge which use a single savehandler for all worlds. I'll look into the other issues soon.

**Comment by ryantheleach** [comment]
Should this be closed? Sponge has moved significantly since this was first created, and originally I believe I was confused at why SpongeVanilla and SpongeForge didn't have matching configuration directories, the rest was just me being confused at the data layout vs the other platforms.

**Comment by gabizou** [comment]
@ryantheleach Well, the question I believe is: is this still an issue where the directories aren't matching up?

**Comment by Zidane** [comment]
Directories should be matching 1:1 between SV and SF. Differences would likely be due to mods. I think this is safely closed.
