### ISSUE TITLE
Unexpected world-teleportation behavior when "allow-nether" is set to false

### ISSUE THREAD

**Issue by zRaptor** [SpongePowered/SpongeCommon#118]
Teleporting to newly-generated worlds does not seem to work properly when `allow-nether` is set to `false` in `server.properties`.

This problem can be replicated by running the WorldsTest plugin that is available in the Cookbook. It is expected that, after the server has started, typing `/tpworld skylands` will take you to the Skylands world. Instead, you are teleported to a void of absolutely nothing. The world terrain *does* seem to be generated properly, in case that needs to be ruled out - opening the world in MCEdit shows the terrain.

Sponge: 1.8-1499-2.1DEV-536
Forge: v11.14.3.1450
Java: 1.8.0_51

**Comment by simon816** [comment]
See https://github.com/SpongePowered/Sponge/issues/287
"allow-nether" really means "allow multi-dimensions"

**Comment by zRaptor** [comment]
Ah, thanks - didn't see that issue. That's a rather strange design decision imo, but I'll go with it.

Closing this in favor of the issue you linked.

**Comment by JBYoshi** [comment]
IMO teleporting the player to an empty world seems like a bad decision. I think it would be better to just report an error (kick the player? throw an exception?).

**Comment by ST-DDT** [comment]
There shouldnt be a world to teleport him to.
Because you need a world to teleport a player if you don't have that world you cannot be teleported to it.

**Comment by JBYoshi** [comment]
I think this was accidentally closed? The above commit was supposed to close SpongePowered/Sponge#118.
