### ISSUE TITLE
Implement "weather.getName()" and "weather.getId()"

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#12]
Not implemented "weather.getName()" and "weather.getId()".
https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/weather/SpongeWeather.java

**Comment by Zidane** [comment]
@gabizou implemented this here: https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/weather/SpongeWeather.java
