### ISSUE TITLE
Configurable messages

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#122]
https://korobi.io/network/esper/channel/spongedev/logs/2015/08/09/#L797-815

`NetHandlerHandshakeTCP.processHandshake(C00Handshake)`:
- `"Outdated server! I\'m still on 1.8"`
- `"Outdated client! Please use 1.8"`

`ServerConfigurationManager.allowUserToConnect(SocketAddress, GameProfile)`:
- banned player:
  - `"You are banned from this server!\nReason: "`
  - `"\nYour ban will be removed on "`
- not whitelisted:
 - `"You are not white-listed on this server!"`
- banned IP:
  - `"Your IP address is banned from this server!\nReason: "`
  - `"\nYour ban will be removed on "`
- server full
  - `"The server is full!"`

**Comment by simon816** [comment]
For `allowUserToConnect`, the message can be changed in the `GameClientConnectEvent.setDisconnectMessage`

**Comment by kashike** [comment]
@simon816 The point of this issue is to make the "core" messages configurable for users who do not know how to write a plugin to change the message.

**Comment by zml2008** [comment]
Or the users could download a plugin that makes those messages configurable...

**Comment by Zidane** [comment]
Leaving this up to plugins...our only job is to provide these in events where relevant.

**Comment by simon816** [comment]
@Zidane Currently we don't have an event for the initial `C00Handshake` packet in the API. Should we add one?

**Comment by Zidane** [comment]
@simon816 

You can but its really only used for the message.
