### ISSUE TITLE
LegacyTextRepresentation replace method does not work as intended.

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#127]
https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/text/LegacyTextRepresentation.java#L180

**Input:** `&cK&ea&as&bhi&9k&de`
**Expected:** `§cK§ea§as§bhi§9k§de`
**Output:** `§§K§§a§as§bhi§§k§§e`

**Comment by kenzierocks** [comment]
Condition just needs to check that `result[pos] == from`.
