### ISSUE TITLE
DataProcessors and ValueProcessors need to handle ItemStack data

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#137]
Various entity related data can also be stored on `ItemStack`s, and it's being shown that various implementations are only partial to the more self-evident cases of an `Entity` being an obvious target, but the non-obvious target being an `ItemStack` that has an `EntityTag` `NBTTagCompound` filled with the necessary information to recreate the various `DataManipulator`s and `Value`s.

Some cases currently are
- [ ] [`CareerDataProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/data/entity/CareerDataProcessor.java)
- [ ] [`FoodDataProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/data/entity/FoodDataProcessor.java)
- [ ] [`HealthDataProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/data/entity/HealthDataProcessor.java)
- [ ] [`VelocityDataProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/data/entity/VelocityDataProcessor.java)

An example of a `DataProcessor` handling the cases of an `ItemStack` doing something properly is [`SignDataProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/data/tileentity/SignDataProcessor.java#L77-L96).

Tagging @SpongePowered/developers for future reference.

**Comment by JBYoshi** [comment]
@gabizou 
> the non-obvious target being an `ItemStack` that has an `EntityTag` `NBTTagCompound` filled with the necessary information to recreate the various `DataManipulator`s and `Value`s

That's not in 1.8. It will be part of 1.9, but that can wait until 1.9 is released.

**Comment by gabizou** [comment]
> That's not in 1.8. It will be part of 1.9, but that can wait until 1.9 is released.

Why should we limit ourselves to vanilla functionality when we can perfectly start storing the data onto `ItemStack`s NOW for plugins to use NOW?

**Comment by gabizou** [comment]
This is going to be resolved with the feature/schematic additions.
