### ISSUE TITLE
EntityHuman should likely use more Player related Data

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#145]
Currently, EntityHuman has a very limited set of use with the Data API, however, I believe that we should try to make EntityHuman use as much data that can be associated with it as possible, including the following:

- [ ] GameModeData

There's of course others that should be mentioned, but the matter remains, it currently doesn't follow much of the "use cases" that a `Player` would otherwise follow.

**Comment by simon816** [comment]
I had a list of things available to players that may or may not be relevant to humans, #46.
I don't think it really makes sense for humans to have gamemodes, it's exclusive to players. Humans are just another mob and I don't see how some features of gamemodes would work.

**Comment by gabizou** [comment]
> Humans are just another mob and I don't see how some features of gamemodes would work.

Yes, but there's various instances where plugins will want to know if the `Human` has a `GameMode` since `GameMode`s do have a huge play with regards to damage events, placement etc.

**Comment by Zidane** [comment]
Closing this as it sets a dangerous precedent.

EntityHuman is as alike to Players as Skeletons are in 1.9...they use the same model (Skeletons use a different texture albeit). In no way should they ever be considered "Just Players but not Players" and should be treated completely the same as Skeleton and Zombie.
