### ISSUE TITLE
EntityType Registry

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#146]
Trying to get an EntityType by its Id is not working.
For example ```game.getRegistry().getType(EntityType.class, EntityTypes.HORSE.getId())``` will return absent.

Getting an EntityType seems to only work with the Strings set here (Lowercased Fieldnames?):
https://github.com/SpongePowered/SpongeCommon/blob/a4f30c2daf499237d7551a3a5c77bfb47fddf1ad/src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java#L1830

So ```game.getRegistry().getType(EntityType.class, "horse")``` works
but not ```game.getRegistry().getType(EntityType.class, "minecraft:entityhorse")```

**Comment by Zidane** [comment]
@Faithcaio 

Unfortunately, Minecraft doesn't do it via "minecraft:entityhorse" unlike Blocks and Items which have the minecraft portion in it.

@bloodmc what do you want to do for this?

**Comment by ST-DDT** [comment]
> Unfortunately, Minecraft doesn't do it via "minecraft:entityhorse" unlike Blocks and Items which have the minecraft portion in it.

This has nothing to do with minecraft vanilla.
Sponge registers it that way.
IMO we should add the well known aliases as well. And especially enforce `T a = gr.getType(T.class, a.getId())`.
