### ISSUE TITLE
Restore Pre-1.8 Server Spawn Protection Behavior

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#15]
As some may know, in 1.8 the server disables spawn point protection if the server has no known OPs. In my opinion, this is an incredibly stupid design decision and, as evidenced by looking at various forum posts, many server admins were under a false impression that spawn protection broke.

Put simply, you shouldn't HAVE to have an OP specified for spawn protection work. Its an easy change to DedicatedServer to remove the if check.

@SpongePowered/developers thoughts?

**Comment by Deamon5550** [comment]
Seems very logical to me, from a safety standpoint you don't want the spawn protection to break if the ops.json file has any issues.

**Comment by gabizou** [comment]
I agree with @Deamon5550 on this. It does seem like a silly change that sadly shouldn't have been made in the first place.

**Comment by ZephireNZ** [comment]
Perhaps add this as an optional module (or to an existing one), similar to the other ones we have already? That way Sponge can be as vanilla as possible, or add in these "logical" changes if wanted.

**Comment by modwizcode** [comment]
Config option and yes this should be added.

**Comment by AnUnknownMiner** [comment]
Agree with this, I don't know what they were thinking.. :+1:

**Comment by Zidane** [comment]
Resolved by zml
