### ISSUE TITLE
Itemstack builder, allow negative or zero item quantity

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeCommon#150]
In a vanilla minecraft we can have itemstacks with 0 or even negative quantity. This vanilla feature(/ glitch?) can be useful in inventory menus.
![image](https://i.gyazo.com/0636d77e6dd8b004117d0b529b479c6c.png)
However sponge implementation of itemstackbuilder will throw an exception if someone tries to use value lesser or equal to zero.

Would be possible to remove this restriction?

**Comment by ST-DDT** [comment]
This is a quite nice feature for shop plugins.
However we should keep the restrictions in this call and add an `unsafeQuantity(int)` or `unboundQuantity(int)` one to ensure nobody accidentally set a zero or negative value.

**Comment by gabizou** [comment]
@Zidane should this be allowed? It's an easy change in the API and implementation.

**Comment by kashike** [comment]
I have to agree with @ST-DDT, this can be helpful in GUIs.

**Comment by gabizou** [comment]
The biggest issue with those types of itemstacks is they're prone to duplication glitches, and that is the last thing we want to encourage.

**Comment by Zidane** [comment]
@gabizou So long as you make sure to not allow dupes, you have a go.

**Comment by gabizou** [comment]
We'll allow zero quantity itemstacks, but we won't allow negative quantity itemstacks.

**Comment by simon816** [comment]
Like @ST-DDT suggested, I believe we need something like `unsafeQuantity`, perhaps just `zeroQuantity()`. It could be a programming error to set the quantity to 0 if using the `quantity(int)` method. It should be made explicit so the developer doesn't make an accidental mistake.

**Comment by kenzierocks** [comment]
I would prefer `unsafeQuantity(int)` so that I could use `0->whatever` without a branch.

**Comment by simon816** [comment]
@gabizou / @Zidane Is there confirmation for the following changes to be added to `ItemStack.Builder`?

```diff
          */
         Builder quantity(int quantity) throws IllegalArgumentException;
 
+        /**
+         * Sets the quantity of the item stack without doing validation on the
+         * maximum stack size. Allows quantity of zero but negative is not
+         * allowed.
+         *
+         * @param quantity The quantity of the item stack
+         * @return This builder, for chaining
+         */
+        Builder unsafeQuantity(int quantity);
+
         /**
          * Sets the {@link DataManipulator} to add to the {@link ItemStack}.
          *
```

**Comment by Cybermaxke** [comment]
This issue should be closed, negative quantities are no longer allowed in 1.11
