### ISSUE TITLE
juni94

### ISSUE THREAD

**Issue by samu05** [SpongePowered/SpongeCommon#153]

**Comment by kenzierocks** [comment]
plz

**Comment by Mumfrey** [comment]
I think we should consider this

**Comment by JBYoshi** [comment]
Okay... What is this all about?

**Comment by RobertHerhold** [comment]
juni94 is obviously the issue...

**Comment by zml2008** [comment]
Oh wow how could we have forgotten this!?!  Without this we pretty much don't have an implementation!

**Comment by mcsnetworks** [comment]
We simply cannot afford to finance such a large change at this time.

**Comment by jomo** [comment]
but what if juni94 was not kill?

**Comment by hsyyid** [comment]
We need this.

**Comment by JBYoshi** [comment]
What is juni94 anyway? Or was this all a joke?
