### ISSUE TITLE
NBTTranslator and byte/int arrays inconsistence

### ISSUE THREAD

**Issue by Xfel** [SpongePowered/SpongeCommon#156]
When using the NBTTranslator class to convert a NBT tree with ByteArrayTags or IntArrayTags to a DataContainer, it will properly represent these as byte[] or int[]. However, the resulting data container cannot be converted back, as the NBTTranslator.getBaseFromObject method will only convert Byte[], not byte[] (and the same for ints). Is this inconsistence intentional?

**Comment by gabizou** [comment]
Can you provide some code snippet for testing?

**Comment by Xfel** [comment]
```
// build NBT structure with ByteArrayTag
NBTTagCompound compound = new NBTTagCompound();
compound.setByteArray("test", new byte[]{12,13});

// translate to data container
DataContainer container = NbtTranslator.getInstance().translateFrom(compound);

// the ByteArrayTag is translated to a simple stored byte[] within the data container
assertTrue(Arrays.equals(new byte[]{12, 13},(byte[])container.get(new DataQuery("test")).get()));

// try to translate back
// will throw: "java.lang.IllegalArgumentException: Unable to translate object to NBTBase!
NBTTagCompound backTranslate = NbtTranslator.getInstance().translateData(container);
```
The general question here is: Shouldn't DataView support primitive type arrays? I can query for a List<Byte> so that would probably be the correct translation, but this is a horribly inefficient way to store this data. Also, if I translate a List<Byte> to NBT, I will get a NBTTagList containing NBTTagBytes.

**Comment by simon816** [comment]
I think it's happening because of this: https://github.com/SpongePowered/Sponge/commit/01d15339e12a17fcc1e4ade16622cd2764588f95#commitcomment-10376027

**Comment by gabizou** [comment]
So, here's the conundrum, either I store arrays as just arrays (whereby you cast from get(DataQuery) from Object)), or explicitly support arrays in `DataView`. Ultimately I do understand how it's happening, just a rather unfortunate reality of Java.
