### ISSUE TITLE
OP permission not given in SSP

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeCommon#16]
When running in SSP, even starting a LAN server with "Cheats" enabled doesn't give the overall OP permission. This prevents use of any higher level commands without a permission plugin installed.

**Comment by kenzierocks** [comment]
[This](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/entity/player/MixinEntityPlayerMP.java#L210) needs to be OP sensitive.

**Comment by zml2008** [comment]
no, that is not what needs to change. getParents() in UserSubject is what needs to be corrected (and I think it was corrected -- it worked last time I tried at least)

**Comment by zml2008** [comment]
Tested this, cannot reproduce. Works fine for me -- permissions are given based on the assigned op level for singleplayer with cheats.
