### ISSUE TITLE
DisplayNameData on books doesnt work correctly

### ISSUE THREAD

**Issue by lucdon** [SpongePowered/SpongeCommon#170]
found a bug:
if you set the display name of a book then it only sets the Name in the NbtSubCompound "display" and not the "title" value at the main compound. so when you try to get the display name again it looks for the "title value" which hasnt been set.

if i create the pageData first then the title gets set to "invalid" if i change the display name of the book it still stays "invalid" because DisplayNameData doesnt set the "title" of the book. 

the bug is only with a WRITTEN_BOOK created by ItemStackBuilder.
(note: i do use my implementation of pagedData, so pagedData is implemented for me)

stackTrace: 
```
[13:02:25] [Server thread/ERROR] [Sponge]: There was an issue trying to replace the display name of an itemstack!
java.lang.NullPointerException
	at org.spongepowered.common.data.processor.value.DisplayNameValueProcessor.getValueFromContainer(DisplayNameValueProcessor.java:70) ~[DisplayNameValueProcessor.class:?]
	at org.spongepowered.common.data.processor.common.AbstractSpongeValueProcessor.getApiValueFromContainer(AbstractSpongeValueProcessor.java:65) ~[AbstractSpongeValueProcessor.class:?]
	at org.spongepowered.common.data.processor.value.DisplayNameValueProcessor.offerToStore(DisplayNameValueProcessor.java:113) [DisplayNameValueProcessor.class:?]
	at org.spongepowered.common.data.processor.value.DisplayNameValueProcessor.offerToStore(DisplayNameValueProcessor.java:49) [DisplayNameValueProcessor.class:?]
	at org.spongepowered.common.data.util.ValueProcessorDelegate.offerToStore(ValueProcessorDelegate.java:103) [ValueProcessorDelegate.class:?]
	at net.minecraft.item.ItemStack.offer(ItemStack.java:104) [ItemStack.class:?]
	at luc.spells.rpg.spell.spellbook.RPGSpellBook.<init>(RPGSpellBook.java:40) [RPGSpellBook.class:?]
```
code used:

    this.book = RPGSpells.getInstance().getBase().getGame().getRegistry().createItemBuilder().itemType(ItemTypes.WRITTEN_BOOK).quantity(1).build();
        List<Text> pages = new ArrayList<Text>();
        pages.add(spell.asText().builder().append(Texts.of(TextColors.BLACK, "\n", "rarity: ", spell.getInfo().getRarity().format(), TextColors.BLACK, "\n", "description: ")).append(spell.getInfo().getDesc()).build());
        StringBuilder builder = new StringBuilder();
        builder.append("requirements: \n");
        for (SpellRequirement<?> req : requirements) {
            builder.append(Texts.toPlain(req.getReqAsText()));
        }
        pages.add(Texts.of(builder.toString()));
        this.reqs = Arrays.asList(requirements);
        this.book.offer(Keys.DISPLAY_NAME, spell.asText());  <-- line 40 
        this.book.offer(Keys.BOOK_PAGES, pages);
      
problem: 

this code in displayNameValueProcessor#getValueFromContainer does check if the item is a WRITTEN_BOOK: 

```
 else if (container instanceof ItemStack) {
            if (((ItemStack) container).getItem() == Items.written_book) {
                final NBTTagCompound mainCompound = ((ItemStack) container).getTagCompound();
                final String titleString = mainCompound.getString("title");
                return Optional.of(Texts.legacy().fromUnchecked(titleString));
            }
            final NBTTagCompound mainCompound = ((ItemStack) container).getSubCompound("display", false);
            if (mainCompound != null && mainCompound.hasKey("Name", 8)) {
                final String displayString = mainCompound.getString("Name");
                return Optional.of(Texts.legacy().fromUnchecked(displayString));
            } else {
                return Optional.absent();
            }
```
and here in DisplayNameValueProcessor#offerToStore doesnt: 

```
else if (container instanceof ItemStack) {
            final String legacy = Texts.legacy().to(value);
            final DataTransactionBuilder builder = DataTransactionBuilder.builder();
            try {
                final Optional<Value<Text>> optional = getApiValueFromContainer(container);
                ((ItemStack) container).setStackDisplayName(legacy);
                if (optional.isPresent()) {
                    builder.replace(optional.get().asImmutable());
                }
                return builder.success(new ImmutableSpongeValue<Text>(Keys.DISPLAY_NAME, value))
                        .result(DataTransactionResult.Type.SUCCESS).build();
            } catch (Exception e) {
                Sponge.getLogger().error("There was an issue trying to replace the display name of an itemstack!", e);
                return DataTransactionBuilder.errorResult(new ImmutableSpongeValue<Text>(Keys.DISPLAY_NAME, value));
            }
```

itemstack#setStackDisplayName does only set the subCompound "display" "Name" value

**Comment by ryantheleach** [comment]
Is it possible for a book to have a different display name then it's title? Or are they one and the same as far as minecraft is concerned?

**Comment by gabizou** [comment]
@ryantheleach It's possible to have a different title and display name. I vaguely remember this problem before hand and I seemingly forgot to pay attention to it when porting the display name processors.

**Comment by lucdon** [comment]
i see it has been fixed
