### ISSUE TITLE
Event implementation guide?

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeCommon#171]
I just wanted to create this to get started implementing some events that I would like to use. I have asked around a bit, but haven't gotten many solid responses, so I was wondering if someone could provide some more information. There is [a PR to the docs](https://github.com/SpongePowered/SpongeDocs/pull/321) for data implementation, but no such documentation exists for event implementation. Would anybody be willing to write that documentation, or at least provide enough information for me (or any other member of the docs team) to write the docs?

**Comment by JBYoshi** [comment]
To implement an event in SpongeForge, create a mixin targeting the Forge event and implementing the Sponge event interface, then fill in the methods.

To implement an event in SpongeCommon or SpongeVanilla, you'll need to mix in to the various locations where the event should be fired and add some code similar to [this](https://github.com/SpongePowered/SpongeCommon/blob/c3984ebf6ee1369ce81a69f5566c03d5447de224/src/main/java/org/spongepowered/common/mixin/core/entity/ai/MixinEntityAIMate.java).

**Comment by Aaron1011** [comment]
@JBYoshi: Unfortunately, the Great Event Refactor has made it much more complicated to use the corresponding Forge event.

@bloodmc can comment more on this, but the process requires syncing data between different Forge and Sponge event instances.

**Comment by Zerthick** [comment]
Any progress on this?  I'd like to start implementing some event's I'd like to use as well :smile:

**Comment by gabizou** [comment]
I believe this issue is closer related to the docs, and likely should be handled there.
