### ISSUE TITLE
add .launch files to .gitignore

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeCommon#182]
As wonderful as it is to have a matching launch configuration automagically generated when `gradle eclipse` is run, it not being ignored by the .gitignore file is rather annoying. Zidane told me to blame @Minecrell for this, which I gladly do.

Same Issue goes for Sponge (and I suppose SpongeVanilla)

**Comment by Minecrell** [comment]
There needs to be something else going wrong then, I added it in https://github.com/SpongePowered/SpongeCommon/commit/c21f90b9e71dc939c7fa3003e58ab8dcb0c87544#diff-a084b794bc0759e7a6b77810e01874f2R77

**Comment by saladoc** [comment]
My bad, I noticed this issue on sponge and immediatly assumed it was on SpongeCommon as well. Should I reopen this in the Sponge project? :D 
I have now double-checked and the line is only missing in Sponges .gitignore. SpongeVanilla and SpongeCommon are fine.

**Comment by Minecrell** [comment]
Oh I see, my bad - seems like I missed it there.
