### ISSUE TITLE
PSA for Contributing Mixins

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#186]
Due to the bump to Java 8, it has been discovered that the previous Java 8 attempt failed due to a hidden issue from the massive changes bundled. The issue stemmed from a Mixin failing to apply correctly, and namely, we were under the illusion that we simply couldn't mix in Java 8 code into Java 6.

Since our tests have started, we've found that not only can we succeed in the Java 8 upgrade, but I've personally narrowed the issues down to a mistaken use of Java 8 Lambdas. Lambdas are amazing, but they are at the cost of being syntactical sugar for writing anonymous classes like so:

```java
return new Predicate<ItemStack>() {
  @Override
  public boolean test(ItemStack input) {
    return input.getItem().equals(Items.golden_apple);
  }
}
``` 
into
```java
return input -> input.getItem().equals(Items.golden_apple);
```

The issue is that Mixins, while amazing and really useful, can NOT mixin the creation of these anonymous classes.

So, a PSA is being made about contributing mixing code where the following will NOT work:
```java
this::foo
```
```java
input -> input.bar()
```

To read more about Lambdas: [The Oracle documentation](https://docs.oracle.com/javase/tutorial/java/javaOO/lambdaexpressions.html)

**Comment by ST-DDT** [comment]
Is this a temporary issue with Java 6 
or a general issue with Mixins that will still apply when MC is updated to Java 8?

**Comment by gabizou** [comment]
It's an issue with Anonymous classes having a class reference to the Mixin class that doesn't exist at runtime.

**Comment by ST-DDT** [comment]
So theoretically it would be possible to update the Mixin tool to rewrite the internal class reference as well? Some kind of implicit `@Shadow` on a none existing field.

**Comment by gabizou** [comment]
I would think @Mumfrey can explain the horrors of anonymous classes and why Mixins still doesn't handle them.

**Comment by skinny121** [comment]
Although lambdas might be semantically the same thing as anonymous classes in bytecode they are completely different.

How it works is that the lambda body is extracted in another instance method(if the lambda is in an instance method) called something like lambda$get$0().  And where the lambda was declared is replaced by an call to LambdaMetafactory.metafactor(...)(actually an invokedynamic call but that doesn't really matter) which then creates the object representing the lambda expression.  One of the arguments to that LambdaMetafactory.metafactor(...) method is a reference to that synthetic method.

For example given this method:
java```
Supplier<Integer> add(int j){
        return ()->this.i+j;
}
```
So getting lambda expressions to work should be a lot easier than anonymous classes as it just needs
to inject the method and rewrite the method reference to include the new class.

**Comment by gabizou** [comment]
@SpongePowered/docs If possible, this issue should be resolved with the contributing docs and eventually updated with Mixin is able to appropriately handle anonymous classes and lambda relocations.
