### ISSUE TITLE
NPE on Interacting with Wolves

### ISSUE THREAD

**Issue by saladoc** [SpongePowered/SpongeCommon#189]
Interacting with a wolf while empty-handed will crash the server throwing an NPE. 
I think this is because the [MixinEntityWolf](https://github.com/SpongePowered/SpongeCommon/blame/master/src/main/java/org/spongepowered/common/mixin/core/entity/living/animal/MixinEntityWolf.java#L73) does not take into account that the currentItemStack may be null.

**Comment by TBlueF** [comment]
Could this be similar to #181?
