### ISSUE TITLE
SpongeCommon is downloading VanillaGradle when executing build script

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#2]
This is for @Minecrell 

Not so much an issue but more a question: Should common be pulling this dependency vs. SpongeVanilla?

**Comment by Minecrell** [comment]
Common is using the Vanilla Minecraft source, as this is the shared base we have for both implementations. In order to provide the Vanilla source we need to use VanillaGradle currently. SpongeVanilla is also using VanillaGradle, but Sponge is using ForgeGradle directly.

**Comment by Zidane** [comment]
@Minecrell 

Can you discuss on IRC further right now?

**Comment by Minecrell** [comment]
@Zidane I could join #lapis for like 5-10 minutes, but I gtg then and don't have the other channels setup from the iPad.

**Comment by Minecrell** [comment]
@Zidane I guess this is solved now, nobody mentioned additional problems in IRC after I explained why Common is using the Vanilla Minecraft source. The additional decompile time is of course kinda a problem, but let's hope that is going to be improved with FG2.
