### ISSUE TITLE
PlayerInteractBlockEvent performed twice.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#20]
PlayerInteractBlockEvent performed twice.
This occurs when:
I hold in my hand the subject;
The reason for the event - use.

CODE
```
    @Subscribe
    public void interact (PlayerInteractBlockEvent event){
        String interactionType = event.getInteractionType().getName();
        Text startEvent = Texts.of("Start PlayerInteractBlockEvent");
        Text inter = Texts.of("Cause: " + interactionType);
        Player player = event.getPlayer();
        player.sendMessage(inter);}
```

Job CODE
![2015-05-03_22 07 45](https://cloud.githubusercontent.com/assets/10154956/7445962/fcb0c416-f1e0-11e4-8ed7-261362282bf7.png)

**Comment by Zidane** [comment]
https://github.com/SpongePowered/Sponge/issues/260

Closing this to bring over all feedback to the other issue.
