### ISSUE TITLE
Expressing interest in Stone-data and Prismarine-data datamanipulator implimentation

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#206]
Per recommendation https://forums.spongepowered.org/t/so-many-ways-that-do-not-work-is-there-one-that-does/9590/5

I am making a post to show interest for some particular data-manipulators.
Requesting for data manipulators for stone-data (to allow placing/changing of granite, andesite, diorite blocks ) and prismarine-data (to allow placing/changing of prismarine bricks and darkprismarine blocks)

**Comment by gabizou** [comment]
This has been implemented.
