### ISSUE TITLE
DisplaceEntityEvent.Move.TargetPlayer fires when a player teleports

### ISSUE THREAD

**Issue by RobertHerhold** [SpongePowered/SpongeCommon#207]
Please correct me if I am wrong, but the `Move` event is only supposed to fire when a player walks, jumps, etc. However, if I use [this plugin](https://gist.github.com/RobertHerhold/3d97bb65895b0754e6c2) and teleport somewhere, the console will report that the `DisplaceEntityEvent.Move.TargetPlayer` has been fired, which it should not be doing.

**Comment by bloodmc** [comment]
This is intended as a teleport is still considered moving.
