### ISSUE TITLE
Simplify submodule initialization/updating and project setup

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#215]
> Come up with a mechanism to handle the hassle with dealing with submodules. This is not an open invitation to some bastard "run a shell script and it will setup some symlinked workspace for you". I'm thinking of an optional thing to run (as part of the toolchain) that would not only update submodules but also do setupDecompWorkspace. I welcome ideas on this one.

**Comment by JBYoshi** [comment]
If submodules are such a hassle, why does Sponge use them at all?

**Comment by Minecrell** [comment]
We would need a completely different project setup, and up to now there where no ways we came up with to remove the submodules without other disadvantages.

**Comment by JBYoshi** [comment]
@Minecrell "up to now"?

**Comment by Minecrell** [comment]
@JBYoshi Still none. Right now the plan is to make a Gradle plugin which will keep the submodules up to date and has a task which will setup the complete workspace, including decompiling etc.

The difficulty is to make it still possible to test submodule changes without having the plugin reset them every time the project is built.

**Comment by Zidane** [comment]
Closing this as our toolchain is fairly well handled by outside peeps and is arguably better than alternatives to Sponge.

Should outcry emerge, we can re-visit later.
