### ISSUE TITLE
Inconsistancy in CommandContext & CommandSpec (specifically GenericArguments)

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#218]
The command context components .getOne(), .getAll(), .hasAny() etc used in the the command executor retrieve a keyed-value that was designated by the command registration process, and that key isa String.  ie: 
`String warpname = (String) args.getOne("warpame").get();
`
Yet the parser setup assigns the keyname as a Text object.  
`CommandSpec cmdCreate =CommandSpec.builder()
.arguments(GenericArguments.onlyOne(GenericArguments.string(Texts.of("warpname")))).....
`

This is inconsistant -- and likely without need; are you really going to apply color styles and hover code to a parameter Keyvalue?  You can't do anything with it as a Text in this system except get the string value for use...  Is this a case of "Text-ify every string to avoid possible screwups" getting out of hand being used in the first place?  We dont even get to use a Text object at the downstream end, its been reduced to a String for the key...

There's been a lot of OCD-like changes made to parts of the code since its better to bite the bullet and do it now, rather than live with it, and while its been argued in many places and times why Text objects are used everywhere, and functions wont be overloaded with string alternatives, this doesnt seem like one where there is a need for the extra work putting it into Texts for no reason.  What does happen if an argument keyname does have color codes added - are they all stripped out when checked against the string key, or is the programmer out of luck, when you just gave him a new way to mess something up unnecessarily :)   

Is there a necessary need for these keys being created as Text objects that I'm not seeing at the other end, and they ARE used as Texts in some specific situation??  Or should this inconsistancy be thrown onto the "Synch up the 'set' and 'get' processes 'pile (either to throw out and use strings here only, or to add the extra code to make it a text object in the get process...)

**Comment by zml2008** [comment]
The usage of Text is for translatable parameter names -- usage messages use the Text representation.

**Comment by theboomer** [comment]
Translatable parameter names? What does that mean?
Why are the key parameters defined as Text keys, but accessed as String keys.  If Text is required to "modify" a string into a special thing that a string cant represent, then how is it supposed to be accessed when only a string is provided for the key accession?

**Comment by zml2008** [comment]
the string used as a mapping key is untranslated. the Text itself is what is sent to the user, translated into that user's language.

**Comment by theboomer** [comment]
So where in my code there does "warpname" appear to the user, and how can I modify this key so that it translates to whatever - again still though, im selecting the name for the key as 'warpname'.  Minecraft is capable of translating my keynames?  And it requires a Text to do so?

**Comment by gabizou** [comment]
I'm just going to take a gander that this also has to deal with text formatting, am I correct, @Minecrell and @zml2008 ?

**Comment by zml2008** [comment]
I don't think this is a valid issue -- it's a question about how to use Translatables (the refererence there is ResourcePackTranslationHelper, which has some appropriate example code).
