### ISSUE TITLE
Refactor DataConstants

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#219]
Currently, throughout the Data implementation, there are various "constants" that are thrown around, and some constants are not evident and in some cases, aren't retained between uses.

I'm working on a `DataConstants` class that will achieve something similar to what `NbtDataUtil` does with the `NbtTagCompound` related keys used in various places.

To see what I mean:
![DataConstants Example](http://puu.sh/kQSIH/ad3c989261.png)

**Comment by ST-DDT** [comment]
While this is a nice feature. I see an issue with these defaults. Some implementations do not have one default they choose their initial value at random (Career). At least they will not be available/known during API compile time.

**Comment by gabizou** [comment]
> Some implementations do not have one default they choose their initial value at random (Career).

Granted, but there's still a notion of "defaults" that all of Data encompasses around.



> At least they will not be available/known during API compile time.

No default should be known in the API as it's purely implementation detail, that's the reason for `getDefault()` in `BaseValue`, the issue stems from caching of `ImmutableValue`s such that having differing "defaults" for a specific `Key` will result in n times more possible combinations, while caching shouldn't have to deal with that many combinations.

**Comment by simon816** [comment]
@gabizou completed now?

**Comment by gabizou** [comment]
@simon816 no. I'll close it when I'm done going through it.
