### ISSUE TITLE
Errors with unqualified access to instance variables.

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeCommon#22]
These places don't use `this.` for access to instance variables:

- [MixinChunk:154](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L154)
- [MixinChunk:206](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinChunk.java#L206)
- [MixinWorldType:117](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldType.java#L117)
- [SpongeGame:113](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/SpongeGame.java#L113)

**Comment by Deamon5550** [comment]
Covered in #23
