### ISSUE TITLE
Sponge Error logs

### ISSUE THREAD

**Issue by UB1AFU** [SpongePowered/SpongeCommon#2332]
- SpongeForge version: spongeforge-1.12.2-2838-7.1.7-RC3870
- Java version: JRE 1.8.0_221
- Operating System: Windows 7 x64

- Plugins/Mods:
Included in the debug.log

**Issue Description**
Server has crash with a bug Sponge...idk

**Logs debug and latest with a problem**
https://gist.github.com/UB1AFU/60542a3fceee1425ded589ff02798e2f

**Comment by Zidane** [comment]
Another mod is conflicting with our Mixin. Remove mods, add them back (1 by 1), and find out who is conflicting. Reply back when you have and we'll re-open and see if there is anything we can do on our end.
