### ISSUE TITLE
Thrown potions can only be used if not looking at a block

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#236]
You must not be targeting a block to throw a potion. This breaks Vanilla behavior.

**Comment by Zidane** [comment]
Another thing this bug breaks is the fact that any interactions, when targeting a block, fail to execute the right click on the item in hand.

Good example is Portable Hole in Thaumcraft.

**Comment by saladoc** [comment]
Or trying to read a book
