### ISSUE TITLE
Canceling a CommandEvent causes "Command not found" warning in chat

### ISSUE THREAD

**Issue by boformer** [SpongePowered/SpongeCommon#24]
This happens when you cancel the event that refers to a registered command, 
and when you cancel an event that refers to an unknown command. Always.

Tested with different event orders (PRE, EARLY, LATE).

Expected behaviour: When you cancel a command event, no "Command not found" message should appear.

Tested with Sponge-1.8-1371-2.1DEV-437

This issue did not appear with old versions of Sponge (Pre 2.0).

I posted it here because both implementations share the command code.

Log with test plugin that cancels command:
```
/early
Mai 06, 2015 12:39:18 AM com.github.boformer.spongetest.SpongeTestPlugin onCommandEarly
INFORMATION: Cancelling command /early
[00:39:18] [Server thread/INFO]: Unknown command. Try /help for a list of commands
```

**Comment by Zidane** [comment]
I'd almost say its better to say no command found. My opinion though.

@SpongePowered/developers thoughts?

**Comment by Minecrell** [comment]
If a plugin wants to supress any command execution, e.g. by cancelling the `CommandEvent` and sending a message instead the unknown command message should really not be displayed. Cancelling the event should prevent any further processing.

**Comment by boformer** [comment]
Exactly.

**Comment by DDoS** [comment]
I don't like the idea of sending "Command not found". The server shouldn't lie about what commands it knows because it could cause some major confusion for users.

I think it should print a message defined by the canceller, with a default value of "Command cancelled" (with the source of the cancellation if possible).

**Comment by boformer** [comment]
@DDoS It should not send a message at all if a plugin cancels the event (the plugin can do that).

**Comment by DDoS** [comment]
I'm a bit worried about a plugin not doing that. When it comes to user stuff, you really don't want to be vague or unclear.

**Comment by zml2008** [comment]
When the event is cancelled, the result set in the event is used as the result. If no result is set, the command is treated as having not been found.
To suppress the message, set a command result in the CommandEvent when cancelling it.

**Comment by ST-DDT** [comment]
Is `SUCCESS` the right command result to det or should we have something like `CANCELLED` in the API? With and without message.

**Comment by zml2008** [comment]
There are CommandResult.success() for a generic successful command and CommandResult.empty() for a generic failed command. With not found message is an absent CommandResult (iirc setResult(null) in the event).

Since this is an issue of not marking the command event as handled, gonna close this.

**Comment by boformer** [comment]
This should be mentioned in the CommandEvent.setCancelled javadoc.
