### ISSUE TITLE
InteractEvent not firing for Primary click.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#247]
```scala
  @Listener
  def onArrow(event: org.spongepowered.api.event.action.InteractEvent) : Unit = {
    logger.warn("onArrow")
    val optPlayer = event.getCause.first(classOf[Player]).asScala
    //val optLocation = event.getInteractionPoint.asScala
    //logger.warn(s"onArrow $optPlayer , $optLocation")
    val optBlockRay = optPlayer.map (
      player =>
          {
              val rotation = player.getRotation
              val directon = Quaterniond.fromAxesAnglesDeg(rotation.getX,-rotation.getY,rotation.getZ).getDirection
              player.sendMessage(Texts.of(s"$directon"))
              BlockRay.from(player).blockLimit(6).build()
            }
    )
    logger.warn(s"onArrow $optBlockRay")
    optBlockRay.foreach(
      blockRay => {
        while (blockRay.hasNext) {
          blockRay.next().getLocation.setBlock(BlockTypes.BEDROCK.getDefaultState)
        }
        blockRay.end().asScala.foreach(
          end => end.getLocation.add(0, 10, 0).setBlock(BlockTypes.REDSTONE_BLOCK.getDefaultState)
        )
      }
    )
  }
```

InteractEvent when interacting with Nothing or air, currently does not fire for the primary click.

Tested using blood's redstone testing build with arrows in hand.

Additionally unless it's an Interact with an entity there is no way to tell if it was a Primary or Secondary interaction.

InteractBlockEvent also fires for right click in air, but has a strange location of 0,0,0.

**Comment by simon816** [comment]
> InteractBlockEvent also fires for right click in air, but has a strange location of 0,0,0.

Sounds like the return of https://github.com/SpongePowered/SpongeForge/issues/260

**Comment by bloodmc** [comment]
@ryantheleach Mojang does not send the server a packet when players left click air. The only way to determine this is to raytrace after receiving an animation packet which wouldn't always be accurate. InteractBlockEvent on right-click air showing location of 0,0,0 is a seperate issue. Open another issue for it.
