### ISSUE TITLE
Add Property changes to ChangeBlockEvent.Modify

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeCommon#255]
Currently the only thing stopping ChangeBlockEvent.Modify from being used as a perfect way to detect redstone changes is the absence of property changes calling the event. As 'PoweredProperty' is a property, and not a data value, it does not call the event.

**Comment by gabizou** [comment]
@me4502 @bloodmc has a redstone tracking branch that does add the event hooks for redstone.

**Comment by Zidane** [comment]
Redstone tracking is now in master.
