### ISSUE TITLE
Client lost connection message doesn't format correctly

### ISSUE THREAD

**Issue by l0lkj** [SpongePowered/SpongeCommon#259]
The message printed in console whenever a client disconnects from the server is not printed correctly. As it prints now: 
*[13:29:40] [Server thread/INFO]: l0lkj lost connection: TextComponent{text='Disconnected', siblings=[], style=Style{hasParent=false, color=null, bold=null, italic=null, underlined=null, obfuscated=null, clickEvent=null, hoverEvent=null, insertion=null}}*

Tested on:
jvm: 1.8.0_64
Forge: 11.14.3.1562 mc 1.8
sponge: 1.8-1521-2.1DEV-726

I talked with gratimax and he told me to report an issue here.

**Comment by kashike** [comment]
This is what vanilla does, Sponge doesn't break it.

**Comment by l0lkj** [comment]
Does vanilla own the TextComponent class, og Vanilla minecraft? Either way, it should be fixed as far as I am concerned. Gratimax said it should be an easy fix.

**Comment by kashike** [comment]
`TextComponent` is a vanilla class, yes. If anything, this is a Minecraft bug, not a Sponge bug.
https://bugs.mojang.com/browse/MC-59535

**Comment by l0lkj** [comment]
Okey, thank you for clearing that up. I'll close this issue :)
