### ISSUE TITLE
Bizzare scheduler issue when adding repeating task into a sequence of delayed tasks

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#260]
Zidane recommended posting here and tagging  @simon816 as nothing looked wrong (just odd :) ) with my issue cause.  I reduced it down to the simplest form of my plugin problem, chaining methods one after another scheduled with delays, which merely print to the log when executed.   I want to have 10 methods chained in a row, each one doing a job and scheduling a delayed call to the next phase method at different amounts.  Scheduling the sequence works fine to produce the output in the right order, and with approprate delays observed.  
But what I really want is for one of those phases to also initilize a repeating scheduled method, that runs in parallel no matter how long the other steps take, until one of the phases in the sequence later will cancel the repeating task.  (See image link: http://s.mpserv.net/4775579f865d5e23af980f118497d00c.png for visual representation of entire triggered chain of events)

Unfortunately, the addition of the repeating method scheduled task in the middle causes a total explosion of method calls logged, with the later phases logging thousdands of times in a mishmash of order, even though the repeating method called is not one of the ones in the sequence.  Its almost as if once generating the repeating task, the scheduler is stuck issuing repeating tasks, and it is ONLY the methods downstream of where the repeater scheduler was added which get repeated - the previous methods in the chain are not repeated due to 'perhaps something is constructing multiple instances of your class..'  In my real plugin that does things in those methods, the server exhausts itself to death after a couple minutes of hard lag and bizarre effects, in this test case reduction, the server can spew spam to the logs for at least 4 minutes before i just stopped it.

Sample code:  http://pastebin.com/vgaebXMD     creating an object of this class triggers the process chain.
Sample output log: http://pastebin.com/wSdXH4Zx

I've been struggling with this a few days, and reduced it to the barebones event addition with simply system log printouts.  I've upgraded and continue seeing the results in multiple forge / forgesponge and api combinations up to at the time of posting this:   Forge 1561, spongeforge 1561--Dev808 , api  #120   I dont know what further output i could produce that might be helpful, but i will try and fiddle with something after posting.

I have tried with tick delays and millisecond delays, tick-intervals and millisecond intervals both, and both systems give the same results.

**Comment by JBYoshi** [comment]
Ah... When you finish building a task, you simply reuse the same builder, retaining the same settings. So once you first set the `delayTicks`, all later tasks are configured as if you set the `delayTicks` on them as well. After you build each task, either grab a new builder object, or call `reset()` on the builder (if it exists).

**Comment by simon816** [comment]
@JBYoshi is correct. A builder is used to create a single instance, don't use it on another occasion.
In short, your method `phase4` calls `tbldr.intervalTicks`, this will set the interval for the builder, any future task creations from the builder will inherit the builder's configuration.

Simplest solution is to create a method that returns a new builder instance
```java
private TaskBuilder createBuilder() {
    return plugin.game.getScheduler().createTaskBuilder();
}
```
Then replace all accesses to `tbldr` with `createBuilder()`

**Comment by Deamon5550** [comment]
I find it a little odd that TaskBuilder has no reset method as that would also be a good solution.

**Comment by theboomer** [comment]
Perfect - I was certain it had to be something like that, and now thinking about it it does make sense..
I'll assume other builders work similarly then as well, where I have used them as a shared object

**Comment by ST-DDT** [comment]
Just for reference: [TaskBuilder]8https://github.com/SpongePowered/SpongeAPI/blob/9ae1a308a3e140074f57687fe245d2d3f785eb46/src/main/java/org/spongepowered/api/service/scheduler/TaskBuilder.java)

@simon816 If the builder is meant to be used only once, then subsequent calls after `build()` should throw an `IllegalStateException`. 
I expect the instance to either throw that Exception or clear the `Consumer`/`Runnable` so that I can I can reuse it with the same settings.

Those is closer to the expected behaviour that stacking up.

@Deamon5550 There is a [discussion](https://github.com/SpongePowered/SpongeAPI/issues/758) whether there should be a `reset()` method on builders in general.

**Comment by theboomer** [comment]
problem is that this is a builder that doesn't have a build() method per se

**Comment by ST-DDT** [comment]
@theboomer: Nope, some/most other builders overwrite previous settings such as ItemType etc instead of adding them twice/multiple times.

**Comment by theboomer** [comment]
that was my thinking behind reusing it, like the particle effect builder, doesn't give momenum to an effect made after one that does, etc ;)  So im glad its an 'interpretation' thing that is the source of the flaw here, if others have interpreted the same way, and something might be doable to 'save' people from hurting themselves

**Comment by gabizou** [comment]
`TaskBuilder#reset()` has been [implemented](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/service/scheduler/SpongeTaskBuilder.java#L127) now.
