### ISSUE TITLE
Redstone Tracking minor issue

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeCommon#267]
Hi,

So the following code listens for redstone nearby a sign triggering.

http://pastebin.com/RUyZ8EgD

Now, when the cause is printed to a string when a player toggles a lever near a sign, with a redstone wire separating it, the player is not in the cause.

This basically marks a place where a player is missing from the cause, when it should be in there.

Using the debug options in the client, I have determined that the sign is not being listed as notified by the player, whereas the redstone wire is. As it's being called in the notify event, shouldn't it have notifier set?

**Comment by bloodmc** [comment]
@me4502 I cannot reproduce this. You need to provide a test world and steps to reproduce.
