### ISSUE TITLE
Named Causes conflict.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#273]
http://pastebin.com/HmiCF8wh

I tried printing out the name in question:
"unknown0NamedCause"

Not sure how that is happening, but is instanceof somehow returning false?

**Comment by me4502** [comment]
Did you build from source? If so, make sure SpongeAPI is up to date.

**Comment by gravityfox** [comment]
i did:
git pull --all
git submodules update --recursive
gradle setupDecompWorkspace

**Comment by gravityfox** [comment]
I also noticed that block changes that happen on their own during chunk generation have their owner set to the player that generated them. 

As an example, as I was flying around, I saw a village, but when i hovered over the crops, it said I was the owner.

**Comment by gravityfox** [comment]
Just realized this issue belongs in SpongeAPI

**Comment by me4502** [comment]
Fixed.
