### ISSUE TITLE
Add option for Sponge Event Logging to be stored in separate file.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#280]
Sponge config has a section to allow logging of certain events. However these events have a tendency to clutter the console output and resultant log file. I think it would be best to add a config option to dump all this console log info into a separate file (and not in the console).

**Comment by ST-DDT** [comment]
IMO this can and should be configured in the Log4J2.xml config.

**Comment by Zidane** [comment]
I disagree on the premise that this would open the door to having every little thing be configured to go to another file and, ultimately, should be done in a log4j2 config file.
