### ISSUE TITLE
SpongeCommon won't compile

### ISSUE THREAD

**Issue by CrystalMageX** [SpongePowered/SpongeCommon#285]
"./gradlew" doesn't work.

[log.txt](https://github.com/SpongePowered/SpongeCommon/files/43333/log.txt)

**Comment by Mumfrey** [comment]
Please follow the instructions in the readme

**Comment by CrystalMageX** [comment]
Whoops. It seems that I forgot to do "setupDecompWorkspace" Sorry for that.
