### ISSUE TITLE
NbtTranslator has bad logic or formatting.

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeCommon#288]
[This line](https://github.com/SpongePowered/SpongeCommon/blob/11a77b370af6119cb660fcb4bc7a21b84f9d8654/src/main/java/org/spongepowered/common/service/persistence/NbtTranslator.java#L88) should be `else if` or formatted properly if it should be an `if`.

**Comment by CrystalMageX** [comment]
Definitely ```else if```, since it can't be a ```Boolean``` if it's an ```DataView```
