### ISSUE TITLE
Inconsistencies with DropItemEvent.Destruct Causes

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeCommon#295]
Hello All!  I've be messing around with detecting the Cause of a [DropItemEvent.Destruct](https://jd.spongepowered.org/org/spongepowered/api/event/item/inventory/DropItemEvent.Destruct.html) event and noticed a few inconsistencies.  The following are a few captures I've made:

Killing a chicken with a sword:
```Cause[{Name=unknown1org.spongepowered.common.entity.SpongeEntitySnapshot, Object={SpongeEntitySnapshot{uniqueId=16905ab3-2165-40d9-bc04-8b5ff3cb5546, entityType=SpongeEntityType{id=93, name=chicken, modid=minecraft, class=net.minecraft.entity.passive.EntityChicken}, position=(-87.52823482629321, 78.0, 286.9675926713128), rotation=(-22.073196411132812, 0.0, 0.0), scale=(1.0, 1.0, 1.0)}}}, {Name=unknown2net.minecraft.entity.player.EntityPlayerMP, Object={EntityPlayerMP['Zerthick'/460, l='world', x=-89.63, y=78.00, z=286.10]}}]```

Killing a chicken with a bow:
```Cause[{Name=unknown1net.minecraft.entity.projectile.EntityArrow, Object={EntityArrow['arrow'/1000, l='world', x=-91.91, y=77.50, z=278.48]}}, {Name=Owner, Object={EntityPlayerMP['Zerthick'/460, l='world', x=-94.46, y=77.00, z=279.59]}}]```

Zombie burning to death due to the sun:
```Cause[{Name=unknown1net.minecraft.entity.monster.EntityZombie, Object={EntityZombie['Zombie'/10017, l='world', x=0.25, y=80.00, z=273.13]}}]```

Notice that when killing the entity with a sword the cause contains an instance of EntitySnapshot, however when the environment kills the zombie the cause contains an instance of Entity, also note that when the entity is killed by a bow there is no reference to the entity killed at all, only the entity that fired the bow.  I'd like to propose a more consistent order for the cause of a DropItemEvent.Destruct event, like the root is always the block/entity that was destroyed and the other causes then follow in order.  I think it would make filtering Destruct events much easier.  I'll continue to update this ticket as I run more tests.

Thanks!

**Comment by Zerthick** [comment]
I've also discovered that when a piston breaks a block that can't be moved, like crops, the DropItemEvent.Destruct is not fired, however the more generic DropItemEvent is fired, is this the intended behavior?

**Comment by bloodmc** [comment]
@Zerthick please confirm this issue is resolved with latest build.

**Comment by Zerthick** [comment]
@bloodmc I can't of course confirm that it's working on the latest dev build, since one incorporating your changes doesn't exist yet, but running tests of a fresh build of master on my machine seems to have resolved the problem.  I like how you encapsulated the object doing the damage inside of either a DamageSource or IndirectDamageSource!  It will make filtering these events based on damage source much easier!  Thanks!
