### ISSUE TITLE
WeatherEffects Stopped Spawning [Again...]

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeCommon#299]
Using this code: http://pastebin.com/Z9Egjcdh

It appears that recently a change was made to SpongeCommon that resulted in WeatherEffects no longer working. The entity is spawned, however the corresponding weather effect is not being spawned. I am not sure if this issue is a mistake of my own, or an actual bug in SpongeCommon, so I figured I'd post an issue to find out. :smile:

**Comment by Deamon5550** [comment]
[The code is still there](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorld.java#L681). So I'm not sure what could be causing this.

**Comment by hsyyid** [comment]
@Deamon5550 Yeah, @kashike mentioned this - for some reason several of my users, as well as myself have noticed this issue as of late.

**Comment by simon816** [comment]
Tested and it seems `processingCaptureCause` is true when I attempted to spawn a lightning bolt (from a command) which means [that code is never executed](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorld.java#L582)

**Comment by simon816** [comment]
@bloodmc If this is the wrong _actual_ fix (i.e. `processingCaptureCause` should not be `true` when spawning weather) then please fix properly when you can
