### ISSUE TITLE
DisplayNameData throws AbstractMethodError...

### ISSUE THREAD

**Issue by MikaalSky** [SpongePowered/SpongeCommon#30]
Calling .getDisplayNameData() on a player throws an AbstractMethodError, which suggests it hasn't been implemented, but according to this: https://github.com/SpongePowered/SpongeCommon/issues/7, it has.

**Comment by Zidane** [comment]
Need more information. Paste some code.

**Comment by MikaalSky** [comment]
game.getServer().getPlayer(event.getSource().getName()).get().getDisplayNameData();

**Comment by gabizou** [comment]
The individual method is not implemented. The manipulator itself works and you can get the display name data by the traditional method getData.

**Comment by Zidane** [comment]
@gabizou 

Don't close the issue if the method he is using isn't implemented. Once it is, then it will be closed.

**Comment by gabizou** [comment]
Perfectly handled by #8.
