### ISSUE TITLE
SpawnEntityEvent does not fire when ExperienceOrbs Spawn

### ISSUE THREAD

**Issue by Zerthick** [SpongePowered/SpongeCommon#301]
Hello all, I've been fiddling with detecting when [ExperienceOrb](https://jd.spongepowered.org/org/spongepowered/api/entity/ExperienceOrb.html)s spawn and I've discovered that [SpawnEntityEvent](https://jd.spongepowered.org/org/spongepowered/api/event/entity/SpawnEntityEvent.html) does not fire when ExperienceOrbs spawn. Some sample code for my listener
```
    @Listener
    public void onExpSpawn(SpawnEntityEvent event){
        if(event.getEntities().contains(ExperienceOrb.class)){
            getLogger().info(event.getCause().toString());
        }
    }
```
This does not fire at all, I have tested exp from killing mobs, bottles 'o enchanting, and mining and smelting ore.

**Comment by bloodmc** [comment]
[10:03:17] [Server thread/INFO] [STDOUT]: [org.spongepowered.mod.plugin.SpongeWorldTest:onEntitySpawn:668]: SPAWNED ENTITY EntityXPOrb['Experience Orb'/1112, l='ChunkTest1', x=-395.55, y=65.00, z=150.45]

Definitely does work. Why are you checking for the class? I pass the actual Entity object, not the class. Just do the following check 

```java
for (Entity entity : event.getEntities()) {
    if (entity.getType() == EntityTypes.EXPERIENCE_ORB) {
        // do something
    }
}
```
