### ISSUE TITLE
Falling Block entities disappear immediately

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#305]
Falling block entities work fine if an entity is spawned at the location of a solid block of that type to convert the solid block to falling block.  But a falling block spawned in an air or water (or any unmatching default block-state block)  flickers into existance and disappears immediately.

Is this intentional?  Do we need to first convert a location into a particular block state, and THEN spawn a falling block entity of that same state at that location, as intentional design?  It does seem to be the way it works right how - using the following code to spawn a falling dirt nearby, the dirt flickers into and out of existance immediately, unless there is a dirt (or course dirt ) block in the target position already.

Or am I missing the second punch of a one-two punch with some other data to set simultaneously to override the instant-removal of the spawned entity?  Just trying to port many falling-block applications from Bukkit, and this is a big difference - bukkit spawns a falling block entity into existance where nothing was before.  If by design Sponge works oppositely to that, then it will be good to know; if sponge intended to work the same, then what is the correct process?  Well, the fact that sponge flickers a block perhaps means that it too does indeed spawn the block into existance, but then just destroys it immediately...

spongeforge 1577--867, forge 1577, api 
```java
	public void spawnFallingBlock(Player p) {
		Extent ext = p.getLocation().getExtent();
		BlockState dirt = BlockTypes.DIRT.getDefaultState();
		Location<World> bl = p.getLocation().add(3, 3, 3);
		Entity fb =
			ext.createEntity(EntityTypes.FALLING_BLOCK, bl.getPosition().floor().add(0.5, 0, 0.5)).get();
		fb.offer(Keys.FALLING_BLOCK_STATE, dirt);
		ext.spawnEntity(fb, Cause.of(this));
		broadcast("Spawned fb entity, what happened?");
	}

**Comment by kenzierocks** [comment]
You can set the time to 1. There's a Key for that.

**Comment by theboomer** [comment]
Ahhah yes, thank you that was the missing piece.  Its not really an obvious counter-paired setting to set though :) Is that a workaround that happens to work, or is that the way it is intended to be?

**Comment by kenzierocks** [comment]
It is the way the entity is written, but it should probably be changes in Sponge so keep this open.

**Comment by gabizou** [comment]
What key are you guys talking about?

**Comment by Zidane** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/1e08be13731af519e40899ce72f430826da19f0e
