### ISSUE TITLE
Timings should use the plugin id

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#307]
Currently, timings are currently using the plugin name in many places ([here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L91), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L93), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L191), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L193), [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/TimingsExport.java#L166), and [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/TimedEventListener.java#L57) - though I may have missed one). To be consistent, we should be returning the plugin id instead - we can provide the plugin name [here](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/TimingsExport.java#L166) to provide a friendly name that can be used, if necessary.

**Comment by Zidane** [comment]
@kashike 

Either @simon816 or myself will fix this up.

**Comment by kashike** [comment]
@Zidane If possible, it might be good to change [this](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/co/aikar/timings/SpongeTimingsFactory.java#L62) to be of `debug` type.
