### ISSUE TITLE
Directions incorrect on debug screen.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#316]
SpongeForge spongeforge-1.8-1577-2.1-DEV-884
![image](https://cloud.githubusercontent.com/assets/141554/11658897/508e156c-9e15-11e5-88df-918bb636bc83.png)

Vanilla 1.8.8
![image](https://cloud.githubusercontent.com/assets/141554/11658924/73cfb47c-9e15-11e5-8853-1e76c32581bf.png)

**Comment by gabizou** [comment]
For future reference, only SpongeForge can be on the client (so issues like this should be made in SpongeForge).

**Comment by ryantheleach** [comment]
I thought it may have been implying a deeper issue, rather then just the debug screen as I was struggling with directions again, but it was my own code fail instead.
