### ISSUE TITLE
Display name for human entity not hidden

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#318]
Skins work on human mobs just great now, thanks!  
But the ShowsDisplayName has no effect regardless of being set true or false, yet its offer result is a success in either case. Is this the wrong key to be using to hide the name overhead, and applies to somethinge else?  Is hiding the name possible?  (Setting to "" will still show  highlight space overhead, which is an okay compromise i guess)

```
		Entity ent = p.getLocation().getExtent().createEntity(EntityTypes.HUMAN, p.getLocation().getPosition()).get();
		System.out.println("uuid" + ent.offer(Keys.SKIN, p.getUniqueId()).getType()); // UUID.fromString("d816c61c-a38e-48d9-97ec-113c74e5d355"));
		System.out.println(ent.offer(Keys.DISPLAY_NAME, Texts.of("MyNameToBeHidden")).getType());
		System.out.println(ent.offer(Keys.SHOWS_DISPLAY_NAME, false).getType());
		p.getLocation().getExtent().spawnEntity(ent, Cause.of(this));

```
[17:19:58] [Server thread/INFO] [STDOUT]: [TESTER:doThing1:83]: uuidSUCCESS
[17:19:58] [Server thread/INFO] [STDOUT]: [TESTER:doThing1:84]: SUCCESS
[17:19:58] [Server thread/INFO] [STDOUT]: [TESTER:doThing1:85]: SUCCESS

**Comment by JBYoshi** [comment]
Looks like whoever wrote the `EntityHuman` class was aware of this, but it notes a potential workaround.
https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/entity/living/human/EntityHuman.java#L69
```
The label above the player's head is always visible unless the human is in
a team with invisible labels set to true. Could we leverage this at all?
```

**Comment by Aaron1011** [comment]
@theboomer @JBYoshi: The reason for this is that, as far as the client is concerned, Humans are actual Players. The only way to hide a player's display name is to set the nametag `Visibility` on a team, such that their nametag is only displayed to certain players.

It's an imperfect solution, but the only one that's possible in Vanilla. Making `Keys.SHOWS_DISPLAY_NAME` work for humans would require messing with the teams of other, actual players, which could have bad consequences for plugins. Instead, you'll need to manipulate `Team`s yourself.

**Comment by theboomer** [comment]
okay, manipulating the system to get an hidden display is fine.  Basically, Keys.SHOWS_DISPLAY_NAME doesn't apply to humans, its the wrong key / not work by design.  

So the process would be to create a team that no player belongs to and add the human mob to it, set nametag visibility for team....    shows-display-name not part of the equation after that still?

**Comment by Aaron1011** [comment]
@theboomer: You would need to set the visibility for the team that actual players are on. For example, you could set it to NONE

**Comment by Deamon5550** [comment]
We should change the it to not return success when offering to the entity if we're not going to support it.

**Comment by simon816** [comment]
The open question I left on EntityHuman was to suggest that Humans could be of a special team (internal sponge team - not accessible from API) in order to achieve the hiding name tag effect.
Would this be up for consideration or shall we just say you can't?

**Comment by Aaron1011** [comment]
@simon816: That won't work. Remember that a player can only be on one team, and it's the team of actual players (not humans) that really matters. There's no way to accomplish this automatically without messing with a player's scoreboard team behind the scenes, which we should not do.

**Comment by gabizou** [comment]
Yeah, to be honest, the issue is that data is simply saying it "supports" it, when it should not. The likelihood is that `DisplayNameData` is going to be split up so that it's properly handled (this is actually handled nicely because `ItemStack`s too can't be made to be "hidden".
