### ISSUE TITLE
Message in console: "Fetching addPacket for removed entity".

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#319]
Message in console: "Fetching addPacket for removed entity". What does it mean?

Code:
```
@Listener
public void onDropItem(DropItemEvent.Destruct event)
    List<Entity> entities = event.getEntities();
    entities.stream().forEach((entity) -> entity.remove());
}
```

Screen:
![image](https://cloud.githubusercontent.com/assets/10154956/11690920/a3d946a6-9eba-11e5-9975-3ebbb61a2f21.png)

Second question: What happens to the message LostConnection?

**Comment by kashike** [comment]
This is a vanilla warning, caused by the entity tracker entry calling `addPacket` when the tracked entity is dead.

**Comment by JBYoshi** [comment]
The "lost connection" message means the client left the server without notifying the server that it was about to leave. If you intentionally left the server, you can ignore this.

**Comment by kashike** [comment]
To add onto what @JBYoshi stated: If you're asking why the message is formatted like that, the answer is: that's the way it is in Vanilla.

**Comment by simon816** [comment]
You're calling `entity.remove()` which will remove the entity from the world. If you're wanting to remove it from the items in the drop event then use `event.filterEntities(Predicate)`

**Comment by Azatik** [comment]
@simon816 I need to remove them from the world.

**Comment by gabizou** [comment]
I think the issue is that `filter(Predicate)` doesn't actually mutate the list in the event, which makes sense in this case because the entities can't otherwise be removed (or we add a setter for the entities).
