### ISSUE TITLE
Dimensions stored by class name could lead to issues

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#320]
When writing to the compound tag of `level_sponge.dat`, `WorldInfo` stores: `dimensionType:"net.minecraft.world.WorldProviderSurface"` (as well as the respective class name for `WorldProviderEnd` and `WorldProviderHell`).
If the package or class name changes for the providers, things go boom - this is more likely to happen with mod-based providers, but there's always the chance that an MCP class name could change as well.

**Comment by gabizou** [comment]
> there's always the chance that an MCP class name could change

The likelihood of the vanilla classes changing are slim. Sadly, there's no real "identifier" we can enforce on dimension types since this is our API we're providing, and mods likely won't provide a string identifier anytime soon (short of their class name).

**Comment by simon816** [comment]
Aren't world providers registered in the `DimensionManager`?

**Comment by JBYoshi** [comment]
Yeah... there's `dimensionProviderType` (see `DimensionManager.getProviderType()`).
