### ISSUE TITLE
Cancelling block interact secondary does not prevent bucket use.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#327]
Exactly as it says on the tin.

If you cancel InteractBlockEvent.Secondary when someone tries to use a bucket, it will not prevent them from interacting with fluids. Water still places as normal.

It shouldn't do that.

**Comment by Zidane** [comment]
Fairly sure @bloodmc told me this needs to be cancelled in UseItemStackEvent. He can say better.

Remember that InteractBlock.Secondary is when a BLOCK is receiving a right click and you want to cancel that. It isn't when an ItemStack received a right click and you want to cancel that action.
