### ISSUE TITLE
Change the Sponge DataManipulators to extend the API abstract classes.

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeCommon#329]
With SpongePowered/SpongeAPI#940, the abstract superclasses used in SpongeCommon for the `DataManipulator`s (such as `AbstractIntData`) were moved to SpongeCommon. However, the old classes still remain in the implementation, and many manipulators still use them. Would it be possible to delete the abstract superclasses from SpongeCommon and change the manipulators to use the API versions of those classes?

**Comment by ZephireNZ** [comment]
One of the major roadblocks we have is that many of the Abstract classes provide caching functionality which the API implementations do not. The is mainly the boolean, enum and catalog typed values, as far as I'm aware.

**Comment by gabizou** [comment]
No. There's a reason why I didn't change their implementations. The API classes don't use any of the reflection utils or caching utils.
