### ISSUE TITLE
SyncScheduler has incorrect delay compensation

### ISSUE THREAD

**Issue by pqqqqq** [SpongePowered/SpongeCommon#33]
When using the SynchronousScheduler#runTaskAfter method (implemented by SyncScheduler), the delay given by the command in ticks is sometimes not used. For example, when using this code in a command:
```java
final long st1 = System.currentTimeMillis();
// Start a timeout schedule
plugin.getGame().getSyncScheduler().runTaskAfter(plugin, new Runnable() {
    public void run() {
        source.sendMessage(Texts.of(TextColors.AQUA, (System.currentTimeMillis() - st1)));
    }
}, 200);
```
Usually a server averages about 20tps, so this delay would be 10 seconds, however this value returns 51 milliseconds.

Doing a similar test with 2000 ticks (which is usually about 100 seconds) gives about 90000 milliseconds, which is closer to the estimated value.

**EDIT: After some testing, it's been determined that this issue only persists inside of a command. Running this during ServerStartingEvent or otherwise yields expected values.**

Sponge dev version: 1.8-1371-2.1DEV-443
Forge version: 1.8-11.14.1.1371

**Comment by RobertHerhold** [comment]
I ran into the same issue: SpongePowered/Sponge#220

**Comment by pqqqqq** [comment]
Didn't realize this was posted previously. Might as well bring an old issue back to life, especially with a reproducible way to experience it.

**Comment by RobertHerhold** [comment]
I still have the same issue today, so a resolution would be appreciated :)

**Comment by Zidane** [comment]
```
    @Subscribe
    public void onServerStarting(final ServerStartingEvent event) {
        final long st1 = System.currentTimeMillis();
        // Start a timeout schedule
        event.getGame().getSyncScheduler().runTaskAfter(this, new Runnable() {
            @Override
            public void run() {
                event.getGame().getServer().getConsole().sendMessage(Texts.of(TextColors.AQUA, (System.currentTimeMillis() - st1)));
            }
        }, 200);
    }
```

Outputs

```
[23:09:32] [Server thread/INFO]: 10010
```

I can't reproduce this now and I couldn't before but I used SpongeVanilla to test. Anyway either of you could pull it down and test on it? I can also try it with Sponge itself and see (though this mimic'd the results in the past).

What OS is everyone on? Windows 8.1 here. What JRE? Java 8 u 45 here.

**Comment by RobertHerhold** [comment]
I'll try it out again sometime tomorrow

Ubuntu 15.04, JRE 7u79 (OpenJDK)

**Comment by pqqqqq** [comment]
I can set up a quick SpongeVanilla server and test the same code on it. I'm on Windows 8.1 with Java 7 u 74.

**Comment by gabizou** [comment]
I just tested on Mac OS X with Java 8 update 45:

SpongeVanilla:
[21:12:35] [Server thread/INFO]: 10022

Sponge:
[21:46:53] [Server thread/INFO]: 10016

Aside from some minor delay using `ServerStartingEvent`, I wouldn't really see this as reproducible.

**Comment by kenzierocks** [comment]
So people with 7 have bug, with 8 do not? Might be JRE related.

**Comment by Zidane** [comment]
@pqqqqq 

Are you in the position of using Java 8? Could you try and see what your mileage is?

Could you also paste all of your plugin's code?

**Comment by pqqqqq** [comment]
@Zidane 
I've just tried this on java 8 u 45 and the same issue persists. I've tried it on both Sponge and SpongeVanilla on Windows 8.1. In addition, my Sponge public server running Linux ubuntu 14.04 java 8 u 45 (SUN jre) has the same issue. I'll message you the source since I'd rather keep it private.

**Comment by Zidane** [comment]
@Minecrell 

Read the OP's edit. Seems to happen when issuing this from a command. Want to take a look at this sometime?

**Comment by RobertHerhold** [comment]
The issue I was working on had the same setup. Command executed --> schedule task. I made a pull request for it: SpongePowered/Sponge#225 which I'm fairly certain is a valid fix. I could never reproduce the scheduled task working at the correct delay without it. I'll test this out again, and I'll post my results

**Comment by RobertHerhold** [comment]
...And I was correct! My PR does work! If you want to reproduce, checkout [my fork of SpongeCommon](https://github.com/RobertHerhold/SpongeCommon) and build it. I tested this with [BLWarps](https://github.com/BlockLaunch/BLWarps/releases/tag/v0.2.1). To reproduce:
* Use both the BLWarps plugin and my fork of SpongeCommon
* In game, make a warp: "/addwarp mywarp"
* Warp to the newly created warp: "/warp mywarp". After about 5 seconds, you will be given an error message (this is when you would have warped, but my plugin is broken).
* If you want proof, just run the same thing without my fork of SpongeCommon and compare results. When running "/warp mywarp", you will be given an error immediately rather than after 5 seconds.

I'm PR'ing this: #35
