### ISSUE TITLE
Features and Requests

### ISSUE THREAD

**Issue by Darktilldawn** [SpongePowered/SpongeCommon#330]
Player logging and tracking. Instead of having it log all the tracking through the console, add a log and folder for separate worlds to track and log everything that happens. The reason for the individual tracking logs is for plugin logability. So you can make a plugin that uses the actual sponge tracking logs for it's in game interface and Inspector tools and logging and tracing in game.

Folders
- Config
 - Sponge
   - Logs
     -  World(have to have the option to log multiple worlds)
        - Blockbreak.json
        - Blockmodify.json
        - Blockplace.json
        - Blockpopulate.json
        - Blocktracking.json
        - Chunkload.json
        - Chunkunload.json
        - Entitycollision.json
        - Entitydeath.json
        - Entitydespawn.json
        - Entityspawn.json
        - Entityspeedremoval.json
        - Logstacktraces.json

**Comment by me4502** [comment]
I don't believe sponge currently outputs all of that to the console?

**Comment by Darktilldawn** [comment]
It does, Talked to blood about it today. When you enable the logging features in the sponge config, it would log to your console everything I've posted up there.

**Comment by wizjany** [comment]
there's a big difference between outputting things to console for debugging and storing logs of everything that happens. storing all the info, both in disk and in memory, would be a performance nightmare. there's a reason that every logging plugin uses databases to store and retrieve records on a per-need basis.

**Comment by Darktilldawn** [comment]
Can't they make a database for all the logging then? Plugins are able to do with minimum performance or disk space.

**Comment by zml2008** [comment]
I see no reason for this to be built into Sponge. It makes more sense for this to be available as a plugin.

**Comment by Darktilldawn** [comment]
It seems pretty useless to have a console logging system for it if it's not going to log it to a readable file though?

**Comment by wizjany** [comment]
it's not a console logging system. it's a debugging system.

**Comment by Zidane** [comment]
This is a task for a plugin to do.
