### ISSUE TITLE
Cancelling ChangeBlockEvent.Modify Does Not Cancel Redstone Output

### ISSUE THREAD

**Issue by clucky** [SpongePowered/SpongeCommon#334]
In the case of buttons, levers, pressure plates, tripwire and any other block that outputs a redstone signal, cancelling the `ChangeBlockEvent.Modify` event does not cancel the redstone signal that is outputted immediately. There is a very short redstone signal output that is still sent out from the block, which is just long enough for a redstone repeater to detect. I would recommend that you use the test world that I provided to test this issue, as orientation of the redstone repeater can mean everything with this bug (redstone bugs are known to behave differently depending on the orientation). I have also provided a video, recorded in the test world, showing you the bug. I recorded this video from a second player, who is viewing the first player producing the bug, to eliminate any suspicion of client-side "ghosting". 

Here is the sample code that I used to produce this bug:
````
	@Listener
	public void onBlockModify(ChangeBlockEvent.Modify event, @Root Player player) {
		event.setCancelled(true);
	}
````

The world file can be found at http://www.risingcolonies.com/files/world.zip. The area I'm testing at is located at -840,4, 1075

And here's the video: https://www.youtube.com/watch?v=5cgStgLYLq0. Sorry about the sniffling, i'm getting sick :(

**Comment by bloodmc** [comment]
@clucky Have you tried cancelling the NotifyNeigborBlockEvent? This should happen before the modify and should fix the issue you are having. Just check permissions on all neighbor blocks and if any do not have correct permission, remove it from the list. The filterPredicate method is bugged so dont use that, just remove it directly from the neighbor list passed.

**Comment by bloodmc** [comment]
@clucky I'm implementing CollideBlockEvent which should be the best way to handle these type of events as the player will be the root cause.

**Comment by clucky** [comment]
@bloodmc I have not yet tried the NotifyNeighborBlockEvent. Would this CollideBlockEvent replace the need to do NotifyNeighborBlockEvent for pressure plates, or would that event still be required?

**Comment by bloodmc** [comment]
@clucky Cancelling CollideBlockEvent will remove the need to worry about NotifyNeigborBlockEvent. I'll be pushing it shortly.

**Comment by bloodmc** [comment]
@clucky Please confirm cancelling the CollideBlockEvent fixes your issue. Thanks!

**Comment by clucky** [comment]
@bloodmc It appears to correct the issue. Thanks
