### ISSUE TITLE
'/sponge plugins' fails when a plugin id has spaces.

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeCommon#338]
Clicking on one of the text entries produced by `/sponge plugins` does not work when the ID of the link's plugin contains spaces.

Do we want to allow spaces in plugin ids, or should the command be modified to support them?

**Comment by gabizou** [comment]
Plugin ID's with spaces are a bad thing since you can't parse over spaces in a command properly.

**Comment by simon816** [comment]
Perhaps the argument parser could handle quoted strings?

**Comment by Zidane** [comment]
Regardless of that @simon816 ...plugin ids shouldn't have spaces. That should prompt a plugin to fail loading lol.

**Comment by zml2008** [comment]
On December 18, 2015 3:29:02 PM PST, Chris Sanders <notifications@github.com> wrote:
>Regardless of that @simon816 ...plugin ids shouldn't have spaces. That
>should prompt a plugin to fail loading lol.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SpongePowered/SpongeCommon/issues/338#issuecomment-165920036

Anyways we already support both quoted and backslash escaped strings

**Comment by Minecrell** [comment]
This is fixed in https://github.com/SpongePowered/SpongeAPI/pull/1081, plugin IDs can no longer contain spaces.
