### ISSUE TITLE
Deobf jar not fully usable

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeCommon#339]
This (is/will be) partially fixed by #289, but the deobf jar is not easy to use at the moment. SpongeCommon must be present in some maven repo, which is not any right now. It also appears to generate a jar with `srg` names instead of `MCP` names, which means it doesn't work as a deobf jar.

@Minecrell.

**Comment by Minecrell** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/3bd77aa6b984224d5cc6a4e7563836f6b204f7dd
