### ISSUE TITLE
SpongeDamageSourceBuilder mutator methods have no effect

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#342]
https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/event/SpongeDamageSourceBuilder.java#L43-L76

The mutator methods simply return an instance of the builder without changing any of the builder's member data.

**Comment by kashike** [comment]
In addition, the `reset` method does not actually reset the builder.
