### ISSUE TITLE
CollideBlockEvent is not called at all times

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#343]
not called: `net.minecraft.block.Block#onEntityCollidedWithBlock(net.minecraft.world.World, net.minecraft.util.BlockPos, net.minecraft.block.state.IBlockState, net.minecraft.entity.Entity)`
and possibly more

**Comment by bloodmc** [comment]
This was fixed in commit

https://github.com/SpongePowered/SpongeCommon/commit/ff65dacfb3bd8e902b66a4dff1ee4caf552f3493
