### ISSUE TITLE
Allow configuration of Bukkit-style command aliases.

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeCommon#347]
In Bukkit, it was possible configure which command would take priority, if several were registered with the same name (the others will still acessible prefixed with the plugin name).

It would be nice to have a similar thing in Sponge, instead of an arbitrary (from a server owner's perspective) plugin getting to own the unprefixed command.

Pinging @zml2008.

**Comment by ST-DDT** [comment]
@Aaron1011 You are referring to a configurable (file based) solution instead of a 	programmatically (code based) solution, aren't you?

IMO thats the right way. 

However there are few other things to consider as well (at least one) as they are closely related.
Configurable command shortcuts:
````yml
/help: /userhelp:help
/spawn: /warp spawn
/tphere: /tp %1 %name
````

**Comment by Aaron1011** [comment]
It turns out we actually have this already, in `SpongeConfig#CommandsCategory`

**Comment by zml2008** [comment]
Yep. Any more extensive aliasing functionality like bukkit had imo belongs in a plugin (like CommandHelper)
