### ISSUE TITLE
Cancelling ChangeBlockEvent.Break from an explosion doesn't cancel the drops

### ISSUE THREAD

**Issue by JBYoshi** [SpongePowered/SpongeCommon#357]
This can cause block duplication, like in FoxDenStudio/FoxGuard#8.

**Comment by ryantheleach** [comment]
Talking to blood I think this is largely by design.

Block events in sponge are recorded, so all side effects will continue to take place. So you would need to listen to the appropriate events caused by this and cancel them...

**Comment by gravityfox** [comment]
The weird thing is that this doesn't happen if my plugin is the only thing installed on the server.

This behavior also appears extremely inconsistent.

**Comment by gravityfox** [comment]
So for some reason this stopped happening on the Sponge Community Server.

I think it was another plugin interfering with that particular event.

**Comment by bloodmc** [comment]
@gravityfox I'll look into this.

**Comment by bloodmc** [comment]
Cannot reproduce with latest builds.
