### ISSUE TITLE
Tasks will not stop if canceled during run()

### ISSUE THREAD

**Issue by ConnorStone** [SpongePowered/SpongeCommon#36]
Both Async and Sync Schedulers use the same similar code to process every task, every run.

```java
boolean bTaskStarted = startTask(task);
if (bTaskStarted) {
    task.setState(ScheduledTask.ScheduledTaskState.RUNNING);
```
startTask() ends up calling run() on the task as expected but the task is always set to the RUNNING state once completed, which means if task.cancel() is called during run() of the task, it will be ignored and set back to RUNNING, and never stop.

**Comment by ConnorStone** [comment]
Ping

**Comment by simon816** [comment]
I have fixed this in my scheduler cleanup PR. The state is set to running just _before_ it actually runs the task
See [`SchedulerBase#startTask`](https://github.com/SpongePowered/SpongeCommon/pull/47/files#diff-168ace8114caeb27d02b38cad72bc18eR177)
