### ISSUE TITLE
Custom data isn't retrieveable

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#362]
When i offer a custom data manipulator to an itemstack, i can see it in the datacontainter, but when i call get() it always returns an empty optional.

The itemstack creation code:
```java
WandData wandData = Sponge.getDataManager().getManipulatorBuilder(WandData.class).get().create();
if (args.length > 0) {
    WandType type = WandType.from(args[0]);
    if(type == null) throw new CommandException(Texts.of("Not a valid wand type!"));
    wandData.setWandType(type);
}
LoreData loreData = Sponge.getDataManager().getManipulatorBuilder(LoreData.class).get().create();
final ListValue<Text> lore = loreData.lore();
lore.add(Texts.of("Position Wand"));
loreData.set(lore);
ItemStack stack = ItemStack.of(ItemTypes.GOLDEN_AXE, 1);
stack.offer(wandData);
stack.offer(loreData);
stack.offer(Sponge.getDataManager().getManipulatorBuilder(EnchantmentData.class).get().create());

if (player.getItemInHand().isPresent()) {
    Entity entity = player.getWorld().createEntity(EntityTypes.ITEM, player.getLocation().getPosition()).get();
    entity.offer(Keys.REPRESENTED_ITEM, stack.createSnapshot());
    player.getWorld().spawnEntity(entity, Cause.of(FoxCoreMain.instance()));
} else {
    player.setItemInHand(stack);
}
```

The checking code:
```java
ItemStack item = player.getItemInHand().get();
if (item.get(WandData.class).isPresent()) {
    Vector3i pos = event.getTargetBlock().getPosition();
    List<Vector3i> positions = FCHelper.getPositions(player);
    if (event instanceof InteractBlockEvent.Primary) {
        if (positions.contains(pos)) {
            positions.remove(positions.lastIndexOf(pos));
            player.sendMessage(Texts.of(TextColors.GREEN, "Successfully removed position (" + pos.getX() + ", " + pos.getY() + ", " + pos.getZ() + ")!"));
            FCPacketManager.instance().sendPos(player, positions);
        }
    } else if (event instanceof InteractBlockEvent.Secondary) {
        positions.add(pos);
        player.sendMessage(Texts.of(TextColors.GREEN, "Successfully added position (" + pos.getX() + ", " + pos.getY() + ", " + pos.getZ() + ")!"));
        FCPacketManager.instance().sendPos(player, positions);
    }
event.setCancelled(true);
}
```

Optional#isPresent() always returns false, even if the held item clearly has the custom data.

**Comment by gravityfox** [comment]
With the recent data fix, Custom data is retrievable, but magically disappears after a few inventory updates. It comes back with a server restart, and disappears again.

https://gist.github.com/gravityfox/6a0421e3a6255f225be7

The first line is the result of toContainer() on an itemstack where data cannot be retrieved.
The second line is the same, but data is retrievable in this case.

Itemstacks start out printing the second line, but soon after print the first line.

**Comment by gravityfox** [comment]
Here's a more readable gist

https://gist.github.com/gravityfox/aa4987de4d1c68121949

**Comment by RobertHerhold** [comment]
@gabizou Is this in the pipeline somewhere?

**Comment by gabizou** [comment]
@gravityfox is this still actually happening? It's been a while since I've pushed a few fixes with regards to inventory movements and such.

**Comment by gravityfox** [comment]
I'm pretty sure it's been resolved, as the custom data based implementation has been out in the wild for awhile now and I haven't heard anything about it. 

I think this can be marked as resolved.

**Comment by RobertHerhold** [comment]
@gabizou I believe I've run into this issue again (assuming my data implementation is correct). [This](https://gist.github.com/RobertHerhold/f67023d9e1a5616f1c82b97f1633c5c6) is what I've been working with.

**Comment by gabizou** [comment]
@RobertHerhold You're not adding the `DataManipulator` to the builder. The builder does not know how to add custom manipulators from keys.
