### ISSUE TITLE
Right clicking daylight sensors fires a change and a place event, the latter of which causes dupe issues when cancelled, regardless of the handling of the former.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#363]
Instead of firing a single BlockChangeEvent.Modify, Right clicking a daylight sensor fires a BlockChangeEvent.Break followed by a BlockChangeEvent.Place.

Cancelling the events causes a dupe bug.

If you right click with an itemstack and then an empty hand, if both clicks are canceled in both the events, the itemstack will be duped to the empty hand.

**Comment by gravityfox** [comment]
Actually i found out.

It's not a break event followed by a place event.

It's a modify event followed by the place event.

cancelling the place event will give the player the last item used on a sensor globally, if and only if they have an empty hand.

This has also caused some players to end up with 0 or negative amounts of things.

**Comment by Aaron1011** [comment]
Confirmed on the latest SpongeForge.

@bloodmc: This appears to be a blocktracking-related issue. Something to note is that daylight sensors have two distinct blocks: `minecraft:daylight_detector` and ``minecraft:daylight_detector_inverted`.

**Comment by bloodmc** [comment]
@gravityfox OK i'll look into this issue soon.
