### ISSUE TITLE
Sponge causes custom world generation parameters to be ignored

### ISSUE THREAD

**Issue by Xenograph** [SpongePowered/SpongeCommon#369]
I'm running SpongeForge 968 and Forge 1577. The issue I'm having is that when I'm using custom world generator parameters, having SpongeForge loaded looks like it causes the world generation routine to ignore the custom parameters in the level.dat. That is, assuming we're using the same seed, the world generated with SpongeForge with the custom parameters specified is seemingly identical to the world generated without SpongeForge without the custom parameters specified. Or rather, changing the custom parameters seems to have no effect on world generation when SpongeForge is loaded. 

Here are the parameters we're using in our server.properties file:
```
level-type=CUSTOMIZED
generator-settings={"coordinateScale":684.412,"heightScale":684.412,"lowerLimitScale":512.0,"upperLimitScale":512.0,"depthNoiseScaleX":200.0,"depthNoiseScaleZ":200.0,"depthNoiseScaleExponent":0.5,"mainNoiseScaleX":1000.0,"mainNoiseScaleY":100.0,"mainNoiseScaleZ":1000.0,"baseSize":8.5,"stretchY":10.0,"biomeDepthWeight":1.0,"biomeDepthOffset":1.0,"biomeScaleWeight":3.0,"biomeScaleOffset":1.0,"seaLevel":63,"useCaves":true,"useDungeons":true,"dungeonChance":8,"useStrongholds":true,"useVillages":false,"useMineShafts":true,"useTemples":true,"useRavines":true,"useWaterLakes":true,"waterLakeChance":2,"useLavaLakes":true,"lavaLakeChance":80,"useLavaOceans":false,"fixedBiome":-1,"biomeSize":5,"riverSize":1,"dirtSize":33,"dirtCount":10,"dirtMinHeight":0,"dirtMaxHeight":256,"gravelSize":33,"gravelCount":8,"gravelMinHeight":0,"gravelMaxHeight":256,"graniteSize":33,"graniteCount":10,"graniteMinHeight":0,"graniteMaxHeight":160,"dioriteSize":33,"dioriteCount":10,"dioriteMinHeight":0,"dioriteMaxHeight":255,"andesiteSize":33,"andesiteCount":10,"andesiteMinHeight":0,"andesiteMaxHeight":255,"coalSize":17,"coalCount":20,"coalMinHeight":0,"coalMaxHeight":255,"ironSize":9,"ironCount":20,"ironMinHeight":0,"ironMaxHeight":192,"goldSize":9,"goldCount":2,"goldMinHeight":0,"goldMaxHeight":96,"redstoneSize":8,"redstoneCount":8,"redstoneMinHeight":0,"redstoneMaxHeight":255,"diamondSize":8,"diamondCount":1,"diamondMinHeight":0,"diamondMaxHeight":48,"lapisSize":7,"lapisCount":1,"lapisCenterHeight":16,"lapisSpread":255}
```

Note that it doesn't simply ignore the contents of the server.properties file, since I experienced similar results when copying over a level.dat that was known to contain the correct generation parameters. 

In my testing, I experienced similar results all the way back to SpongeForge build 880 (I didn't test further back than that).

**Comment by Xenograph** [comment]
I looked into the source to try and fix this myself, but ended up being unsure what the vision was for handling the DataContainer formatted world generation settings and properly converting them (if at all) back to JSON so that they could be used by ChunkProviderGenerate.

However, I think I may have fixed what may have been one of the underlying bugs causing this problem. The overwritten loadAllWorlds method in MixinMinecraftServer is (apparently, according to the original loadAllWorlds implementation) supposed to set the world name in the WorldSettings to the generator-settings string in the case that WorldInfo isn't loaded from the save handler. This definitely seems odd, but even the constructor WorldInfo(WorldSettings settings, String name) expects it to be that way. This change causes the biomes to be generated properly according to the parameters. 

As a temporary fix to get chunk generation working properly, I changed the MixinWorldType.getChunkGenerator method to get the generator options string directly from the WorldInfo in order to construct ChunkProviderGenerate. This is where I assume you guys were trying to do something special by allowing dynamic generation parameters or something along those lines. 

The patch to SpongeCommon that I'm using to get world generation working properly for myself until this is resolved is in [this gist here](https://gist.github.com/Xenograph/7627454e64501ba5c02c#file-worldgen-patch). Apologies if I'm misinterpreting things or not making much sense, this is my first time playing with reverse engineered Minecraft stuff.

**Comment by Zidane** [comment]
@simon816 fixed this in https://github.com/SpongePowered/SpongeCommon/commit/06f372936e8bd1e47112947b6906d27c6c8cd120

**Comment by Xenograph** [comment]
According to my tests 06f3729 did not resolve this issue. Custom generation settings in the server.properties file still seem to be ignored.

**Comment by simon816** [comment]
I see the problem. It's an MCP naming fail. In MCP it's called `WorldSettings.setWorldName` but it actually is `setGeneratorSettings` https://github.com/ModCoderPack/MCPBot-Issues/issues/61
Our code assumes it's a name and doesn't pass it to where it's meant to go

**Comment by Xenograph** [comment]
Nope, still not fixed in 0241fe2. At least, not with the JSON level-type=CUSTOMIZED settings, it might work with the level-type=FLAT formatted settings (in fact, I believe it should).

I think the issue is that on [this line](https://github.com/SpongePowered/SpongeCommon/blob/06f372936e8bd1e47112947b6906d27c6c8cd120/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldType.java#L134), createChunkGenerator is expecting the settings string in a format that Minecraft can accept, and as far as I can tell, we're not sending it the JSON string it's expecting. The [code here](https://github.com/SpongePowered/SpongeCommon/blob/06f372936e8bd1e47112947b6906d27c6c8cd120/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldType.java#L119) seems to be taking the parameters from the DataContainer and encoding it in some format that is not JSON.

**Comment by Aaron1011** [comment]
@Xenograph: Is this still an issue?

**Comment by Xenograph** [comment]
@Aaron1011 Just tested with a fresh clone and yes, the issue still exists. What I said in my last comment should still apply.

**Comment by simon816** [comment]
OK it HAS to be fixed by now -_-
