### ISSUE TITLE
Piston duplicate blocks if ChangeBlockEvent.break is cancelled.

### ISSUE THREAD

**Issue by Azatik** [SpongePowered/SpongeCommon#371]
Piston duplicate blocks if ChangeBlockEvent.break is cancelled.
Code:
```java
public class EventBreakBlock {
    @Listener
    public void onBteakGrave(ChangeBlockEvent.Break event) {
        event.setCancelled(true);
    }
}
```
Checked in SpongeFoorge 967 and SpongeVanilla 122.

Video:
https://youtu.be/qA_m65T1pQE

**Comment by bloodmc** [comment]
Working as intended as cancelling break has nothing to do with the place transaction. You will need to listen to the new ChangeBlockEvent.Post which will be pushed soon if you want to handle ALL transactions that occur when a piston extends.
