### ISSUE TITLE
ChangeBlockEvent.Break fired with misleading cause upon chunk generation

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#374]
ChangeBlockEvent.Break is fired upon chunk generation with a cause containing only the player.

Example: 
````
Cause[{Name=Source, Object={EntityPlayerMP['Dark_Arc'/208, l='Wilderness', x=274.00, y=116.00, z=2962.00]}}]
````

**Comment by bloodmc** [comment]
@DarkArc is this still an issue with latest build? If not, please close.

**Comment by DarkArc** [comment]
It's fixed for sure, sorry, I wasn't available yesterday.
