### ISSUE TITLE
getInventory().query(Hotbar.class)) returns wrong inventory row

### ISSUE THREAD

**Issue by NeumimTo** [SpongePowered/SpongeCommon#389]
getInventory().query(Hotbar.class)) returns bottom row of players inventory instead of hotbar

**Comment by clienthax** [comment]
@Mumfrey

**Comment by Mumfrey** [comment]
Should have been fixed a few days ago :/

**Comment by NeumimTo** [comment]
@Mumfrey I just tried build 1025 ,can't reproduce this issue anymore.
