### ISSUE TITLE
font-sizes.json requires particular encoding without ensuring it's loaded as such.

### ISSUE THREAD

**Issue by mbax** [SpongePowered/SpongeCommon#390]
https://gist.github.com/mbax/d12c97a06ce1683e7f6a

[font-sizes.json](https://github.com/SpongePowered/SpongeCommon/blob/850f9f95675c8bc3be9a9a711f84b7a1f3033d57/src/main/resources/org/spongepowered/common/service/pagination/font-sizes.json) contains characters that don't go over very well when loaded on certain standard encodings.

Works fine if loaded `-Dfile.encoding=utf-8` but making everyone do that is unnecessary. The file is inside the jar, just load it with the specified encoding! :)

**Comment by mbax** [comment]
For reference, several other folks have also encountered this problem. It's difficult because there is no indication that this is the cause.

In a conversation about this, I believe configuration was pointed at as the source of the bug. Is there an update which fixes this problem?

**Comment by Minecrell** [comment]
I could imagine https://github.com/zml2008/configurate/commit/b1344121ea895bc99d5e98074587bcaacd42869e could fix the issue, however I don't think @zml2008 has made a new release yet we could update to.

**Comment by Minecrell** [comment]
I think that should fix the problem. If it is still an issue, just comment here again.
