### ISSUE TITLE
Server Crash After I Got Killed by a Spider

### ISSUE THREAD

**Issue by Feeliiix** [SpongePowered/SpongeCommon#393]
After I got killed by a spider, the server crashed with this log:

Full Log: http://pastebin.com/4q9LNC1B (LAAG)
Short Log: http://pastie.org/private/lxd66rinbndyamzghtvfg

I think it's an inventory bug so i'm pinging @Mumfrey for this.

I'm on the latest SpongeForge.

**Comment by Aaron1011** [comment]
The issue appears to be due to `DefaultInventoryFabric` and `InventoryPlayer` mutually calling each other. See [this gist](https://gist.github.com/Aaron1011/196bbd2a281de0116c48).

**Comment by Aaron1011** [comment]
To reproduce this:

1) Place an item in your hotbar.
2) Switch to Survival
3) Die (fall damage, being attacked by a mob, etc)
4) Observe the stacktrace in the console.

**Comment by Aaron1011** [comment]
@Feeliiix: I think this is fixed in the the latest SpongeForge. Can you see if the issue is resolved?

**Comment by Feeliiix** [comment]
Fixed in 27705f6
