### ISSUE TITLE
Unable to get ImmutableGrowthData as mutable

### ISSUE THREAD

**Issue by Zbob750** [SpongePowered/SpongeCommon#397]
Apparently this is a known issue, creating ticket for tracking.

```java.lang.IllegalArgumentException: Applicable constructor not found for class: org.spongepowered.common.data.manipulator.mutable.block.SpongeGrowthData with args: [2, 0, 7, 0] ...```

Full stack trace also available here, as GH issues seems to mangle the readability. https://gist.github.com/Zbob750/ae1899f632a58e556d67

**Comment by Aaron1011** [comment]
@Zbob750: Is this still an issue?

**Comment by Zbob750** [comment]
IRC bump
```
<Z750> I have not tested to see if it is still an issue since the initial report
<Aaron1011> oh, that's a username :P
<Aaron1011> didn't realize you were in this channel
<Aaron1011> hello :)
<Z750> the stack trace linked in the issue has the code used at the bottom
<Z750> hi :)
<kashike> https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/manipulator/mutable/block/SpongeGrowthData.java
<kashike> 3 arg ctor, no 4 arg
<Aaron1011> ooh, right
<Z750> ^ that was the original issue yes
```
https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/manipulator/mutable/block/SpongeGrowthData.java
