### ISSUE TITLE
help command underline

### ISSUE THREAD

**Issue by seema84** [SpongePowered/SpongeCommon#399]
Hello,

i think it would be better, if the commandlist after /help display without underlines. (Letters are cut)

![](https://picload.org/image/wrdrcrl/helpcommand.png)

**Comment by ryantheleach** [comment]
It's a minor cosmetic thing, vs the hint to the user that it's clickable by being underlined like web links were.

**Comment by seema84** [comment]
yes its cosmetic but it looks not so good - maybe you find a other way to mark a clickable link

**Comment by Mumfrey** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  adam@eq2.serveftp.net
    Domain eq2.co.uk has exceeded the max emails per hour (71/60 (118%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext5.iad.github.net ([192.30.252.196]:38229 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by web3.cov.yesit.co.uk with esmtps (TLSv1.2:DHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86)
	(envelope-from <noreply@github.com>)
	id 1aGIKU-000CKz-PG
	for adam@eq2.co.uk; Tue, 05 Jan 2016 03:30:38 +0000
Date: Mon, 04 Jan 2016 19:29:57 -0800
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1451964597;
	bh=CuSkynzFWDqtf9lLwCp5Xj4/uVqLNBecdEDYepTZiRY=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=mXy2eO7ycxA0OeQEcUFxCx04dm+GhFkEtOXLs/CbXn0wszaV/9pQcFbBEh9SBFjFh
	 9HNZNx9HIe1JKQELniaOiy3cJcVkZEvhgFXaePyWtB142mL/k4P9fGwg+7RnjQxcdN
	 +/wTMKWK2JrWqyzRGq4h9jpVAFgZoKoIuelHeOFU=

**Comment by gravityfox** [comment]
Clickable text is often underlined.

The only reason i don't make the text in my plugin underlined is because LITERALLY EVERYTHING HAS A CLICK ACTION.


Sure you might not like it, but it's slightly more helpful to indicate it has an action.

**Comment by seema84** [comment]
Yes its helpful but other colors or [] are possibly helpful.

**Comment by kashike** [comment]
Another reason to not use underlining is resource packs that change the font/text style - it makes it hard to read at times.

**Comment by seema84** [comment]
And than a info "pls use a resource pack without underlining" ? :D I thinks thats not the best way.

**Comment by gravityfox** [comment]
honestly I say throw it into sponge.conf and be done with it. Let server owners decide how it should be formatted. Makes everyone's life easier.

**Comment by ST-DDT** [comment]
Or at least store that format in a psf const that could forcibly be overwritten at runtime/by impl if necessary. And you can change color and styles with a single field.

**Comment by gravityfox** [comment]
ACTUALLY SCREW EVERYTHING
JUST USE RAINBOW COLORS FOR ALL THE COMMANDS.
DONE.

**Comment by kenzierocks** [comment]
Please keep it civil on the issues, @gravityfox.

**Comment by gravityfox** [comment]
but rainbows tho.

My point is that this issue is rather trivial. Everyone is going to want something different.
Make it a config and be done with it.

**Comment by seema84** [comment]
It's not about that everyone else wants. I accept pink colors and what ever. But a cut Letters looks not good for all i think. We can also open a vanilla issu for change the line spacing.

**Comment by ryantheleach** [comment]
You can use https://forums.spongepowered.org/t/betterhelp-for-3-0-0/10709 for now. If there is any other issues that you want, please follow them up there. If there is common functionality that would be useful I may write it for both SpongeCommon and BetterHelp.

**Comment by seema84** [comment]
Looks good (better than with underline).  I would have preferred to sponge but this is also a solution.

**Comment by Zidane** [comment]
A plugin can change help to your liking. The sponge help menu remains standardized.
