### ISSUE TITLE
Incompatibility with Pixelmon (ConcurrentModificationException)

### ISSUE THREAD

**Issue by CrazyPyroEagle** [SpongePowered/SpongeCommon#406]
This bug has already been reported here: http://pixelmonmod.com/tracker.php?p=2&t=7611
I thought it might be best to report it here too since the developers seem to have ignored it.

This bug is recurring, not always at the same location, and really annoying as it crashes servers. The stack trace is always the same as that in the crash report given on the Pixelmon bug report.

Through analyzing the stack trace and the code, the bug sometimes occurs when a Pixelmon spawns. Something else is modifying the `ArrayList` as it gets iterated by the `MixinWorld`. Right now, I have only found one method that does this: `org.spongepowered.mod.event.SpongeForgeEventFactory.callEntityJoinWorldEvent`. The fact that this bug only affects Pixelmon is really strange. On top of that, many Pixelmon server owners using Forge claim to experience erratic crashes caused by this.

**Comment by gabizou** [comment]
It's mostly because of a bug introduced by PIxelmon to spawn entities off the netty thread, which as you can well imagine, is a different thread from the server thread, thus causing CME's. @clienthax can fill in more info about this.

**Comment by clienthax** [comment]
Yeah pretty sure this is a bug somewhere in our code. tracking it down however is a royal pain in the arse, we found one possible cause which is patched for 4.1.4

**Comment by clienthax** [comment]
@gabizou @CrazyPyroEagle This should be fixed from the first pixelmon 1.8.9 release (soon).

**Comment by CrazyPyroEagle** [comment]
@clienthax To avoid this occurring with any other mod, shouldn't Forge log a warning every time an entity is spawned in the wrong thread?

**Comment by Mumfrey** [comment]
That's a really expensive check to make in a very busy method, it's much better that modders avoid being idiots in the first place.
