### ISSUE TITLE
Requiring Documentation on Injects with numerical offsets

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeCommon#416]
Similar to SpongePowered/SpongeForge#231 I believe that we should start requiring documentation on all `@Inject`s which have opcode shifts (those with `BY` shifts https://github.com/SpongePowered/Mixin/blob/initphase/src/main/java/org/spongepowered/asm/mixin/injection/At.java#L53).

The reasoning for this is similar to that of documenting `@Overwrite`s as it is not always clear where the actual intended destination for the injection is, especially if the targeted method has be changed. Requiring a comment would preserve the intention of the injection allowing later developers to ensure that it is still correct even if the targeted method has changed.

The format of this comment would be similar to that of an overwrite. The important part of the comment is explaining what the actual intended target of the injection is. For example:

``` java
/**
 * @author Deamon
 *
 * @reason Does something, the injection is offset by minus two to be just
 * before the action of blah...
 */
@Inject(method = "foo", at = @At(value = "INVOKE", target = "Lnet/minecraft/FooType;bar()V", shift = At.Shift.BY, by = -2))
public void doSomething() {
// etc
```

As always discussion is welcome, especially on what information should be required or optional in this comment.

**Comment by Zidane** [comment]
I'm closing this as I feel this should be re-opened as a possible toggle-able option in Mixin with a warning that gets triggered.

@Mumfrey may disagree though..

**Comment by Mumfrey** [comment]
My official position is that basically any `Shift-By` with a `by` value greater than 1 should be replaced with slices. Slices are more expressive and have better fail-fast behaviour. Since this feature has been in the wild for some time, I feel like it's justified to set `WARN` threshold on `by` values and guide people towards writing with slices as a better solution.
