### ISSUE TITLE
Sponge is not loading resources in dev environment.

### ISSUE THREAD

**Issue by Meegooo** [SpongePowered/SpongeCommon#417]
I was trying to add localization to my plugin, when I realised, that .properties files are not being loaded. [Here](https://github.com/Meegooo/ExamplePlugin)'s the quick plugin I made just to showcase this issue. If you launch `main()` it outputs  

    Locale = en_US, key = key, value = value
    Locale = de_DE, key = key, value = value_de

But when you launch SpongeForge or SpongeVanilla from the same workspace, it throws [this](https://gist.github.com/Meegooo/c516931e5dda19308eee)

Now, I remember there [was an issue](http://stackoverflow.com/questions/27623326/minecraft-forge-not-loading-textures), when IDEA wasn't loading resources from Gradle projects. But those fixes don't work with Sponge and 1.8 from my experience. Also, as far as I know it was fixed in ForgeGradle 2.0. And indeed, if you replace Sponge plugin with [Forge mod](https://gist.github.com/Meegooo/dcf92571abca99c17aa8) (replace `@Plugin` with `@Mod` and use `FMLPreInitializationEvent` instead of `GamePreInitializationEvent` AND use Forge's default workspace instead of Sponge's) everything loads fine and [outputs correctly](http://i.imgur.com/ywwIHZw.png). But when you use Sponge's workspace and trying to launch mod, not plugin, it still [crashes](https://gist.github.com/Meegooo/8d79d5117bfee7d29d21) 

I tried using Forge's workspace and adding sponge as a mod (dropping dev SpongeForge in mods folder). It asked me for Mixins. I added those as a gradle dependency and suddenly even `main()` started to threw MissingResourceException, even after I deleted SpongeForge and Mixins. Don't know what the deal was here, but I don't wanna do that again...

In production everything works correctly. I built jar file of my ExamplePlugin, threw it on regular SpongeForge server and it launched with correct output (as shown above).

Extra info
I'm using IDEA Ultimate 15.0.1. Don't have Eclipse, so didn't check there.
My SpongeForge clone's HEAD is [here](https://github.com/SpongePowered/SpongeForge/tree/c3eed0fc73c8fb740466709704f8cb66acbc149b)

PS. It may be related to SpongeGradle, so I'm not sure if this issue should be posted here on in SpongeGradle repo.

**Comment by Meegooo** [comment]
So, I checked and apparently .properties files were not in classpath at all. So, I was able to fix that by adding resources folder as a dependency to my plugin. Like [that](http://i.imgur.com/LbcbfCh.png)

**Comment by Meegooo** [comment]
And in the end it was completely fixed by choosing "Inherit project compile output path" in Paths tab of Project Structure window. [Like that](http://i.imgur.com/QNnV3fG.png). 

Also, as Minecrell told me, it can be fixed by adding `idea { module { inheritOutputDirs = true } }` to build.gradle of plugin

**Comment by Zidane** [comment]
I never knew of the above...that is likely the issue I had where my Mod won't pull from resources directory.

Thanks @Minecrell and @Meegooo .

**Comment by ryantheleach** [comment]
Yeah you are 100% correct, just ran into this myself and wouldn't have been able to fix it without your help. Thanks.
