### ISSUE TITLE
Inventory only partially updating on Client

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#418]
This is a small Testplugin i wrote to track down the issue:
http://pastie.org/private/h9vsite5c9qsfgvjjp75dw

To reproduce:
- right-click on a block.
- right-click on a block with at least 2 books in hand
- books get replaces with enchanted book but the others won't show
  -  until you interact with the first "empty" inventory slot

This does not happen when using InteractBlockEvent.Primary instead.

**Comment by catageek** [comment]
Another example: Remove an item with Slot.clear(), the item will be shown until we interact with it.

**Comment by Zidane** [comment]
@Grinch tested both of these issues and wasn't able to reproduce this. Reopen if still an issue.
