### ISSUE TITLE
Lightning set to be an effect still creates fire

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#420]
````java
Location<World> loc = ...;
Optional<Entity> optLightning = loc.getExtent().createEntity(EntityTypes.LIGHTNING, loc.getPosition());
if (optLightning.isPresent()) {
    Lightning lightning = (Lightning) optLightning.get();
    lightning.setEffect(true);
    loc.getExtent().spawnEntity(lightning, Cause.of(this));
}
````

Per the java-docs when setEffect is set to true lightning should not do damage, and thus should not create fire.

**Comment by Aaron1011** [comment]
@DarkArc: I'm having trouble reproducing this. Can you give me a test plugin that can easily reproduce it?

**Comment by DarkArc** [comment]
@Aaron1011 seems it's been fixed by something (either from updating Forge or Sponge, made the 1.8.9 jump) either way, no longer an issue.

**Comment by DarkArc** [comment]
This is back.

**Comment by modwizcode** [comment]
I'll look into this

**Comment by simon816** [comment]
@DarkArc I can't reproduce this on the latest SpongeForge. Is there still an issue?

**Comment by DarkArc** [comment]
@simon816 I'm still seeing fire blocks.

**Comment by simon816** [comment]
Oh I think I had the difficulty level set incorrectly. I've reproduced it now.
