### ISSUE TITLE
Translations are broken

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#421]
related: #336 

A few issues:
- https://github.com/SpongePowered/SpongeCommon/commit/1a560d6ccdacb1d2413fba0944acee61a291d5fe removed the `Locale` parameter from everything
 - causes the wrong values to be sent
- https://github.com/SpongePowered/SpongeCommon/commit/1a560d6ccdacb1d2413fba0944acee61a291d5fe#diff-b4d0e9569b06553fcdd519666dfb010dR45
 - Only some translations are available to the client - Mojang ones. Need to perform translation/etc and return `ChatComponentText` here, depending on provided `Translation`

```java
DemoTranslation translation = new DemoTranslation();
source.sendMessage(Text.of(translation));
source.sendMessage(Text.of(translation.get(source.getLocale())));
```

```java
    public static class DemoTranslation implements Translation {

        @Override
        public String getId() {
            return "demo.key";
        }

        @Override
        public String get(Locale locale) {
            if (locale == Locales.EN_US) {
                return "Meow!";
            } else if(locale == Locales.DE_DE) {
                return "Mew mew!";
            }
            return "wat(" + locale.toString() + ')';
        }

        @Override
        public String get(Locale locale, Object... args) {
            return this.get(locale);
        }
    }
```

Output:
```
[20:14:13] [Client thread/INFO]: [CHAT] demo.key
[20:14:13] [Client thread/INFO]: [CHAT] Meow!
```

Expected output:
```
[20:14:13] [Client thread/INFO]: [CHAT] Meow!
[20:14:13] [Client thread/INFO]: [CHAT] Meow!
```

**Comment by Minecrell** [comment]
This is not exactly a bug; this was removed on purpose because these are very likely better handled together with Text Templates which will be coming soon.

**Comment by kashike** [comment]
And for people who do not want to use text templates?

**Comment by TheRaspPie** [comment]
@kashike The goal of the Text API is to model Mojang's JSON text format as exact as possible, as @gratimax said earlier. So if you send text to a player, it can only contain the following text types:
- `LiteralText` (a `String` with formatting)
- `ScoreText` (to display a scoreboard score on the client)
- `SelectorText` (to resolve a selector on the client)
- `TranslatableText` (to let the client translate the message with a given id and arguments with its translation files or resource packs)

The goal of the text templates is to provide server-side translation, replacements and so on.
Although it would be more convenient to use the pseudo-server-side translation of TranslatableText,
I think we get the cleaner separation of concerns with text templates in the long run.

An issue is, however, that the `Translation` interface is confusing, as it looks like you could implement it yourself and pass it to `TranslatableText`, only to notice that it doesn't get translated.
Maybe this is something for SpongeDocs or SpongeAPI to change. I will open a related issue there.

Sorry if you knew all this before, I just wanted to write it down as there have been so many misconceptions about how the Text API is supposed to work in the past.

**Comment by kashike** [comment]
@TheRaspPie I'm well aware of the goals of the Text API, as well as the possible types that can be sent.

Before the Text API v3 revision (https://github.com/SpongePowered/SpongeCommon/commit/1a560d6ccdacb1d2413fba0944acee61a291d5fe) this worked as expected, @Minecrell intentionally broke it.

**Comment by TheRaspPie** [comment]
@kashike Ok, I see. I didn't know it was ever implemented.

**Comment by kashike** [comment]
It'd be nice to get this reverted or fixed soon.

**Comment by Minecrell** [comment]
I'm going to close this - the changes were intentional because the old API implied it was usable everywhere, even though it was only properly working for chat messages. As soon as the messages were serialized the translations were gone, even though per design of the Text API a text should always stay the same. SpongePowered/SpongeAPI#1088 will be the replacement for the old API.
