### ISSUE TITLE
Extraneous decay events

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#424]
Decay events are thrown in mass quantities with both original/final blocks listed as "minecraft:leaves". After debugging the block state it appears that each time they're fired, the `check_decay` value has flipped.

    minecraft:leaves[check_decay=true,decayable=true,variant=oak]
    minecraft:leaves[check_decay=false,decayable=true,variant=oak]
    minecraft:leaves[check_decay=true,decayable=true,variant=birch]
    minecraft:leaves[check_decay=false,decayable=true,variant=birch]

@bloodmc

**Comment by bloodmc** [comment]
This is normal. Decay events are fired throughout the entire process not just when a block breaks.

**Comment by viveleroi** [comment]
That seems counter-intuitive. If a block has decayed, yet not vanished, the net effect is... nothing? If the only way to know when a block as *broken* due to *decay* is to listen to `Break` events, then I have another use case for #426

**Comment by bloodmc** [comment]
You simply check the final transaction and if it is air then the decay process is complete. I do not see an issue with this as blocks do not just decay instantly, it is a "process".

**Comment by viveleroi** [comment]
Is there a break event fired at all, then? I'd rather listen directly for the break than check final transaction of an event that fires every tick for every leaf block loaded for every current player.

**Comment by bloodmc** [comment]
OK I'll fix this soon.
