### ISSUE TITLE
Naturally flowing liquids occasionally include Player in cause chain

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#425]
A large number of `ChangeBlockEvent.Place` events are firing when liquids flow naturally (without any player involvement, other than being present) which include a `Player` in the `Cause` chain.

While generating new chunks by walking, the events fire with `Cause: net.minecraft.entity.player.EntityPlayerMP`.

@bloodmc

**Comment by bloodmc** [comment]
I'll look into this soon.
