### ISSUE TITLE
Additional classification of block events (spread, flow, etc)

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#426]
Currently, both liquid flow and grass spread (among others) fire `ChangeBlockEvent.Place`. It would be helpful if there was an additional subclass that could further classify these.

A use case would be excluding flow/spread events, while processing other place events. Currently the only way to do this is to check the details of the blocks/cause which is inefficient and not future-proof.

@bloodmc

**Comment by bloodmc** [comment]
You should be able to handle this by checking the root cause.

**Comment by viveleroi** [comment]
Can you clarify this?

I assume what you mean is that I'll know if it's *spread* if the cause was a `Grass` block? My problem with this is that it means I have to hard-code checks for specific causes. If I forget about `mycelium` it's not caught, and if plugins/mods ever add their own, I'm out of luck.

**Comment by bloodmc** [comment]
Please pastebin some transactions you are seeing for liquid flow and grass spread as I currently do not have a workspace setup.

**Comment by viveleroi** [comment]
I won't be able to do this until later today but essentially the original block is dirt, the replacement is grass, and the event was `ChangeBlockEvent.Place`. It's grass spreading in reality, but in order for me to filter that out I have to a) ensure it's not a player, b) ensure the root cause is a block I know can spread, and c) somehow feel confident that the cause block could never place a block except by spreading. A is easy, but B and C are not and will require me to hard-code block checks.

**Comment by bloodmc** [comment]
B is the same issue Sponge will have with mods. How do I know if a mod block is causing a spread without knowing what the mod does? This is one of the main reasons I am really cautious when adding more classifications to ChangeBlockEvent. Sure we could get the same type of event added to Forge for mods but we would fall into the same big issue MCPC/Cauldron had which is mods that never fire said event.

**Comment by viveleroi** [comment]
It shouldn't be sponge's responsibility to fire/identify the right events for mods. If something isn't classified correctly that should be on the mod author. Better classifications would at least be the appropriate avenue for mods to describe what's happening. 

Prism (and other plugins) would have no hope of knowing what's a "spread" versus a legit "place" without better classifications. Plugins will wind up having redundant hard-coded logic for vanilla blocks but mod-based events will probably be ignored.

**Comment by bloodmc** [comment]
I'll look into adding a new NamedCause that represents a "Spread".

**Comment by theboomer** [comment]
Necroquery:
Why do the environmental block changes: Dirt-> Grass, Grass->Dirt, SnowcappedGrass->Grass, etc register as PLACE events - I can appreciate it for the tilled soil as a player block placement, even though it really isn't...
Why is it not modify?

Place implies  "put something into a volume of space which does not have anything in it" just as Break implies "remove something from a volume that leaves empty space"
Modify is "Keep your eye focused on that particular volume, and presto-chango, it has transformed from one thing into another in that same location"

**Comment by wizjany** [comment]
if you place a solid block on a "replaceable" block, like tall grass, is that a place or a modify?

**Comment by JBYoshi** [comment]
It's a place. `Place` is any change in the block type; `Modify` is a change in the block state but not the block type.

**Comment by ryantheleach** [comment]
@JBYoshi I believe blood has stated previously that he was erroneous to decide that was the case, I'm not sure what the current distinction is.

**Comment by bloodmc** [comment]
ChangeBlockEvent.Pre was added to handle spreads, flows, etc..
