### ISSUE TITLE
Respawning to beds is broken.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#431]
Respawning to beds is currently broken on SpongeForge c49c920897ece2657a0f53f67c74609c5b4ee204 [c49c920]

Whenever you die and respawn it sometimes says your bed is obstructed, returns you to the worldspawn, or doesn't say anything, and returns you to the worldspawn.

**Comment by ryantheleach** [comment]
In addition, respawning to beds is currently broken on SpongeForge c49c920897ece2657a0f53f67c74609c5b4ee204 [c49c920]

Whenever you die and respawn it sometimes says your bed is obstructed, returns you to the worldspawn, or doesn't say anything, and returns you to the worldspawn.

It might be in conjunction with the above code, if .isBedSpawn() isn't being set correctly.

**Comment by ryantheleach** [comment]
Modifying the above code, to 

```
    @Listener
    public void onSpawn(RespawnPlayerEvent event){
        if(!event.isBedSpawn()){
            Location location = event.getFromTransform().getExtent().getSpawnLocation();
            location = location.add(.5,.5,.5);
            event.setToTransform(event.getFromTransform().setLocation(location));
            event.getTargetEntity().sendMessage(Text.of("EasySpawn!"));
        }
        event.getTargetEntity().sendMessage(Text.of("BedSpawn"));
    }
```

results in no messages being sent to the player.

**Comment by ryantheleach** [comment]
Ignore this for now, may have been user error.

**Comment by ryantheleach** [comment]
Also, is it intended that players joining the world for the first time, aka a Spawn not a Respawn not fire a Respawn event?

If so, could we get a parent interface event to Respawn Event, that covers both Respawn and FirstSpawn ?

**Comment by simon816** [comment]
Respawn behavior should follow vanilla. Does it falsely think the bed is missing/obstructed?
Note that it is not possible to force the respawn location in the API yet (https://github.com/SpongePowered/SpongeAPI/issues/955)

I don't think a parent for respawn is necessary, you can use `SpawnEntityEvent` to see when a player first spawns in the world (I don't think this should fire on respawn)

**Comment by ryantheleach** [comment]
I'm not looking for when the player entity spawns, but when it is "born" for the very first time. the SpawnEntityEvent would fire for every login, maybe under other modded circumstances as well.

I also tried listening for public void onFirstJoin(ClientConnectionEvent.Login event){
        Optional<JoinData> x = event.getTargetUser().get(JoinData.class);

But it would seem that the join data is absent even for players who have played before. Not sure if unimplemented or not easily fetchable at ClientConnectionEvent.Login

**Comment by Aaron1011** [comment]
@ryantheleach: I'm able to reproduce this. Trying to respawn after sleeping in a bed, I'm told that it's missing or obstructed.

**Comment by Minecrell** [comment]
SpongeVanilla has the same issue.

**Comment by simon816** [comment]
Just about to do that
