### ISSUE TITLE
Add ItemStack / ItemSlot to causes for interact events.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#439]
Doing this is helpful now, and if done in the cause will be compatible with 1.9 as no matter which slot is being activated, you have the correct itemstack/slot.

**Comment by Aaron1011** [comment]
I'm pretty sure that we ruled this out, due to the fact that an interact could be triggered by something for which no item is available (e.g. a mod block).

@Zidane: Thoughts?

**Comment by ryantheleach** [comment]
If there is no item available, then it wouldn't appear in the cause, and people listening for interacts needing items wouldn't catch the event?

Or are you saying that modded blocks could fire interact events, with item stacks, but we have no way of supplying the itemstack to the event?

**Comment by bloodmc** [comment]
You can now use InteractItemEvent.
