### ISSUE TITLE
Provide API for creating virtual inventory screens

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#443]
Servers often use a virtual inventory screen to display a collection of items to players - some use this as a shop, mailboxes, etc. I've looked through the API and do not see any relevant methods.

For reference, Bukkit used `Bukkit.createInventory()`, allowing a custom title and a configurable slot count. After added necessary items it would be sent to `player.openInventory()`.

**Comment by simon816** [comment]
There is [`CustomInventory`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/inventory/custom/CustomInventory.java)
and [`openInventory(Inventory)`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/entity/living/Humanoid.java#L66)
If this is an API issue it should be opened on SpongeAPI
