### ISSUE TITLE
Entity events fired while an entity is constructing can cause problems.

### ISSUE THREAD

**Issue by simon816** [SpongePowered/SpongeCommon#444]
If an event related to an entity (`TargetEntityEvent`) is fired while the entity is still constructing, there can be problems.
For example, `AITaskEvent.Add` gets fired when `this.tasks.addTask` is called in the constructor of many living entities (e.g. EntityPig). The problem is that some fields may not have initialized at this point and so some methods throw NPEs.

In `SpongeEventFactory#createAITaskEventAdd` there is the line:
```java
Preconditions.checkArgument(((goal.getOwner()) == targetEntity), String.format("The target entity \'%s\' is not the owner of the goal \'%s\'!", goal, targetEntity));
```
which will call `targetEntity.toString()`, this calls `getName()`, but lets say there is a modded entity which stores its name in a field. Because the field has not initialized (it is set after `super(..)`) then the name will NPE.

This currently is an issue with the mod, Minecraft Comes Alive with it's `EntityHuman`, attempting to construct this entity causes the following exception: http://pastebin.com/JgpvHpWs

I don't know what's best to fix this, either we don't fire the event when the entity is constructing, we change `String.format` to use the template ability of `checkArgument` (not a real fix, just an avoidance), or we ask MCA to ensure it handles null when constructing

**Comment by Deamon5550** [comment]
We could delay the events to fire after the entity has finished constructing. In the specific case of the AITaskEvent.Add it could lead to less noise if a modded entity is removing the tasks in its ctor, if we wait until the entity is finished constructing and then throw add events for any tasks that it has a plugin would never see those tasks existing on that entity.

**Comment by gabizou** [comment]
We could have some sort of handling similar to entity/block tracking where the entities are targeted and events thrown afterwards.

**Comment by simon816** [comment]
OK it has been decided (thanks @bloodmc @Deamon5550  and @Zidane) that the `AITaskEvent.Add` will be delayed in it's firing when `addTask` is called in the constructor. The events will be stored, then fired just before the entity is spawned.
