### ISSUE TITLE
Asynchronous handling of chat events

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#446]
On Sponge the chat events are currently always running in the main thread which is the standard Vanilla behaviour. However, compared to other parts of the server, moving the chat events out of the main thread is actually quite easy (and safe) to implement, because it does normally not depend on anything world related or similar things. Moving chat processing out of the main server thread has several advantages:

- When the main server thread is running slow, e.g. during a WorldEdit operation or a big TNT explosion chat will be still usable independently because it runs separately from the main server thread.
- Expensive chat processing (e.g. a complex swearing filter or whatever) implemented by plugins can be moved out of the main thread which is already busy enough normally, especially on servers with multiple worlds and a lot of players.

However, this also causes a difficulty for plugin authors:

- Most of SpongeAPI is not thread-safe, so they have to be made aware of the fact that they need to queue things in the main thread if they want to change world details for example. If we implement this we should make sure there are ways for plugin authors to queue things in the main thread easily, or possibly even check if the event is running asynchronously if this behaviour is different depending on the implementation. Additionally, the docs should probably clearly state how to deal with asynchronous processing so plugin authors actually know how to properly deal with it.

I'm basically looking for feedback on this issue whether this is something Sponge should implement, and it what way we should implement it so the event listeners are still safe and don't call methods on SpongeAPI which are not thread-safe.

**Comment by gabizou** [comment]
If I remember correctly, there is a very good reason why most chat plugins for Bukkit ended up not using any sort of `AsyncChatEvent` of sorts: permission lookups. Because it's completely unknowing of whether the underlying permission implementation is performing the permission checks based on location, there's a bit of things that otherwise would be dependent on remaining in sync with the main thread.

**Comment by ryantheleach** [comment]
The biggest issue when threading chat, is dealing with plugins that place variables that can be filled in into the chat. Common variables are Worlds, ranks, groups, factions, health, country, and a whole slew more.

The problem then goes to thread safe access to the variables. One choice is to cache them, but then you need cache invalidation which could get hairy if an event isn't fired for whichever variable you happen to have, and it also means that events need to be listened to for each of those variables.

You could update them every tick, and use the last known good values.

The other thing is permissions.

**Comment by kashike** [comment]
If anything, a sync and async event would be good - not just async.

**Comment by ryantheleach** [comment]
Wouldn't having a sync event just mean everything blocks waiting for the sync event to be fired anyway?

**Comment by Minecrell** [comment]
I'm going to close this for now. If at all, this should be handled together with a general discussion on the handling of certain asynchronous events we should target for a later release.
