### ISSUE TITLE
PaginationService.setPaginationCalculator doesn't appear to work

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#452]
I'm trying to change the "lines per page" number for paginated results sent to a player via the `PaginationServer.Builder`. The only related method I can find is `getFixedLinesCalculator` which returns a new calculator. I assume this calculator must be provided back to the service but either I'm wrong or it's not working:

    service.get().setPaginationCalculator(CommandSource.class, 
        service.get().getFixedLinesCalculator(5));

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeAPI/commit/00a305d92cf5d82ef12e6a375072a32c2cf82ae7.
