### ISSUE TITLE
Entity vehicle/passenger cannot be properly set until one tick after spawn

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeCommon#454]
Attempting to set an entity's vehicle/passenger in the same tick that it is spawned does not update the client properly. If the player's vehicle is set to a `Pig`, for example, the player will still be on the ground (client-side). Attempting to move away from the entity will cause the player to be teleported back by the server.

**Comment by bloodmc** [comment]
Is this SpongeForge or SpongeVanilla? or both?

**Comment by Aaron1011** [comment]
@bloodmc: Both, I believe.

**Comment by Zidane** [comment]
@bloodmc or @Aaron1011 

Status update.

**Comment by Aaron1011** [comment]
This was fixed at some point, and is no longer an issue.
