### ISSUE TITLE
IndexOutOfboundsException caught in Hotbar.getSlot(SlotIndex) and null returned

### ISSUE THREAD

**Issue by catageek** [SpongePowered/SpongeCommon#457]
The following code:
```
Hotbar hotbar = player.getInventory().query(Hotbar.class);
return hotbar.getSlot(new SlotIndex(0)).orElse(null);
```
is returning null because OrderedInventoryAdapter.getSlotLens() is catching an IndexOutOfBoundsException.

Apparently the list OrderedInventoryLensImpl.slotCache is empty, so at OrderedInventoryLensImpl:87 the exception is triggered.

**Comment by modwizcode** [comment]
I'll try to fix this with issue #409.

**Comment by modwizcode** [comment]
To clarify I don't think these are duplicate issues but the fix might be in the same code paths.

**Comment by Mumfrey** [comment]
@modwizcode, do not touch the adapter code please, a few things are being changed and rebasing drives me nuts.

**Comment by modwizcode** [comment]
@Mumfrey If the fix requires that what do you want me to do?

**Comment by Mumfrey** [comment]
It does, leave it with me.

**Comment by modwizcode** [comment]
Ok no problem.

**Comment by Zidane** [comment]
@Mumfrey 

Status update on this issue. Where are we at with changes to the adapter code?
