### ISSUE TITLE
No Sign Text Returned

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#458]
Given the following code where the variable ````BlockState sign```` is the block state for a wall sign block containing some text:

````java
            BlockState sign = ...;
            Optional<List<Text>> optSignText = sign.get(Keys.SIGN_LINES);
            if (!optSignText.isPresent()) {
                MessageChannel.TO_ALL.send(Text.of("No text found: ", sign.getType()));
                return;
            }
            MessageChannel.TO_ALL.send(Text.of("Sign text found!"));
````

The output is "No text found: Sign" where "Sign text found!" is expected.

**Comment by gabizou** [comment]
You can't get sign text from a `BlockState`, a `BlockSnapshot` maybe, but definitely not a `BlockState`.
