### ISSUE TITLE
Sign Text data cannot be offered to a BlockSnapshot 

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#461]
Sign Text data applied to a BlockSnapshot using the `with` method has no effect on the BlockSnapshot.

**Comment by Zidane** [comment]
@gabizou 

Status update.

**Comment by Aaron1011** [comment]
This is intentional, as the data is stored with the `Sign` TileEntity. Offering data to a `BlockSnapshot` goes through the blockstate, which doesn't support `SignData`.

**Comment by simon816** [comment]
A blocksnapshot stores TileEntity data too though. Shouldn't it fall back to the tileentity if the data is not accepted by the blockstate? (or other way around)

**Comment by Aaron1011** [comment]
@simon816: You're right - I'll be implementing that.

**Comment by gabizou** [comment]
This can be resolved once schematics necessary objects are added to the API, namely `TileEntityArchetype` and the relevant implemented processors dealing with raw data.

**Comment by ryantheleach** [comment]
This still trips people up, and schematics have been added. So it's probably time to attempt a fix for this.

**Comment by gabizou** [comment]
Should be able to. Adding to my todo list.

**Comment by gabizou** [comment]
Gonna actually just close this as it can be overall joined with https://github.com/SpongePowered/SpongeCommon/issues/950
