### ISSUE TITLE
Moving vehicles eject players

### ISSUE THREAD

**Issue by catageek** [SpongePowered/SpongeCommon#468]
Since 9366673 It is impossible to ride a cart in movement.

Players can still ride carts when they do not move, but are ejected when the cart starts to move.

**Comment by modwizcode** [comment]
@gabizou you working on this already? If not I'll take a look at it tonight.

**Comment by modwizcode** [comment]
@SpongePowered/developers can someone edit the issue title to just be "Moving vehicles eject players"?
