### ISSUE TITLE
Block Change causes occasionally reference an unrelated source

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#469]
I have some minigame code, which occasionally changes blocks using setBlockType, so as to, for instance, open a door. I added some block protection code to keep a player from breaking the door.

Upon debugging the block protection code, I discovered that Causes identical to if a player were breaking the block are being assigned to the changes performed by setBlockType in the minigame logic. 

These causes seemingly have nothing to do with the player they're claiming is involved. 

After some time, in most cases, the cause will not be assigned, and the edit will be performed -- the door will open/shut.

**Comment by ryantheleach** [comment]
Is it changing the blocks on the interact event? If so as a work around you can schedule the changes instead until you can setBlock with your own custom cause.

**Comment by DarkArc** [comment]
It's running on a scheduled task, the mini game has its own ticks more or less, where it checks some things, and performs updates.
		
        
		
		 ---- On Sun, 31 Jan 2016 19:19:44 -0800  notifications@github.com  wrote ----Is it changing the blocks on the interact event? If so as a work around you can schedule the changes instead until you can setBlock with your own custom cause.

**Comment by DarkArc** [comment]
After changing the minigame to use the new setBlock with a cause of the setting plugin provided, the Cause was instead the plugin that placed it, not the player who was breaking the block. This leads me to believe that occasionally the block's creator is used in place of the player or entity actually changing the block.
