### ISSUE TITLE
Ban Reasons do not support colored Text

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeCommon#470]
As title implies, the ban service doesn't support colored text correctly.

This is the [result](https://gyazo.com/a5c004ecb53397995e51587e1e514322), of using this [command](http://pastebin.com/hW0gwrLR) with the input: `&bIs color enabled? &4&lNo.` for the reason.

The same input when used to kick the player if online is shown in color, but when the player tries to reconnect, and the ban message is shown, the reason is clearly not in color.

**Comment by Zidane** [comment]
@Aaron1011 

Status update.
