### ISSUE TITLE
Restoring an EntitySnapshot should move entity to a safe location if needed

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#472]
It's possible for the location of an EntitySnapshot to no longer be safe upon restore. In that case, the entity should be moved to a safe location.

**Comment by Zidane** [comment]
I think I disagree with this...solely on the premise that this violates the law of the snapshot. If I restore a snapshot, I want the object being restored to be exactly as it were.

Maybe a better fix for your usecase is a method in the API to ask "Is this location safe for this entity?". Granted this would require AABB to be exposed finally.

Tagging @DDoS .

**Comment by viveleroi** [comment]
I filed this per a request from @bloodmc, he might have some input too.

**Comment by Zidane** [comment]
Closing this as it is on the plugin to move the Entity to a safe spot (if they even care...)
