### ISSUE TITLE
method to get baseGen surface y value

### ISSUE THREAD

**Issue by El-minadero** [SpongePowered/SpongeCommon#479]
Someone suggested in IRC that I post this here. I don't know if this is the appropriate place for discussing things like this, and I do realize that most of sponge is already fleshed out. However, if it is possible, could there be a field in chunk that gets the highest y value non-air, non-tree, non-liquid block for a given pair of x,z coordinates? I can't seem to find a fast/easy way to implement this on my own and I know bukkit had a similar function.

**Comment by simon816** [comment]
You could probably just create a [`BlockRay`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/util/blockray/BlockRay.java) with your own filter

**Comment by ryantheleach** [comment]
Do you want the current highest block? or the one that originally generated?

**Comment by El-minadero** [comment]
I could see utilities for both methods, but mainly for the original baseGenerator surface. It would have added functionality for me if the get method didn't have to query chunk objects, but could instead sample the noiseMap the surface is made from (so I could use info in places the world has not yet generated)

**Comment by Deamon5550** [comment]
Fetching from the noise map would be far more expensive than just doing a trace.

**Comment by El-minadero** [comment]
Is this because the noise map in question is after the caves etc; have been applied? is there no way to sample just the base terrain map?

**Comment by Zidane** [comment]
@Deamon5550 

Is this feasible or?

**Comment by Zidane** [comment]
Closing this until @Deamon5550 says otherwise.
