### ISSUE TITLE
PassengerData not working on minecarts

### ISSUE THREAD

**Issue by spongieDev** [SpongePowered/SpongeCommon#48]
I get a "java.lang.IllegalStateException: Optional.get() cannot be called on an absent value" exception when trying to put a block inside a minecart. Code: http://pastebin.com/CsYqXzQq . Thanks for helping, as I cannot keep working with this error.

**Comment by ryantheleach** [comment]
According to this, this effect is done using minecartfurnaces http://www.reddit.com/r/Minecraft/comments/1m3fm8/diagonal_blocks_are_much_easier_now_with_summon/

Is this the effect you want, or are you attempting to get an actual fallingblock entity in a minecraft, which will probably have a limited lifespan.

**Comment by spongieDev** [comment]
I am trying to get the same result as if I had executed this command: /summon MinecartRideable ~ ~1 ~ {CustomDisplayTile:1,DisplayTile:dirt}

**Comment by ZephireNZ** [comment]
What you're trying to do and what you're actually doing are different. PassengerData is made for entities such as horses, pigs etc that have another entity riding on top of them.

The CustomDisplayTile tag is specific to minecarts, they render a block inside the card (or above/below, in some cases) - it is not a seperate entity.

@gabizou Perhaps we need another data type?

**Comment by ZephireNZ** [comment]
PassengerData seems to specific to entities for it to be used for minecarts.

**Comment by gabizou** [comment]
> What you're trying to do and what you're actually doing are different.

You are right about that, he's forgetting to spawn the mincer, then spawning in the `FallingBlock` entity.



> PassengerData is made for entities such as horses, pigs etc that have another entity riding on top of them.

There is no limitation on `PassengerData` about whether the passenger can be a `Living` or anything like that. It's closer to the `SpongePassengerProcessor` returning absent when it shouldn't.



> The CustomDisplayTile tag is specific to minecarts, they render a block inside the card (or above/below, in some cases) - it is not a seperate entity.

Not sure what you mean here, picture?

> PassengerData seems to specific to entities for it to be used for minecarts.

No it isn't.

**Comment by ZephireNZ** [comment]
With minecarts, you have a few optional fields to show a custom block inside the minecart:

- *CustomDisplayTile* - Whether or not to show a custom tile.
- *DisplayTile* - Block ID of the tile to show.
- *DisplayData* - Integer durability for the block
- *DisplayOffset* - draw the tile above or below the usual position in the cart.

This kind of metadata is completely different to PassengerData. PassengerData two seperate entities, with one mounting the other. The data shown here allows a cart (or whatever implements the data) to display a tile similar to chest, furnace and command minecarts - they are not two distinct entities.

**Comment by ryantheleach** [comment]
Can you ride a minecart with a custom display tile? That will be the real test on whether they are different or not from an abstracted view.

**Comment by gabizou** [comment]
So, I take it this should be an API addition, @ZephireNZ since you know a bit more than I do, can you properly make an Issue or PR for it? Thanks!

**Comment by ZephireNZ** [comment]
This has been done in SpongePowered/SpongeAPI#904
