### ISSUE TITLE
Minecarts "float" down

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#480]
I don't know how else to explain this, but somewhere, somehow, we're managing to make it where `Minecart` entities "float" to the ground, as if they're floating like they're chickens. I've tested that it's not the `DisplaceEntity.Move` event implementation, nor is it the `SpongeHooks.checkEntitySpeed` stuff, nor is it any of the mixins directly for `Minecart`s. Really mind boggling. @Zidane was suggesting it might have to do with the velocity fix @simon816 pushed a while ago, but I can't find where that went.

**Comment by simon816** [comment]
My velocity fix was replaced by https://github.com/SpongePowered/SpongeCommon/pull/293

**Comment by simon816** [comment]
OK so I have tested this and found it has something to do with SpongeForge's [`MixinEntityMinecrart`](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/entity/vehicle/MixinEntityMinecart.java). If I remove that mixin then minecarts fall as expected.

**Comment by simon816** [comment]
The issue is that the inject had never worked, ever. [`implementCustomAirborneDeceleration`](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/entity/vehicle/MixinEntityMinecart.java#L69-L79) was never being injected and it was only when the inject was fixed did this actually take effect.
I traced the inject back to @caseif's original PR, https://github.com/SpongePowered/SpongeForge/commit/5ff1e43078478fc7bdd86d449044b655da540626#diff-4832b9fe73d0b8731c99741d931263dfR67 so this method had never been used, I'd say it's safe to remove, unless @caseif would like to fix it.

**Comment by Mumfrey** [comment]
Is the field [airborneMod](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/entity/vehicle/MixinEntityMinecart.java#L46) ever actually assigned? Wouldn't this cause an NPE if [that code](https://github.com/SpongePowered/SpongeForge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/entity/vehicle/MixinEntityMinecart.java#L75-L77) is actually run?

**Comment by caseif** [comment]
@simon816 Honestly I don't really even remember that PR very well, but I'll look at the method tonight to see if I can fix it.

**Comment by gabizou** [comment]
> The issue is that the inject had never worked, ever. implementCustomAirborneDeceleration was never being injected and it was only when the inject was fixed did this actually take effect.
> I traced the inject back to @caseif's original PR, SpongePowered/SpongeForge@5ff1e43#diff-4832b9fe73d0b8731c99741d931263dfR67 so this method had never been used, I'd say it's safe to remove, unless @caseif would like to fix it.

I can guarantee you that

**Comment by Mumfrey** [comment]
Honestly, why is that multiplier 0.5 though?

**Comment by gabizou** [comment]
Because that's what vanilla does.

**Comment by gabizou** [comment]
Also, I just noticed that there's the mixin in Spongeforge, which now I'll re-test and come back with a fix.

**Comment by Mumfrey** [comment]
> Because that's what vanilla does.

Yes but this means that vanilla is doing the 0.5, and then the mixin is applying the 0.5 **again**!

**Comment by Mumfrey** [comment]
Also, vanilla only applies the 0.5 multiplier as the *derailed* modifier, in the air it just applies drag, so surely the base value for that should be `defaultDragAir` (0.94999998807907104D) and not 0.5.

**Comment by gabizou** [comment]
Fixed!
