### ISSUE TITLE
Create mapping of UUID -> Entity for loaded entities

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#482]
Seriously, just iterating over the existing entities in the loaded entity list for the `World` is just poor practice. If anything (since we control the spawned entities anyways), we should maintain the mapping of UUID to Entity instances at least, or if not, we can make a `WeakHashMap` otherwise.

**Comment by kashike** [comment]
This sounds like it should be in the API as well.

`net.minecraft.world.WorldServer#getEntityFromUuid` not an option?

**Comment by gabizou** [comment]
Ah yes, `WorldServer` is probably the better option, I was just strolling across it in `MixinWorld`.

**Comment by gabizou** [comment]
I was looking at the code incorrectly. It is delegating if the world is and instance if `WorldServer`.
