### ISSUE TITLE
NativeStackException when setting item in empty slot

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#488]
```java
player.getInventory().slots().iterator().next().set(ItemStack.of(ItemTypes.SPONGE, 1));
```
Stacktrace:
http://pastie.org/pastes/10712762/text?key=ydvdgdsim3v2ifg1yhztw

https://github.com/SpongePowered/SpongeCommon/blob/27705f6ff539bf00288ccbd3995ec2adfbe90b48/src/main/java/org/spongepowered/common/item/inventory/util/ItemStackUtil.java#L54

**Comment by Rain336** [comment]
The actual error is `SlotAdapter#set(ItemStack)` isn't checking for null as "old" ItemStack.

**Comment by Rain336** [comment]
Btw there is also SpongePowered/SpongeVanilla#220
