### ISSUE TITLE
Tab completion issues

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#49]
Vanilla (and SpongeAPI) commands to not tab-completing correctly.

`/scoreboard <TAB>`:
> `<nothing returned>`

expected:
> `<all subcommands for /scoreboard>`

_______________________________________

`/tpworld Kashike <TAB>`: (expected)
> `endover, nether, world, overend, overnether, Farm, endnether, DIM1, end, DIM-1, netherend, netherover`

_______________________________________

`/tpworld Kashike n<TAB>`:
> `/tpworld Kashike nether`

expected:
> `nether, netherend, netherover`

**Comment by zml2008** [comment]
The issues in Sponge commands are related to SpongePowered/SpongeAPI#604 I think. (Vanilla commands are a separate thing)

**Comment by kashike** [comment]
This is still an issue @zml2008.

**Comment by simon816** [comment]
@zml2008 Update?

**Comment by ryantheleach** [comment]
/particle heart ~ ~ ~ 1 2 3 4 5<tab> results in no tab completion on vanilla minecraft.
/particle heart ~ ~ ~ 1 2 3 4 5 <tab> results in the tab completion of force/normal on vanilla minecraft.

/particle heart ~ ~ ~ 1 2 3 4 5 <tab> incorrectly results in no tab completion on SpongeForge. 
and /particle heart ~ ~ ~ 1 2 3 4 5<tab> correctly results in no tab completion on SpongeForge

/particle heart ~ ~ ~ 1 2 3 4 <tab> results in the incorrect tab completion of force/normal on SpongeForge.

**Comment by JBYoshi** [comment]
@ryantheleach Which of those example commands have spaces at the end, and which don't?

**Comment by ryantheleach** [comment]
Github stripped my \< \>

**Comment by Aaron1011** [comment]
This has been fixed in the latest `master`.
