### ISSUE TITLE
HealEntityEvent not firing.

### ISSUE THREAD

**Issue by KillfalconGames** [SpongePowered/SpongeCommon#490]
I was trying to cancel the healing effects of food. When I tested my listener I realized that the HealEntityEvent never fired. I've set a breakpoint at the first line of the method and tested to heal myself with food and healing potions, both of which did not fire the event. 

Heres the code I'm using:
http://pastebin.com/uWGyuwax

**Comment by gabizou** [comment]
As exemplified by https://github.com/SpongePowered/SpongeCommon/issues/41, the event isn't implemented. Closing as this is redundant to the event implementation checklist.
