### ISSUE TITLE
TextXML - Newlines are lost

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeCommon#492]
onHover text in Minecraft can have new lines. JSON:

``` java
Text t = TextSerializers.JSON.deserialize("{text:\"Hover.\",hoverEvent:{action:show_text,value:\"Hello\\nthere.\"}}");
```

Screenshot:
![scr1](https://dl.dropboxusercontent.com/u/7410519/ScreenS/ser_JSON.png)

But TextXML isn't supporting this in any way.
It's easy to test with serializing and deserializing Text generated from JSON with TextXML:

``` java
Text t2 = TextSerializers.TEXT_XML.deserialize(TextSerializers.TEXT_XML.serialize(t))
```

Resulting TextXML:

``` xml
<span onHover="show_text('&lt;span&gt;Hello
there.&lt;/span&gt;')">Hover.</span>
```

Screenshot:
![scr2](https://dl.dropboxusercontent.com/u/7410519/ScreenS/ser_textXML.png)

**SpongeForge version**:  b66f2dd-SNAPSHOT

**Comment by ryantheleach** [comment]
It also annoys me that users wanting to use hovers now have to encode the <> characters as &gt;

maybe we could fix both issues by refactoring the format, so hover is no longer an attribute of span, but a child tag of some sort?

<span><hover type="show_text">Hello<br/>There</hover>Hover</span>

**Comment by TomyLobo** [comment]
Well, child tags right now mean content, while attributes hold properties.
hover is clearly not content, but also not really a property, but a pseudo event handler thingy...

Other people?

**Comment by TomyLobo** [comment]
On the original issue:
In theory, the deserialization should preserve whitespace.
In practice there has been a bug with whitespace in TextXML before which @Doridian fixed before I handed it over to @zml2008 .
But we never tested multi-line stuff...
Also, I think @zml2008 reimplemented some parts from scratch, so this particular fix might not be in there anymore.

**Comment by ryantheleach** [comment]
I think the fact that it has nested xml fragments that are getting coded show that it definitely should not be an attribute. It's just 100% unfriendly for people to input into configs.

**Comment by gabizou** [comment]
@windy1 @Minecrell can either of you look at this?
