### ISSUE TITLE
DisplaceEntityEvent wont fire after login

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#493]
To reproduce join the game
make sure to not move the camera.
Teleport to another world by using chat.
...
DisplaceEntityEvent did not fire.

Testplugin:
http://pastebin.com/7Ebh8cHY

**Comment by gabizou** [comment]
Because `DisplaceEntityEvent.Teleport` is not implemented, as reported in #41. `Move` events are implemented fully though.
