### ISSUE TITLE
FlyingAbilityData No Longer Working

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeCommon#494]
FlyingAbilityDataProcessor doesn't appear to be changed, but it no longer works for players in survival (verified on SpongeForge 1141)

[Test Code](https://github.com/hsyyid/EssentialCmds/blob/master/src/main/java/io/github/hsyyid/essentialcmds/cmdexecutors/FlyExecutor.java)

**Comment by Aaron1011** [comment]
@hsyyid: I'm unable to reproduce this.  Can you retry on the latest SpongeForge, and post your code?

**Comment by hsyyid** [comment]
@Aaron1011 Sure, wil retry now on SF 1144. I'm using EssentialCmds `/fly` command to test.
