### ISSUE TITLE
handleDisconnection() called twice

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#508]
I can't narrow the cause of this down, nor can I reproduce it with any exact set of steps, but it happens consistently enough that I know it's not a fluke.

During random player disconnects, the console begins spamming this warning:

`[Server thread/WARN]: handleDisconnection() called twice`

There appears to be no way to stop it outside of a full reboot. It's happened on a local dev server (without mods/plugins) for me, it's happened randomly on a public servers with a wide range of players.

**Comment by kashike** [comment]
The actual message is intentional by Mojang, however it shouldn't be spamming it - more than likely a bug with Forge and/or Sponge.

**Comment by viveleroi** [comment]
I'm seeing about 15-20 per second.

**Comment by viveleroi** [comment]
After hunting down the cause, this turned out to be an EssentialCmds issue.
