### ISSUE TITLE
Dupe glitch from invalidated block change transaction

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#510]
Invalidating a block transaction fails to work properly when that block has broken due another block change. For example, breaking a grass block with a door above it will both drop the door item, and leave a door at that location. The same happens with pressure plates so I'm betting that it happens with all blocks that act this way.

Depending on the chain of events I don't know how easy this will be to fix. For my needs, I believe I can also invalidate the bottom block change too.

@bloodmc

**Comment by windy1** [comment]
Just to be clear. When you say "invalidating a block transaction" you are referring to canceling a `ChangeBlockEvent`? Could you supply some example code of when this is happening for you?

**Comment by viveleroi** [comment]
By calling `transaction.setValid(false)` while iterating transactions in a `ChangeBlockEvent`.

**Comment by bloodmc** [comment]
This is fixed in SF 1.10.2+.
