### ISSUE TITLE
Unable to place blocks in specific locations

### ISSUE THREAD

**Issue by Ollie2000** [SpongePowered/SpongeCommon#515]
Myself and a few of my friends have run into a somewhat serious bug, where you cannot place a block in these specific locations. We were trying to figure out why and none of us could... until now.

What was happening was there some some sort of invisible, un-killable, undetectable entitie stopping anything that required the space to be free of entities (solid blocks) from being placed. Items that were not solid such as grass, beds, itemframes, cobwebs, etc were placeable because they didn't check to see if there was an entitie there.

Onto the bug and why it's happening. 1.8 offers a new mob (combination), the chicken jockey, or the zombie jockey, depending on what you call it. Killing the chicken renders the baby zombie ontop to become, as mentioned above, unkillable, undetectable, and unmovable. I don't belive this mob to be the only one, I believe spider jockeys also cause this issue, but I have not tested it. but what I have tested was using the command "/summon Zombie ~0 ~1 ~0 {IsBaby:1,Riding:{id:Chicken,IsChickenJockey:1}}", though all of the bugs I've experience that weren't tests I believe were naturally spawned.    
Just a side note: chicken jockey's baby zombies are in fact, invisible, spawned naturally or by command.
Edit: we're on SpongeForge 1155

**Comment by Aaron1011** [comment]
Is this still reproduceable with the latest SpongeForge?

**Comment by Ollie2000** [comment]
From what I see no, it's not an issue anymore. Though before this is closed I'd like to see if updating from 1155 to the latest 1167 (forge 1762) fixes previous cases of this bug.

**Comment by Aaron1011** [comment]
Ok, sounds good.

**Comment by Ollie2000** [comment]
We updated to 1167 and the problem is still persisting.  (sorry it's taking a while, I don't own the server it's on) I'm going to assume it's the same for 1173.

**Comment by Aaron1011** [comment]
@Ollie2000: I've tried killing the chicken being ridden by the baby zombie, but the zombie remained normal. I was still able to place in its previous hedspace, and able to place where it was after killing it.

**Comment by Ollie2000** [comment]
The cause of the problem no longer exists, but the issue is still apparent after you update. I can show you on the server I play on if you wish. That cause happened in 1155, when we updated to 1167 the spots that were effected by the cause were still there, but the cause is no longer replicatable
