### ISSUE TITLE
Discussion: Procedures for managing Overwrite methods in mixins

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#52]
(Moved into common)

Calling @SpongePowered/developers for comments.

It is my belief that we need to put a procedure (or at least some reasonably strict guidelines) in place for managing `@Overwrite` methods in mixins. This thought is largely triggered by [these two behemoths](https://github.com/SpongePowered/Sponge/blob/master/src/main/java/org/spongepowered/mod/mixin/core/server/MixinServerConfigurationManager.java#L126-L362) which just present a maintenance nightmare as they stand.

We currently have no standard for marking `@Overwrite` methods, meaning that determining the purpose of an `@Overwrite` and the specific code which has changed is an excercise left up to the observer. I think this needs to change before we create too much unmaintainable code.

Suggestions for things we should encode in an `@Overwrite` procedure:
- **All** `@Overwrite` methods should be decorated with a (javadoc?) comment which at minimum contains who added the `@Overwrite` method and why, for example:
  
  ``` java
  /**
  * @auhor Mumfrey
  * Adds custom logic for summoning Cthulu
  */
  @Overwrite
  public void doSomething() {
  // etc
  ```
  
  This will make it possible to quickly determine whether an `@Overwrite` is needed any more, whether it can be replaced with an injection when someone has more time, etc. etc. and in extreme cases, who to go and ask when the inevitable "what the hell does this code even do" comes up :)
- Where an `@Overwrite` method is being employed to only change certain blocks of code within a method (eg. it began as a copy/paste of the target method and was subsequently modified). The changed blocks should be marked with some standard comment _a la_ `// CraftBukkit start` and `// CraftBukkit end` of old. Where new code **replaces** old code, the old code should be left behind and commented out:
  
  ``` java
  // Sponge start
  // this.baz = false; // old code
  this.baz = this.getFoo().isBar();
  // Sponge end
  ```
  
  The old code thing is a suggestion, but I think we should do something along those lines mainly so that when we port changes forward it's possible to locate similar code in the new class?
- Where an `@Overwrite` method entirely differs from its target counterpart (eg. when replacing a hard-coded accessor with some custom logic) the `// Sponge start` and `//Sponge end` could be omitted and the method description can cover it.
- Things we might also want to insist upon/recommend in the method comment might be:
  - Usage of the `@since` tag to designate the forge/mc version at time of adding/last modification?
  - Usage of the `@category` tag with some pre-defined categories indicating purposes of the `@Overwrite`
  - Usage of something like `TODO: inject` if the person adding the `@Overwrite` isn't sure if (for example) an injector is actually a more suitable way of achieving the same goal but isn't experienced enough with injectors to actually write one.

Inviting discussion on what the procedure should be, I think the fact that we ought to put something in place is pretty obvious (for future sanity purposes), but how strict we want to be and what the guidelines themselves should actually be is something we need to decide. Whatever we decide it should go into the contribution guidelines and a review of current `@Overwrite`s undertaken to make them compliant.

As an example, we could make a javadoc comment a "must have" and everything else be optional, or we could go full strict-mode and send people to the firing squad if they don't comment their additions :)

Okay, `</ramble>`.

**Comment by Zidane** [comment]
Just to make clear, this was Mumfrey's original post so direct inquiries to him.

**Comment by Mumfrey** [comment]
I actually forgot about this, I started writing it up but got super frustrated with the crappy *not-quite-as-flexible-as-markdown* markup that the docs project uses. I will finish writing up when I get a minute.

**Comment by bloodmc** [comment]
This looks good to me.

**Comment by gabizou** [comment]
I believe we've taken a deviation from this original thought where the old code isn't directly copied as comments, but rather just eliminated if overwritten. There are approximately 90+ `@Overwrite`s in the current implementation, so re-evaluating all of them to work would not sufficiently suffice unless we spent the time now to re-analyze the original overwrites and re-document and update with all of the previous code that was excluded and re-added strictly as comments.

**Comment by gabizou** [comment]
@Zidane after dealing with a few overwrite rewrites the last couple of days, I feel that we need to heavily start enforcing the idea at least to either include (commented out) vanilla code and the javadoc for `@author` and `@reason`. Mixin is already complaining about all of the current overwrites for the missing javadocs.

**Comment by ryantheleach** [comment]
So this is now policy right, and can be closed?

**Comment by gabizou** [comment]
I just think there's no official guideline we can point to for implementation, but yes, at this point we do fooollow our unofficial guidelines about overwrites.
