### ISSUE TITLE
Implementation of Inventory API

### ISSUE THREAD

**Issue by 20zinnm** [SpongePowered/SpongeCommon#521]
## Implementation of Inventory API [![Bountysource](https://api.bountysource.com/badge/issue?issue_id=31041996)](https://www.bountysource.com/issues/31041996-implementation-of-inventory-api?utm_source=31041996&utm_medium=shield&utm_campaign=ISSUE_BADGE)

I wrote the Sponge port of BuycraftX, which centers around a GUI functionality. Little did I know, the Inventory API has not yet been implemented. Thus, I offer the following challenge:

> Whoever contributes the most to the implementation of inventories in SpongeVanilla and/or SpongeForge (likely both through SpongeCommon) will be entitled to a $10 bounty.

The bounty can be claimed [here](https://www.bountysource.com/issues/31041996-implementation-of-inventory-api) (https://www.bountysource.com/issues/31041996-implementation-of-inventory-api).

This is purely an added bonus, and because I think Sponge developers are so amazing I might up that in the future. I have already become a $30 Patreon donor (funded purely with money I make off of my plugin(s)) and this is an added incentive for something that will be implemented no matter what.

**Comment by windy1** [comment]
:moneybag: :moneybag: :moneybag:

**Comment by Mumfrey** [comment]
The next phase of inventory is blocked on some features of Mixin needed to support it properly for mods. Once Mixin 0.6 is completed the remaining inventory will follow shortly afterward.
