### ISSUE TITLE
Keys.HIDE_UNBREAKABLE hides enchantments

### ISSUE THREAD

**Issue by thekeenant** [SpongePowered/SpongeCommon#527]
It doesn't hide the unbreakable attribute, instead it hides enchantments.

**Comment by Aaron1011** [comment]
@thekeenant: I can't seem to reproduce this. Can I see the code you're using?

**Comment by thekeenant** [comment]
I lost the exact snippet that I used, but I think this was similar: 

https://github.com/thekeenant/sponge-gamer/blob/master/src/main/java/net/keenant/Gamer.java

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/5f6ef52212b46f7ced7b286764cbd9109567fdf1.
