### ISSUE TITLE
Cancelling DropItemEvent.Dispense removes item

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#528]
SF 1159 - When the `DropItemEvent.Dispense` event is cancelled, the dropped items disappear rather than return to the dropping inventory. Tested with players dropping an item and cancelling the event.

**Comment by games647** [comment]
I still got this issue using spongeforge-1.10.2-2073-5.0.0-BETA-1689 and forge-1.10.2-12.18.1.2073-universal
