### ISSUE TITLE
Provide true original text to MessageChannel::transformMessage

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#538]
The `MessageChannel::transformMessage` method receives an argument called `Text original`, but this Text object is the final "vanilla" formatted chat message, complete with `<playername>` formatting. The same is true for a `MessageChannelEvent`, the original/message methods include the player content.

Our custom chat plugin needs to remove this player content from the message (in favor of custom prefixes), but the only way to do this is to convert the message `toPlain` and replace the content, however this also removes any existing formatting like clickable URLs.

**Comment by kashike** [comment]
There isn't really a nice way to do this without adding **another** parameter to the `send` and `transformMessage` methods, however I suppose I can provide the original `String`.

**Comment by ST-DDT** [comment]
AFAICT there is already a sender parameter.

https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/text/channel/MessageChannel.java#L158

Or are you referring to the impl that does not make use of that param.

**Comment by kashike** [comment]
@ST-DDT `sender` is the literal sender (player, etc) of the message. See https://github.com/SpongePowered/SpongeAPI/pull/1104

**Comment by kashike** [comment]
Assuming you're talking about `MessageChannelEvent` for player chat, `MessageChannelEvent.Chat` has a `getRawMessage` method that contains what you want, you just need to set that as the message, the channel will use that afterwards.

**Comment by Zidane** [comment]
API 4 should have addressed this.
