### ISSUE TITLE
Configurate Fails to Save to Config, and Creates .tmp Files 

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeCommon#541]
**This issue was reported by several users of my Kits plugin.**

[Original Issue](https://github.com/hsyyid/Kits/issues/6)
[Console Log](http://pastebin.com/twEuWMPz)

Basically, when Configurate fails to save something to the config (it says there is an AccessDeniedException) it creates LOTS of `.tmp` files, resulting in server TPS to drop, sever RAM usage to go up, and many more issues.

**Comment by Minecrell** [comment]
Pretty sure you should report this @ https://github.com/zml2008/configurate

**Comment by hsyyid** [comment]
@Minecrell Okay! :)
