### ISSUE TITLE
World properties set via API are not retained through reboots

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#542]
I originally noticed this issue with EssentialCmds but am seeing the same result with a custom plugin.

    world.getProperties().setSpawnPosition(location);

World properties like difficulty, spawn position, etc work fine when set via the API - yet when the server is rebooted the values are lost and they revert to the originals. 

@Zidane and I spoke briefly about this in IRC.

**Comment by simon816** [comment]
I just tested setting the spawn point (overworld) and it persisted. I could see it in the NBT.
Does this still happen?

**Comment by viveleroi** [comment]
I've been working with @Zidane on this and I think the real issue is that spawn isn't used an exact position by Minecraft itself, it's apparently randomly around that position. For my needs, it needs to be a exact spot.

**Comment by simon816** [comment]
Ahh right, that'll be the spawn 'fuzz' most likely
https://github.com/SpongePowered/SpongeCommon/blob/65f897e9c5b427578de64cbcd577b9976a9ddb21/src/main/java/org/spongepowered/common/interfaces/world/IMixinWorldType.java#L39
Maybe we could expose that in the API?
