### ISSUE TITLE
Guardians are not spawning naturally

### ISSUE THREAD

**Issue by Minecrell** [SpongePowered/SpongeCommon#544]
Currently Guardians are not spawning naturally in ocean monuments, at least on SV (and likely also on SF, see https://forums.spongepowered.org/t/guardians-not-spawning-at-ocean-monument-after-migrating-to-spongevanilla/11143/3?u=minecrell). This can be reproduced by e.g. generating a world with the seed `-1211445164` which has a ocean monument near the spawn.

The issue seems to be caused by the world generation changes made by Sponge, the custom chunk provider does not implement [`getPossibleCreatures`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/world/gen/SpongeChunkProvider.java#L351-L357) in the same way as Vanilla:

```java
    public List<BiomeGenBase.SpawnListEntry> getPossibleCreatures(EnumCreatureType creatureType, BlockPos pos)
    {
        BiomeGenBase biomegenbase = this.worldObj.getBiomeGenForCoords(pos);

        if (this.mapFeaturesEnabled)
        {
            if (creatureType == EnumCreatureType.MONSTER && this.scatteredFeatureGenerator.func_175798_a(pos))
            {
                return this.scatteredFeatureGenerator.getScatteredFeatureSpawnList();
            }

            // This is where Guardians are coming from
            if (creatureType == EnumCreatureType.MONSTER && this.settings.useMonuments && this.oceanMonumentGenerator.func_175796_a(this.worldObj, pos))
            {
                return this.oceanMonumentGenerator.getScatteredFeatureSpawnList();
            }
        }

        return biomegenbase.getSpawnableList(creatureType);
    }
```

@Deamon5550

**Comment by Minecrell** [comment]
@Deamon5550 Any news on this issue?

**Comment by viveleroi** [comment]
I'm pretty sure this applies to other mobs. For quite some time my players have been complaining that wither skeletons, blazes, etc do not spawn either at all, or so rarely it's impossible to tell the difference. We've seen this on a server without any custom plugins too.
