### ISSUE TITLE
Exception while ticking a block

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeCommon#546]
I'm having an issue that is occurring around 10 - 15 minutes apart. When 5 players are on it spits out a crash report message in console and this is what I get.

SpongeForge: 1.8.9-1763-3.1.0-BETA-1170
Forge: 1.8.9-11.15.1.1763

Crash Report:
http://paste.ubuntu.com/15219203/

Any help?

**Comment by Aaron1011** [comment]
Can you try removing Pixelmon, and seeing if you still get this?

**Comment by Zidane** [comment]
Error with Pixelmon.
