### ISSUE TITLE
Vanished players pickup items, are targeted by entities

### ISSUE THREAD

**Issue by viveleroi** [SpongePowered/SpongeCommon#547]
Using spongeforge 1167.

**Comment by gabizou** [comment]
@viveleroi Is this still present in the latest SF/SV?

**Comment by viveleroi** [comment]
1167 is only three builds behind and I haven't seen any commits related to this.

**Comment by gabizou** [comment]
Just double checking as I don't want it to be a non-issue on master by it being somehow broken and then fixed in the commits between builds ;). I'll get to this shortly.

**Comment by gabizou** [comment]
@viveleroi I can't reproduce this locally, any noticeable changes server side?

**Comment by gabizou** [comment]
@viveleroi let me know if this is still an issue, otherwise I'm closing it.
