### ISSUE TITLE
The world may have leaked: seen X times!

### ISSUE THREAD

**Issue by thomas15v** [SpongePowered/SpongeCommon#556]
We encountered this message after we did this with a world.
1. unload
2. delete

MapLoader class we use: http://hastebin.com/enulamomub.java
Server logs: http://hastebin.com/sitimadufu
minecraft version: 1.8.9
SpongeAPI: 4.0.0-SNAPSHOT-05b3db
SpongeVanilla: 1.8.9-4.0.0-BETA-249.

However the server doesn't seem to be badly affected. We did a unload and delete for 10 times and let the server run for a night.

**Comment by Zidane** [comment]
This is a design issue with your plugin lol.

You have several Optional<World> refs that you don't nullify when unloading a world. In all actuality, this is a poor way to store a Word. Unless the object in question is temp, Worlds should ALWAYS be stored within WeakReference.
