### ISSUE TITLE
Changing CommandBlock successCount needs manual block update on comparator

### ISSUE THREAD

**Issue by jk-5** [SpongePowered/SpongeCommon#557]
Example code:

    CommandBlock.offer(Keys.SUCCESS_COUNT, 5);

After calling this, you need to update the comparator manually for the redstone level to be outputted.

**Comment by Rain336** [comment]
I would say that the `TileEntitySuccessCountValueProcessor` needs a `container.markDirty()` before the return.

**Comment by jk-5** [comment]
That would mark the TileEntity for saving. Just doing one of the 5 world.blockupdate methods should suffice
