### ISSUE TITLE
Speed up event snapshots

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#564]
Carried over from post-SoS9 conversation, there is talk of optimizing data snapshots that are passed to events.

Among the ideas discussed are:

- Lazy initialization/creation of snapshots
- Stop throwing events when no one is listening
- Using weak references and gc (probably not viable)
- caching snapshots so they don't need to be reconstructed over and over.

This is among the several major optimizations that need to be made.

**Comment by TheRaspPie** [comment]
If we aren't creating the events in the first place if nobody listens to them, we could avoid a lot of object creation. Although the implementation will probably be very tedious...

**Comment by Zidane** [comment]
We've made some improvements to this in both 1.8.9 and 1.9.4. If this becomes a bigger issue, we'll evaluate further in the future.
