### ISSUE TITLE
Punctuation in chat

### ISSUE THREAD

**Issue by Ollie2000** [SpongePowered/SpongeCommon#569]
So doing any type of command (for the server I play on we can use chat commands like `/s` `/g` `/l` etc for other channels for chatting) such as /s then using any of these punctuation mars - `'` `\` and `"` will give an error message and won't let you send the message; using both quotation marks will let you send the message but won't show them - http://i.imgur.com/Ou3Ug9T.png but with only one of them you get this error - http://i.imgur.com/jJkqb7J.png

I assume you already know this but it'd be nice if there was a work-around for chats and /msg, /r /whisper, etc.

**Comment by zml2008** [comment]
On March 9, 2016 9:34:40 AM PST, Oliver <notifications@github.com> wrote:
>So doing any type of command (for the server I play on we can use chat
>commands like `/s` `/g` `/l` etc for other channels for chatting) such
>as /s then using any of these punctuation mars - `'` `\` and `"` will
>give an error message and won't let you send the message; using both
>quotation marks will let you send the message but won't show them -
>http://i.imgur.com/Ou3Ug9T.png but with only one of them you get this
>error - http://i.imgur.com/jJkqb7J.png
>
>I assume you already know this but it'd be nice if there was a
>work-around for chats and /msg, /r /whisper, etc.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/SpongePowered/SpongeCommon/issues/569

This is intentional. Use backslash escapes like basically every shell ever. There might also be a raw joined string, which can be combined with lenient parsing (iirc can be set in CommandSpec) to work without having to use escapes.

**Comment by viveleroi** [comment]
I think the crux of the issue is that in certain situations, like chat, it's not user-friendly. Players are used to vanilla chat allowing these characters without special escaping (and many need to be educated as to what escaping means) so in certain contexts we need a way to treat them normally.

**Comment by Minecrell** [comment]
The [`RemainingJoinedStringsCommandElement`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/command/args/GenericArguments.java#L823-L864) seems to support a `raw` option, although from what I can tell there is no way to set it currently.

**Comment by kashike** [comment]
Is this still an issue?

**Comment by ImMorpheus** [comment]
I'm not able to reproduce this with 1.12 (bleeding branch).

**Comment by ryantheleach** [comment]
To follow up, it is by design for most of the elements, and GenericArguments.remainingRawJoinedStrings is now exposed.
