### ISSUE TITLE
Move a majority of World API methods into MixinWorldServer

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#572]
As mentioned by @Zidane the other day, a majority of the API methods should only be called on by a `WorldServer` object since there are things such as `WorldClient`s and mod introduced fake worlds. The reasoning behind this is that interacting through the API in any way that provides access to a client side `WorldClient` will result in errors and or exceptions being thrown. This is just a general issue to discuss which bits of `MixinWorld` can be indeed moved over to the `MixinWorldServer` and equivalents.

**Comment by Zidane** [comment]
All bits of MixinWorld can be moved to WorldServer and should be moved because we shouldn't touch non-server worlds with Sponge.

**Comment by Zidane** [comment]
This has been mostly finished in 1.9.4 | bleeding.
