### ISSUE TITLE
Workaround MAX_HEALTH limitations

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#575]
Currently, max health is unlimited in 1.8.9, however in 1.9, there's a hard limit of the max health displayed on a client. This workaround will closely tie into health scaling to a certain point.

Note in 1.9: The maximum allowed health that both the client and server will accept is 1024.

**Comment by kashike** [comment]
I'm pretty sure the same limit applied in 1.8.9 and earlier.

**Comment by DarkArc** [comment]
This seems to apply to 1.8.9, I'm fairly certain that it wasn't in 1.7, can't attest for 1.8. Very strange modification, I wonder what the reason for the change was.

**Comment by ImMorpheus** [comment]
I think this can be closed. Quoting from https://github.com/SpongePowered/SpongeAPI/issues/1733:

> You can successfully set the health scale to 20 and the client will always see what is worth 20 hearts of health (10 whole hearts to be exact). The advantage here is that you can now set the maximum health to Float.MAX_VALUE willingly without obstructing the client with that insane value. The health scale test plugin included SpongeCommon allows for such values even.
