### ISSUE TITLE
Error with S2FPacketSetSlot

### ISSUE THREAD

**Issue by hsyyid** [SpongePowered/SpongeCommon#580]
[Result] (https://gyazo.com/7dc71de836244e6c19d4124fb92b107d)

No errors are logged in console. 

```java
List<Inventory> slots = Lists.newArrayList(player.getInventory().slots());

for (int i = 0; i < slots.size(); i++)
{
  System.out.println("Slot: " + i);
  slots.get(i).set(ItemStack.builder().itemType(ItemTypes.NONE).build());
}
```

[Console Output] (http://pastebin.com/dHx4avXa)

**Comment by simon816** [comment]
That's probably because you're using `ItemTypes.NONE` which is an invalid item.
Try calling `slots.get(i).set(null);`

**Comment by hsyyid** [comment]
@simon816 Shouldn't the inventory impl handle that?

**Comment by simon816** [comment]
Yes, it should add some defense against invalid items.

**Comment by hsyyid** [comment]
@simon816 Not only that, if `NONE` is an `ItemType`, it shouldn't be throwing errors when you try to set that - the impl should be dealing with that.

**Comment by modwizcode** [comment]
I feel like a null item is something that should be invalid, while a NONE item should be the correct solution. Just a thought though.

**Comment by simon816** [comment]
I'm assuming the intention here is to empty a slot, perhaps using `slot.clear()` would be more appropriate here.
We either throw `IllegalArgumentException` on a `NONE` item, or we internally clear the slot.

**Comment by modwizcode** [comment]
If we have a `slot.clear()` then that should be how you clear items. I think `NONE` should still be supported to have it be cleaner if you have let's say a hotbar toolbox plugin, and need to define all the hotbar slots, having a none item slot is a better (and simpler) format than making the plugin special case that gap. Obviously other solutions are possible, but that somehow feels cleaner to me.
