### ISSUE TITLE
Zombie Reinforcements get categorized as "DROPPED_ITEM"

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#584]
Zombie Reinforcements when spawned are categorized as DROPPED_ITEM rather than something more applicable like PASSIVE, or their own type.

**Comment by DarkArc** [comment]
I misidentified this issue, they are not getting spawned as CUSTOM, but rather DROPPED_ITEM.

**Comment by simon816** [comment]
I'm thinking that the cause tracker is making the naive assumption that any entities spawned when an entity dies are item drops. Possibly something cleaned up in @gabizou's refactor of the system.
