### ISSUE TITLE
Use FastUtil rather than Trove for more memory efficient collections and maps.

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeCommon#586]
Whilst Trove has been around for a while, it isn't as actively developed anymore. FastUtil is much more recent, and actively developed.

On top of this, Trove doesn't hold up in terms of performance compared to more modern libraries. Here's an example of a benchmark that pits numerous libraries together,

http://java-performance.info/hashmap-overview-jdk-fastutil-goldman-sachs-hppc-koloboke-trove-january-2015/

Another option is Koloboke, which appears to include enhanced integration with JDK8.

**Comment by me4502** [comment]
Koloboke is looking to be a better option, as the FastUtil jar is 17mb.

**Comment by Zidane** [comment]
@amaranth 

Your thoughts on this?

**Comment by Minecrell** [comment]
Koloboke's full JAR is even bigger (about 18 MB), so if we'd choose one of them we'd need to filter the unused classes out before shading, because that would be way to big to shade completely.

**Comment by amaranth** [comment]
Now that Minecraft is including a subset of fastutil it makes sense to use that in place of trove.

**Comment by Minecrell** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/81e15b64da5b1c3dda4ec3cce2469cef13a4f0dd
