### ISSUE TITLE
The CatalogType of Weather is empty!

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/SpongeCommon#59]
I tried to get the Weather Types and the result was to return a empty collection.

Source:
```java
game.getRegistry().getAllOf( CatalogTypes.WEATHER ); //returned an empty collection.
```

The SpongeGameRegistry needs revision. https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java#L1079

**Comment by simon816** [comment]
There is a TODO marker beside the `Weather` catalog map, [`SpongeGameReigistry:504`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java#L504), so this will get done at some point (likely at the same time as several other registry TODOs)

**Comment by JBYoshi** [comment]
Mumfrey's working on an overhaul of the game registry that should take care of this (see #61)

**Comment by bloodmc** [comment]
This was fixed by gabizou in commit https://github.com/SpongePowered/SpongeCommon/commit/af86add69d6cc75b618196461f2310ca9576b6b7
