### ISSUE TITLE
"/page <number>" should give the specified page

### ISSUE THREAD

**Issue by turtledude01** [SpongePowered/SpongeCommon#593]
When doing /page <number> the sub command does not exist, but should show the user the page they specify.

**Comment by kenzierocks** [comment]
`/page page <number>`

**Comment by turtledude01** [comment]
That seems like a really redundant command, but i guess with how Sponge handles sub commands, your stuck with doing it that way, right?

**Comment by VcSaJen** [comment]
Help for /page shows:
`/page <pagination-id> next|previous|page`
Which is implies that pagination-UUID is non-optional, while it can be omitted. I don't know what's up with that.

P.S. On unrelated note, I think it would be helpful if page number below paginated list would link to onClick 'suggest_command' `/page page ` (or `/page `, if it will be changed)

**Comment by ryantheleach** [comment]
It's because the pagination-id is always needed, just the command argument knows how to fallback to a known value if one has been used previously. However I can see how this is confusing for users, So I have adjusted the syntax used.
