### ISSUE TITLE
Explosions made with the explosion builder are "CUSTOM" damage type

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#595]
Explosions made with the explosion builder are set to the "CUSTOM" damage type, rather than being set to the more reasonable "EXPLOSIVE" damage type.

**Comment by kashike** [comment]
Is it not possible to specify what type during the creation of the explosion?

**Comment by DarkArc** [comment]
It is not

---- On Fri, 13 May 2016 19:30:42 -0700 notifications@github.com wrote ----

Is it not possible to specify what type during the creation of the explosion?

**Comment by Zidane** [comment]
Re-test with stable-5 and report back if still an issue and we will re-open.
