### ISSUE TITLE
Rewrite SpongeUser serialization to use Sponge related Compounds

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#597]
SpongeUser currently duplicates how Forge saves bed spawns per world, which isn't going to work going towards the future versions of Minecraft. This needs to be converted during the 1.8.9 support phase and continue with 1.9.

**Comment by Zidane** [comment]
Closing this as I don't think its relevant anymore @gabizou . Re-open if I'm wrong.
