### ISSUE TITLE
CatalogType does not ignore case.

### ISSUE THREAD

**Issue by nikosgram13** [SpongePowered/SpongeCommon#60]
I tried to get a GameMode type from the CatalogType and I noticed the following. When the Type name is in Lower Case the CatalogType can't find the type.

Example:
```java
game.getRegistry().getType(ItemType.class, "SPONGE").orNull(); //returned the SPONGE ItemType.

game.getRegistry().getType(ItemType.class, "sponge").orNull(); //returned null.
```

**Comment by Deamon5550** [comment]
I'm pretty sure we probably do want these keys to be case insensitive, I can't see us wanting to allow registering types with keys that differ only by case, it would follow then that we make the keys case insensitive.

Thoughts @SpongePowered/developers ?

**Comment by Aaron1011** [comment]
I agree with this idea. I can't imagine any case where we'd have keys that were distinguishable just be case, so I think we should change this.

**Comment by gabizou** [comment]
@Deamon5550 I agree with keys being case insensitive. I'm sure though @Mumfrey's `GameRegistry` changes will likely fix this in the very near future.

**Comment by JBYoshi** [comment]
@Zidane Close?

**Comment by JBYoshi** [comment]
Never mind. It's not in master yet.
