### ISSUE TITLE
Offering a player no health doesn't result in the normal death sequence

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#603]
I have a minigame where I use the Data API to set a player's health to 0.

If I kill the player using the "/kill" command, I see a death message, and things proceed as I expect. If I kill them via setting their health to 0 via offering them the health key (ex ```.offer(Keys.HEALTH, 0D);```) they just respawn with their inventory items in tact, and no death message appears.

**Comment by modwizcode** [comment]
Are you considering this a bug? This is the current processing that happens https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/multi/entity/HealthDataProcessor.java#L67-L69

**Comment by modwizcode** [comment]
Sorry that's when using the `HealthData` `DataManipulator`, compared to using the value `https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/value/entity/HealthValueProcessor.java`, it just sets the health, not calling an onDeath. I would say this is an oversight unless @gabizou has another opinion.

**Comment by ryantheleach** [comment]
It's surprising that the respawn code fires when setting the health to 0, but death doesn't happen.

That said, people have wanted a way for people to die without showing the respawn gui, this just feels like a clunky way to do it.

**Comment by modwizcode** [comment]
Maybe a 0 health set by plugins should be invalid and have killing players
happen by another method. That way the respawn cause is modifiable and
relevant.

**Comment by DarkArc** [comment]
@ryantheleach The GUI is still shown... Item dropping, and the death events are what seem to be absent.

@modwizcode No I don't think that's a good solution at all. Then any kind of forced health change code that might kill someone has to handle ``` if newHeath == 0 { kill(); } else { ... } ```, and that's just annoying.

**Comment by ryantheleach** [comment]
The least surprising action to happen when setting health to 0 is for the player to die normally.

**Comment by modwizcode** [comment]
Yes in that case probably going with the least surprising behavior will be
best.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/755adb3a947d86281dd14915dcf4a75c53072d9c.

**Comment by DarkArc** [comment]
I'm still seeing this for some reason...
