### ISSUE TITLE
WorldBorder.ChunkPreGenerate does not populate the chunks.

### ISSUE THREAD

**Issue by Cybermaxke** [SpongePowered/SpongeCommon#611]
Using the ChunkPreGenerate task does not populate any chunks, the thread that is relevant to this issue can be found [here](https://forums.spongepowered.org/t/chunk-pregeneration-utility/12002).

The source of the issue is that the ChunkPreGenerate task the chunks generates one by one and unloads them directly afterwards, but in order to be able to populate the chunks should the surrounding chunks also be loaded, which in this case never happens.

xx    o = The chunk that is loaded.
ox    x = The chunks that are required for population.

A solution would be to load the other chunks before population, but this would cause disruption of the chunk generation order.

**Comment by Cybermaxke** [comment]
@DDoS It seems like the issue is not completely resolved, only parts of the region are being populated.
http://imgur.com/B0Sro90

**Comment by DDoS** [comment]
I'll try keeping more loaded, let me known if that works.
