### ISSUE TITLE
Can't set Dispenser and Dropper to Direction.UP and DOWN, can't set special rails to any RailDirection.

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeCommon#612]
I can't set Dispenser and Dropper to Direction.UP and DOWN, and can't set special rails to any RailDirection. I'm testing it with this code:
``` Java
    @Listener
    public void onInteractSecondary(InteractBlockEvent.Secondary event) {
        BlockState bs = event.getTargetBlock().getState();
        if (bs.getType().equals(BlockTypes.DISPENSER) ||
                bs.getType().equals(BlockTypes.DROPPER))
        {
            if (event.getTargetBlock().getLocation().isPresent())
            {
                event.getTargetBlock().getLocation().get().setBlock(bs.with(Keys.DIRECTION, Direction.UP).get(), false);
            }
        }
        if (bs.getType().equals(BlockTypes.GOLDEN_RAIL) ||
                bs.getType().equals(BlockTypes.RAIL) ||
                bs.getType().equals(BlockTypes.ACTIVATOR_RAIL) ||
                bs.getType().equals(BlockTypes.DETECTOR_RAIL))
        {
            if (event.getTargetBlock().getLocation().isPresent())
            {
                event.getTargetBlock().getLocation().get().setBlock(bs.with(Keys.RAIL_DIRECTION, RailDirections.EAST_WEST).get());
            }
        }

        logger.info(bs.toString());
    }
```
Problem is that `.with` return Optional.empty() or BlockState with default Value of Key.

Tested on SpongeForge 1.8.9-1763-4.1.0-BETA-1225 and SpongeVanilla 1.8.9-4.1.0-BETA-281.

**Comment by Aaron1011** [comment]
@VcSaJen: I've fixed the issue with dispensers and droppers in https://github.com/SpongePowered/SpongeCommon/commit/470fa428a2dd1961deeff30cb26e8c59f9d814a1. You can download the latest SpongeForge to get those fixes.

After investigating the rail direction issue, I've discovered that it's not actually possible to set (at least for now). No matter what state you set, `BlockRailBase` always forces it to the 'correct' state when the block is added (the state that makes it connect to neighboring blocks).

However, it will be possible to send the client a particular rail blockstate, which will be displayed regardless of the neighboring blocks (once [this PR](https://github.com/SpongePowered/SpongeAPI/pull/1144) is merged). For now, though, there's not much you can do without using the MC sources and sending the packet yourself.
