### ISSUE TITLE
Implementation of the InteractEntityEvent

### ISSUE THREAD

**Issue by TBlueF** [SpongePowered/SpongeCommon#62]
According to [this](https://github.com/SpongePowered/Sponge/issues/274) Event Progress Tracker and my Plugin, the **PlayerInteractEntityEvent** is not jet implemented.
_Deamon5550 said [here](https://github.com/SpongePowered/Sponge/issues/272): "Opening issues like these does help us prioritize which events we're implementing." So i thougt i'll open this issue, since this is the last missing event i need to finish my plugin and start my server :)_

For the sake of completeness:
_Sponge Build: 1.8-1371-2.1DEV-467
Forge Build: forge-1.8-11.14.1.1397
Client Type/Version (Forge/Vanilla and version) : Vanilla 1.8.6
Installed Plugins and/or Mods: Sponge, My Plugin, (and DynmapForge)
Java Version: 1.8.0_40
Operating System: Windows 7 64 bit_

(Reopens [this Issue](https://github.com/SpongePowered/Sponge/issues/286))

**Comment by RafVDL** [comment]
I quickly wrote this (it needs to be inserted into MixinNetHandlerPlayServer):
```java
@Inject(method = "processUseEntity", at = @At(value = "INVOKE", target =
        "net/minecraft/network/play/client/C02PacketUseEntity.getAction()" +
                "Lnet/minecraft/network/play/client/C02PacketUseEntity$Action;", ordinal = 0), cancellable = true, locals = LocalCapture.CAPTURE_FAILSOFT)
public void processUseEntity(C02PacketUseEntity packetIn, CallbackInfo info, WorldServer worldserver, Entity
        entity, boolean flag, double d0) {
    EntityInteractionType type = null;
    Vector3d location = null;
    switch (packetIn.getAction()) {
        case ATTACK:
            type = EntityInteractionTypes.ATTACK;
            break;
        case INTERACT_AT:
            location = new Vector3d(packetIn.getHitVec().xCoord, packetIn.getHitVec().yCoord, packetIn.getHitVec().zCoord);
        case INTERACT:
            type = EntityInteractionTypes.USE;
            break;
    }
    
    if (type == null) return;

    if (Sponge.getGame().getEventManager().post(SpongeEventFactory.createPlayerInteractEntity(Sponge.getGame(),
            this.getPlayer(), (org.spongepowered.api.entity.Entity) entity, type, location))) {
        info.cancel();
    }
}
```
I can't test it completely as I'm having issues with my workspace (SpongePowered/SpongeAPI#673), but I can confirm that the event gets posted.

**Comment by JBYoshi** [comment]
IMO this should be part of Sponge and SpongeVanilla, not SpongeCommon. Forge has its own event for this - `net.minecraftforge.event.entity.player.EntityInteractEvent`.

**Comment by TBlueF** [comment]
After event-refactor: Still valid issue, just an other name. Waiting patiently... =)

**Comment by gabizou** [comment]
@TBlueF I'm just going to say that the `InteractEntityEvent`s and such have been implemented at least partially implemented in almost all cases. However, if there is an interaction that is missing an event (and you've tested it), please let me know, otherwise this issue should be resolved.

**Comment by TBlueF** [comment]
Nope, nice work! :)
