### ISSUE TITLE
Optimization Mixin Plugins

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#621]
Throughout #502's development, I've found many areas where I thought "this could be optimized to reduce the amount of entity spawns," or "this type of system can reduce the stress of chunk loads." A few of these optimizations have started making their way into the implementation as Mixin plugins, an example being #566 where some changes in the server performance can be less noticeable.

Ultimately however, I'd like to see about forming a list of potential optimizations and how to group those optimizations as Mixin plugins to where they're applied only when enabled.

The ones I've found currently possible to do:
- [x] ~~**Pre-merge `ItemStack` spawns:** This involves CauseTracking as the item stacks would have to be captured prior to being spawned as entities, to which the maximum allowed stack size would be merged, eliminating the necessity for multiple `EntityItem`s to merge _after_ they have been spawned into the world~~ Added in 1.9 with Cause Tracking Refactor
- [x] ~~**Prevent block ticking from loading chunks from file**: There are certain corner cases that block ticks will request a `BlockState` into the neighboring chunk, which has a tendency to be unloaded (meaning the block that is ticking is at the very edge of the chunk radius for a `Player` anyways). While this is normally what Vanilla Minecraft will do, this can be better optimized to avoid adding extra overhead of these tick caused chunk generation/loading.~~ This is intended.
- [ ] Employ a more powerful object tick range to process closer objects more often versus objects further away. This is partially an idea that CraftBukkit++ had originally, and I've found various areas that we could employ such a system, though nothing set in stone as of yet.
- [x] BlockState micro-optimization for often called methods
- [x] Cache last retrieved chunk in `LongObjectHashMap`

I'd appreciate more ideas from the community, and any code contributions would be well reviewed for acceptance (seriously, don't just copy, there are licenses to follow and copyrights to obey, you should look at a feature and try to work out an implementation without referring to other implementations).

**Comment by kashike** [comment]
:+1: for using mixin plugins instead of including in core - some optimisations/changes, such as merging itemstacks, are unwanted quite often, so being able to enable/disable each optimisation/change is a huge plus.

**Comment by mcsnetworks** [comment]
Crop growth....

**Comment by mcsnetworks** [comment]
Also, blood had a function within Cauldron that TE's would skip ticks if a player wasn't near.  This can have a bad effect on a mod but a good effect on the servers performance.

**Comment by mcsnetworks** [comment]
Limiting Chunks Generated per tick helps servers with complex map generation (aka TerrainControl).

**Comment by Deamon5550** [comment]
- The fix for end spikes
- If we didn't fix the chunk loading from file twice in core we could do that here

**Comment by Zidane** [comment]
@Aikar
This seems to be right up your alley...I know you gave us full permission to use your commits to Paper. 

Are there any that you would recommend we do "right away"?

Also pinging @amaranth since he had ideas as well (beyond wall time).

**Comment by aikar** [comment]
https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0105-Optimize-Chunk-Access.patch
https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0082-Chunk-save-queue-improvements.patch
https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0100-Optimize-Chunk-Unload-Queue.patch
https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0091-Optimize-BlockStateList-BlockData.patch
https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0063-Optimize-Pathfinding.patch
https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0107-Optimize-isValidLocation-for-inlining.patch

I think some of them may depend on some stuff from:
https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0092-Add-World-Util-Methods.patch

brand new so hasnt had time to report any known bugs but can help tremendously: https://github.com/PaperMC/Paper/blob/dea2d41b86e2a749251e12dd33439a08e9622dba/Spigot-Server-Patches/0125-Do-not-load-chunks-for-light-checks.patch

**Comment by me4502** [comment]
The patch that optimises isValidLocation for inlining... Does that really make a measurable difference?

**Comment by aikar** [comment]
@me4502 it's showing up in profilers as a hotspot, meaning it's not inlined. It's one of the most hottest methods called. It's a micro optimization, but at scale, it adds up. Lot of the performance comes by multiple micro optimizations in combination together.

**Comment by aikar** [comment]
updated chunk access patch to https://github.com/PaperMC/Paper/blob/081420d738fffe256fd18aa57dfe762be356493d/Spigot-Server-Patches/0105-Optimize-Chunk-Access.patch

noted by amaranth that previous version where invalidation was handled manually at caller would be an issue for mods that may mess with the map themselves., so moved the invalidation to be an overloaded .remove()

**Comment by Zidane** [comment]
@aikar 

Thanks for the links. This is actually pretty simple to put into place with Mixin's capabilities. The bigger challenge is making sure that what we do doesn't break mods (though SpongeVanilla has full reign to do as it pleases).

**Comment by kashike** [comment]
A few of the patches @aikar linked might be good being PR'd to Forge instead.

**Comment by gabizou** [comment]
@kashike sure, but you're still leaving out SpongeVanilla.

**Comment by kashike** [comment]
no, I'm not. I'm saying to PR to Forge instead of SC/SF, and add to SV separately.

**Comment by gabizou** [comment]
@aikar I'm still all ears for adding more optimizations in 1.9.4, or possibly back porting any optimizations for 1.8.9.

**Comment by bloodmc** [comment]
Closing as this should already be done.

**Comment by liach** [comment]
@gabizou Would you optimize furnaces?
