### ISSUE TITLE
ItemStacks should be constructable with a -1 size

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#624]
The ItemStack builder doesn't currently allow an item stack to be created with a size of -1:
https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/item/inventory/SpongeItemStackBuilder.java#L86

However, some portions of the Inventory API need ItemStack's with a size of -1 to function properly:
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/item/inventory/Inventory.java#L389

**Comment by Zidane** [comment]
This is a duplicate of https://github.com/SpongePowered/SpongeCommon/issues/150

Please review open issues before creating them in the future.

**Comment by DarkArc** [comment]
I tried to, evidently not hard enough.
