### ISSUE TITLE
Interact at 0, 0, 0 when right clicking water

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#626]
I recently got some reports of strange "block interaction denials" on my server. Upon adding some debug code, it appears that right clicking water (with an empty bucket in hand) includes a block interact at 0, 0, 0.

This may be related to:
https://github.com/SpongePowered/SpongeForge/issues/260

Screen shot of debug output provided by one user:
https://screencloud.net/v/pLJu

Code used to produce the error:
```java
    @Listener
    public void onInteract(InteractBlockEvent event) {
        Optional<Player> optPlayer = event.getCause().first(Player.class);
        if (optPlayer.isPresent()) {
            Player player = optPlayer.get();

            Optional<Location<World>> optLoc = event.getTargetBlock().getLocation();
            if (optLoc.isPresent()) {
                if (check(player, optLoc.get())) { // This a region permissions check function
                    event.setCancelled(true);
                    if (event.getCause().root().equals(player)) {
                        player.sendMessage(Text.of(TextColors.RED, "You can't interact with blocks here!"));
                        player.sendMessage(Text.of(TextColors.RED, "[Debug] ", optLoc.get(), " [Cause ", event.getCause(), "]"));
                    }
                }
            }
        }
    }
```

**Comment by bloodmc** [comment]
This has been brought up many times. If a player does not select a block(water cannot be selected) and right-clicks in AIR, the C08PacketPlayerBlockPlacement will use its default BlockPos of (-1, -1, -1) which is not in the accepted range of
 
(-30000000, 0, -30000000) to (29999999, 255, 29999999)

To workaround this, Forge passes the location 0, 0, 0 with action type of AIR as seen here

https://github.com/MinecraftForge/MinecraftForge/blob/master/patches/minecraft/net/minecraft/network/NetHandlerPlayServer.java.patch#L72

If any changes need to be done, it should be requested with Forge so mods don't break.

**Comment by DarkArc** [comment]
Well we convert their interact event into our interact event, correct? 

So, why can't we safely have a "UntargetedInteractEvent", w/ "UntargetedInteractEvent.Primary" and "UntargetedInteractEvent.Secondary" or something of that sort, when we get the special case, we instead use those, that way the InteractBlockEvent always has a valid block target?

Since the block's invalid anyways, it's not like we'd be discarding any valid information from a Sponge plugin.
