### ISSUE TITLE
Normal zombies are spawning in the nether

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#627]
Normal zombies are spawning in the nether, presumably from the Zombie reinforcement code.

**Comment by bloodmc** [comment]
Did you test with no plugins or mods and with a fresh world? List exact build you were using and whether it was client or server.

**Comment by modwizcode** [comment]
I just tested with no plugins, no mods and a clean world from the latest build. I cannot reproduce this issue in any form.

**Comment by DarkArc** [comment]
Ah, I should've specified, this Nether world is not the Nether world generated by the server by default. It's a created nether world using the API:
```
WorldCreationSettings.Builder builder = WorldCreationSettings.builder();
builder.enabled(true).loadsOnStartup(true).dimension(DimensionTypes.NETHER).generator(GeneratorTypes.NETHER).name("some name").seed(random.nextLong()).usesMapFeatures(true).build()
```

As for the build info:
```
    Minecraft: 1.8.9
    SpongeAPI: 4.1.0-SNAPSHOT-8b23bcf
    SpongeForge: 1.8.9-1808-4.1.0-BETA-1227
    Minecraft Forge: 11.15.1.1764
```

**Comment by modwizcode** [comment]
I will investigate this after classes today.

**Comment by simon816** [comment]
I just tested with the above creation settings and got a regular nether with regular pigzombies. @DarkArc does this still happen?

**Comment by DarkArc** [comment]
Can't seem to reproduce this any more either.
