### ISSUE TITLE
setBlock() LIT_REDSTONE_LAMP doesn't work

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeCommon#633]
Location#setBlockType(BlockTypes.LIT_REDSTONE_LAMP) doesn't work. It instead places an unlit lamp. The bug can be reproduced by the setBlock command ingame. https://bugs.mojang.com/browse/MC-46649 states that this behavior is intended.
Sponge should do the right thing: Forcefully place a lit lamp!

https://github.com/randombyte-developer/street-lights/blob/693a89418a11686fdb07c866bda3125f1451e1ba/src/main/kotlin/de/randombyte/streetlights/database/Lights.kt#L44

**Comment by Deamon5550** [comment]
It would become unlit again as soon as it receives a block update.

**Comment by randombyte-developer** [comment]
How to prevent this?

**Comment by ryantheleach** [comment]
Cancel change block events that change it from lit to unlit?

**Comment by gabizou** [comment]
You have to set it with [`#setBlock(int x, int y, int z, BlockState block, boolean notifyNeighbors)`](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/world/extent/Extent.java#L117-L128). This should effectively set the redstone lamp without notifications.

**Comment by randombyte-developer** [comment]
Sorry, but changing it with [this commit](https://github.com/randombyte-developer/street-lights/commit/f367ba2533ffd9efc076889062b568fd806cc557) doesn't help. Even with `notifyNeighbors = false` it doesn't work(but this is as I assume only for the neighbor blocks as the name says).

**Comment by Aaron1011** [comment]
@randombyte-developer: Are you cancelling changes to the block (e.g. from lit to unlit)?

**Comment by randombyte-developer** [comment]
No, not yet. How could I do that? Giving a cause to the setBlock and cancel all other change events to lamps instead of my own setBlock?

**Comment by Aaron1011** [comment]
@randombyte-developer: I mean, you need to listen to `ChangeBlockEvent.Modify`, and cancel any transaction which changes your block from lit to unlit.

**Comment by randombyte-developer** [comment]
@Aaron1011 I have to listen to `ChangeBlockEvent.Place`. Cancelling the block update produces the effect that the lamp stays lit. My problem is to identify those specific block updates so not that the plugin blocks all events that contain lit lamps. The cause of the block updates is somehow lava that is about 100 blocks away... ?!

**Comment by Aaron1011** [comment]
@randombyte-developer: I'm confused - don't you want certain lamp blocks to always stay lit? If so, can't you just cancel the `ChangBlockEvent.Modify` event transactions that touch the blocks you care about?

**Comment by randombyte-developer** [comment]
@Aaron1011 You understood it right.
It is too late. I have to sleep :smile:. I have to restructure my code. When I am finished I publish the plugin and you can see what I did.
