### ISSUE TITLE
Pixelmon Saving entity NBT NullReference crash

### ISSUE THREAD

**Issue by salmjak** [SpongePowered/SpongeCommon#635]
I posted about this on the forum. Know when I have a better idea about what's going on I decide to post it here:

https://forums.spongepowered.org/t/pixelmon-saving-entity-nbt-server-crash/12153

This might have nothing to do with Sponges SnapShotBuilder, but it would be nice if someone could take a look.

**Comment by simon816** [comment]
Looks like an issue with pixelmon, report it to them.

**Comment by clienthax** [comment]
Fixed in next release <3
