### ISSUE TITLE
A DataQuery part containing "." is expanded incorrectly when deserializing data

### ISSUE THREAD

**Issue by Wolfizen** [SpongePowered/SpongeCommon#637]
**SpongeForge version:** 1.8.9-1808-4.1.0-BETA-1237
**Forge version:** 1.8.9-11.15.1.1808
**Plugins installed:** My personal WIP plugin
**Logs:** N/A

My plugin id is `net.my.plugin` as recommended by the code style. For any custom `Key`s, I use a query like `DataQuery.of("net.my.plugin_MyData")`. I use the query when converting my `DataManipulator` to a `DataContainer`. However, when my manipulator is given a container to restore back from, the data is instead nested as if the query was created like `DataQuery.of("net", "my", "plugin_MyData")`

Here is a representation of the container when serializing: `net.my.plugin_MyData { ... }`
And here is what is given when deserializing: `net { my { plugin_MyData { ... } } }`

I have used my IDE's debugger to verify the structure of the two containers.

My implementation of DataManipulator#toContainer() looks like this:
```
@Override
public DataContainer toContainer() {
    DataContainer dataContainer = super.toContainer();
    dataContainer.set(MyData.KEY.getQuery().then(DataQuery.of("someData")), someData);
    return dataContainer;
}
```

@modwizcode has suggested the problem lies in [DataQuery#toString()](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/data/DataQuery.java#L229) and its related usages.

**Comment by modwizcode** [comment]
This is one of a few uses of `asString('.')` that causes a '.' separated query from behaving as expected. https://github.com/SpongePowered/SpongeCommon/blob/ce903298ff8293513495c865509e2af5b0fc1239/src/main/java/org/spongepowered/common/data/persistence/NbtTranslator.java#L83

**Comment by Cybermaxke** [comment]
Replacing all the `of('.', key)` with `of(key)` in the NbtTranslator should fix this issue.

**Comment by modwizcode** [comment]
Why? I believe internally that calls `of('.', key)`

**Comment by Wolfizen** [comment]
<3
