### ISSUE TITLE
Pagination jitters.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#638]
At the moment Pagination jitters if the next element would span multiple lines making it appear inconsistent in chat.

Perhaps the contents should be padded with lines so that way it fills the entire chat box, making the previous and next arrows of the previous text hidden.

@Zidane You asked for more justification.

![image](https://cloud.githubusercontent.com/assets/141554/15266769/9d83c0e2-19ee-11e6-8054-5a258a8cfdaf.png)

Is how it looks without these changes, Notice that it can and will show the previous set of navigation links.

This PR adds whitespace so that this doesn't happen on the default chat width/height.

**Comment by ryantheleach** [comment]
I'm partially through coding this, and it looks somewhat empty if there is a large amount of whitespace. But still somewhat better then what the jitter did. Wondering what the best method of dealing with it will be. 

![image](https://cloud.githubusercontent.com/assets/141554/14319511/a36c3cfc-fc50-11e5-9b89-8b2b5d7b7db5.png)


![image](https://cloud.githubusercontent.com/assets/141554/14319497/959cebe4-fc50-11e5-9eed-5f20c313c1fc.png)

**Comment by ST-DDT** [comment]
I would prefer the whitespace before the content so it is aligned to the bottom. Because the textbox itself is too. Otherwise the text just flies in the middle of the screen.

**Comment by ryantheleach** [comment]
![image](https://cloud.githubusercontent.com/assets/141554/14348410/742ff3f6-fcfb-11e5-9836-0bc7f252639f.png)

![image](https://cloud.githubusercontent.com/assets/141554/14348416/802234bc-fcfb-11e5-9381-805548aeca67.png)

As the textbox has focus, and the text all appears at the same time it's going to "fly into the middle of the screen" regardless if it's paddded, as the background of the text box dims the screen.

![image](https://cloud.githubusercontent.com/assets/141554/14348470/d2c69820-fcfb-11e5-916a-5c54152c99c3.png)

**Comment by ST-DDT** [comment]
I would move the available commands section after the whitespace too because then you only need one or two lines of whitespace and the other stuff would already fade out.

But waiting for official approval is also a good idea.

**Comment by ryantheleach** [comment]
@ST-DDT I agree with you now regarding the prepending of the padding.

I was just testing pagination on the Sponge Community Server and when connected remotely the chat that comes back doesn't fill the whole screen, meaning the response the player gets back for pagination doesn't necessarily display immediately, if padding is appended then it's possible for the commands to appear in the "scroll back" hidden area instead of appearing on the screen, which can be confusing for users.
