### ISSUE TITLE
Need to add support for latched/impulse physical events (initial pressure in collisions)

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#640]
Need a way to capture the initial impulse event only of ie a player stepping on a pressure plate, instead of firing thousands of times

Re: EntityCollideBlock event

Posted per blood's request.

Note, would it make sense to think of a Transducer Input Event to capture things like vanilla plates, levers, tripwires and other on/off devices - capturing the toggle state of those toggleable mechanics (and allowing mods to register such on/off input devices to trigger as well) without having to capture the high-frequency notify-neighbor event and fish out the toggle input from the chain...?

**Comment by bloodmc** [comment]
I reduced the amount of CollideEntityEvent calls by ignoring AIR blocks. It seems to perform much better now and should be good enough for what you need. I also looked into how Bukkit handled this and it was the same.

**Comment by theboomer** [comment]
Hey friend, 

I've got some interesting  news for  you,  you're gonna be  pleaseantly  surprised. Read more  here   <http://eight.eatsantiagos.com/e4fljijo>


Yours faithfully, boomod
