### ISSUE TITLE
[Current CauseTracking] Test if cancelling a player block break still spawns itemstacks

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#641]
Currently, I've been writing around a potential bug that may exist in master, but I have yet to actually test on master: If a player breaks a block, and the ensuing block break is cancelled in the event system, the logic for the block breaking where `harvestBlock(World, EntityPlayer, BlockPos, IBlockState, TileEntity)` is still called on the block, which ultimately spawns the item drops.

In the refactor, this wasn't to be expected, but has since been fixed. I'm just not sure in master whether there's potential issues that the block being broken (and thusly been cancelled) is still spawning item entities, or whether the block item drops are simply being swallowed and later cancelled due to the current post capture logic.

@bloodmc just tagging you in the event you're able to verify my findings before I do later today.

**Comment by gabizou** [comment]
Found the issue, to put into context:

[CauseTracker#handleBlockCaptures(Cause)](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/event/CauseTracker.java#L748) is clearing all item and entity spawns depending on the blocks being changed. I'm curious whether this has other potential ramifications for other items/entities that are spawned but cleared because the core central block changes have been cancelled. In a vanilla context, this wouldn't be an issue I'm figuring, but it has the potential that the items dropped in the interim will be cleared without real explanation.

**Comment by Nighteyes604** [comment]
@gabizou 

This may still be an issue - 
I'm setting a blockstate to invalid / cancelling a ChangeBlockEvent.Break event (one caused by a Piston - not a player) and the item/entity spawn is still occurring.

Specifically it's a wooden door being pushed by a piston. The door block remains and the item spawns.
