### ISSUE TITLE
Itemframes wash away in spongeforge, but not vanilla/forge

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#642]
Tested with spongeforge-1808-1250, vanilla minecraft 1.8.9 and forge-1808

In spongeforge, if water flows down over an itemframe, or it is at ground level and water flows into it, the itemframe remains on the block submerged fine, but when the water source is removed and frames are reexposed to air, the itemframes pop off the blocks.  Vanilla minecraft behavior is they are not impacted by the addition and removal of water.

![washedawayitemframes](https://cloud.githubusercontent.com/assets/3393225/14370364/8180e61e-fcfb-11e5-94a9-48259cb3cf56.png)

**Comment by gabizou** [comment]
Can you test this in SpongeVanilla?

**Comment by theboomer** [comment]
i can, and shall.

**Comment by theboomer** [comment]
Yes, the behaviour is identical in spongevanilla Beta-291
