### ISSUE TITLE
@Exclude has no effect

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeCommon#643]
`@Exclude` has no effect. https://github.com/randombyte-developer/teleport-compass/blob/1485525853cc47e1bdaf6cfa8b5afa9853f20fec/src/main/kotlin/de/randombyte/teleportcompass/ExcludedListenerJava.java#L14-L14 gets fired but it shouldn't when `InteractBlockEvent`. https://forums.spongepowered.org/t/event-gets-fired-although-exclude/12189 others have problems too.

**Comment by gabizou** [comment]
@Deamon5550 this is your realm of expertise.
