### ISSUE TITLE
InteractBlockEvent.Primary gets called repeatedly on air click, even after releasing the button

### ISSUE THREAD

**Issue by mentlerd** [SpongePowered/SpongeCommon#647]
As the title says, the 'Primary' variant of the event gets called indefinitely, unless you interact with a block, or interact with the air with the right button.

**Comment by bloodmc** [comment]
@mentlerd I cannot reproduce this. Remove all plugins/mods except for sponge and test again.

**Comment by mentlerd** [comment]
I have forgot to mention that this happens when I cancel the event. In this case the method handling this event exits prematurely, so lastAnimTick will never get changed. 
[I think this part of code should run even if the event got cancelled](https://github.com/SpongePowered/SpongeCommon/blob/1953c13297f81517062b9404f31b97869e9e955f/src/main/java/org/spongepowered/common/mixin/core/server/MixinMinecraftServer.java#L1051)

**Comment by TheRaspPie** [comment]
The same happens to me. Very strange.
