### ISSUE TITLE
Scoreboard entries with long names can kick players.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#652]
If a score in the sidebar scoreboard has a name greater than 40 characters, the user will disconnect with an error. Sponge should check to make sure a particular string is within that limit, and truncate it if need be.

Mentioning @Aaron1011 cause scoreboards.

**Comment by kashike** [comment]
Probably best to throw an exception instead of truncating - here's what vanilla does, for reference:
```java
        if (username.length() > 40)
        {
            throw new IllegalArgumentException("The player name \'" + username + "\' is too long!");
        }
```

**Comment by modwizcode** [comment]
Agree with @kashike, truncating could technically allow overlap, and it's a pretty valid reason to throw.

**Comment by gravityfox** [comment]
This does leave an unanswered question though. Let's say this does happen. How would I go about truncating a Text object that is too long?

**Comment by gravityfox** [comment]
Actually, Objective names apparently have a 36 character limit. An exception should be thrown there too @Aaron1011.

**Comment by kashike** [comment]
@gravityfox Objective **display** names are limited to `32` characters, not `36`.

As for objective names - they are internally limited to `16` characters:
```java
        if (name.length() > 16)
        {
            throw new IllegalArgumentException("The objective name \'" + name + "\' is too long!");
        }
```

**Comment by gravityfox** [comment]
I meant the display name. xD

Either way my score names and display names have variable length, and if players decided to use ridiculously long world names or foxguard object names then it just sorta explodes. I would like to have it NOT do that.
