### ISSUE TITLE
Cancelling the DropItemEvent.Destruct event no longer preserves inventory items

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#654]
When a player is killed, previously you could cancel the DropItemEvent.Destruct and that would prevent the player's items from being dropped, instead, they would be kept in the player's inventory. This is no longer the case, and the player's items will instead be destroyed.

**Comment by DarkArc** [comment]
It's back again.

**Comment by bloodmc** [comment]
@DarkArc OK I'll fix soon.
