### ISSUE TITLE
MemoryDataView issue parsing collections

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#655]
gabizou spotted issue while looking over Set<UUID> deserialization...  I can't state what the issue is other than to quote the chat as reference.

`<gabizou>oh hah`
`<gabizou>Wolfizen, TheHiggsBozo, there's a minor bug in MemoryDataView`
`<TheHiggsBozo>oh?`
`<gabizou>it doesn't parse over objects within collections`

**Comment by gabizou** [comment]
Wrong repo: https://github.com/SpongePowered/SpongeAPI/issues/1188
