### ISSUE TITLE
Calling `Server.loadWorld(String)` for a non-existent world name creates world files

### ISSUE THREAD

**Issue by TheRaspPie** [SpongePowered/SpongeCommon#658]
Validated with SpongeVanilla build 293 and SpongeForge build 1272.

Specifically, these files are created:

* non-empty `session.lock` file
* empty `playerdata` folder
* empty `data` folder

**Comment by Zidane** [comment]
Nice catch @TheRaspPie 

Fixed.

**Comment by TheRaspPie** [comment]
Thank you so much!
