### ISSUE TITLE
Some block translations are off

### ISSUE THREAD

**Issue by 12AwsomeMan34** [SpongePowered/SpongeCommon#659]
Performing `getTranslation()` on a blocktype usually produces the correct translation (ie. if I use it on grass, I get 'Grass Block'). However, if use it on something such as sponge, I get 'tile.sponge.name'

Essentially, running the following code
https://gist.github.com/12AwsomeMan34/8023b50333d0be8707862ed51a70e72d

will produce this output
https://gist.github.com/12AwsomeMan34/753a8e191958776c5cbdd275115edb57

Note the ones such as 'tile.stone.name', 'tile.banner.name', or 'tile.sponge.name'. It would be nice if these were corrected for the usage of `getTranslation()`.

**Comment by Zidane** [comment]
I think this is because some translations are not known unless its in an ItemStack.

@Minecrell @gabizou ?

**Comment by Zidane** [comment]
@Minecrell @gabizou @Aaron1011 Comments? This issue shouldn't still exist...

**Comment by ImMorpheus** [comment]
Still happening with 1.12 (bleeding branch)

```
tile.stoneSlab2.name
tile.doorOak.name
tile.concretePowder.name
tile.cobbleWall.name
tile.stone.name
tile.diode.name
tile.doorBirch.name
tile.comparator.name
tile.banner.name
tile.null.name
tile.bed.name
tile.diode.name
tile.banner.name
tile.sapling.name
tile.concrete.name
tile.brewingStand.name
tile.null.name
tile.doorDarkOak.name
tile.comparator.name
tile.skull.name
tile.prismarine.name
tile.null.name
tile.stoneSlab2.name
tile.doorJungle.name
tile.flowerPot.name
tile.doorAcacia.name
tile.doorSpruce.name
tile.sponge.name
```

**Comment by ImMorpheus** [comment]
I'm working on this.

This also affects potions, gamemodes, blockstates and a couple of other things. (PR scheduled for... I don't know)

**Comment by parlough** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/pull/1728
