### ISSUE TITLE
Version Checker Problems

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#660]
Ubuntu's OpenJDK builds say their version is the following when accessed via the ```java.version``` property:
```
1.8.0_03-Ubuntu
```

However, this is not the case, and the build is actually:
```
1.8.0_77
```

If you use ```java.runtime.version``` property you receive:
```
1.8.0_03-Ubuntu-8u77-b03-3ubuntu3-b03
```

**Comment by DarkArc** [comment]
Why exactly do we need a version post update 40?

**Comment by gabizou** [comment]
@DarkArc because certain parts of our implementation relies on the various "fixes' that were pushed to the JRE for better stream compatibility with various collections (namely things like `CopyOnWriteArrayList`).

**Comment by DarkArc** [comment]
@gabizou do those changes only affect performance, or is there actually something that would crash Sponge?

It seems like a bit of overkill to crash the server if they're on Java 8 but they don't have the right update/we can't verify it.

**Comment by DarkArc** [comment]
This will hopefully be addressed by Ubuntu at some point, just as an fyi:
https://bugs.launchpad.net/ubuntu/+source/openjdk-8/+bug/1550244

**Comment by gabizou** [comment]
> @gabizou do those changes only affect performance, or is there actually something that would crash Sponge?

The changes made in update 40 result in a hard crash in the `SpongeDataManager` when trying to sort on a `CopyOnWriteArrayList`, and a few other stream crashes that took place early on.
