### ISSUE TITLE
"/entitydata" doesn't work instantly

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeCommon#665]
Since SpongePowered/SpongeAPI#1178 and SpongePowered/SpongeAPI#1179 doesn't seem to get attention I worked around setting some entity data. I used the `/entitydata ...`- command in my plugin. It calls it like so: 
``` kotlin
fun executeCommandAsConsole(command: String) = Sponge.getCommandManager().process(Sponge.getServer().console, command)
```
The entity is identified by its uuid so a command looks like this: `entitydata 550e8400-e29b-11d4-a716-446655440000 {PickupDelay:32767}`
The problem is that before this command another command must be executed. Otherwise: `That entity cannot be found`. Until now I just used `msg` and then second command works.

Edit: https://github.com/randombyte-developer/holograms/blob/master/src/main/kotlin/de/randombyte/holograms/EntityExtension.kt

**Comment by simon816** [comment]
I can confirm this strange behaviour.
I think it's caused by the `CauseTracker`, because when calling `spawnEntity`, it doesn't actually add the entity to the list - this is problematic and IMO must change.
When executing a command (e.g. `msg`) it will flush the pending entities and actually spawn them in.
@gabizou Has the cause tracking refactor fixed this downfall of the current system?

**Comment by gabizou** [comment]
> @gabizou Has the cause tracking refactor fixed this downfall of the current system?

If you were to explain to me how to test this in game, then I can verify whether it was fixed or not.

**Comment by simon816** [comment]
```java
            World world = player.getWorld();
            Optional<Entity> optItem = world.createEntity(EntityTypes.ITEM, player.getLocation().getPosition().add(1, 1, 1));
            if (optItem.isPresent()) {
                Item item = (Item) optItem.get();
                world.spawnEntity(item, Cause.source(this).build());
                System.out.println("Should be true: " + world.getEntity(item.getUniqueId()).isPresent());
                Sponge.getCommandManager().process(Sponge.getServer().getConsole(), "msg");
                System.out.println("Should be true: " + world.getEntity(item.getUniqueId()).isPresent());
            }
```
Current output:
```
Should be true: false
Usage: /tell <player> <private message ...>
Should be true: true
```

**Comment by Zidane** [comment]
This issue should be resolved now that entities are now spawned on calling spawnEntity.
