### ISSUE TITLE
[1.9] Upgrade Jar and world gets overwritten

### ISSUE THREAD

**Issue by jmiahman** [SpongePowered/SpongeCommon#671]
If I update the Server Jar the previous world gets over written. Let me know if you need logs etc..

**Comment by gabizou** [comment]
@Zidane I thought I wasn't going crazy last night when I said that it generated a new world...

**Comment by Zidane** [comment]
Pass me a log if you can. This is quite strange.

**Comment by jmiahman** [comment]
Here's a link to the log..

http://theloveoflinux.com/latest.log

**Comment by jmiahman** [comment]
Is this the fix to this issue? Would you like me to test?

https://github.com/SpongePowered/SpongeCommon/commit/ead30fd4e812b1551bf73ebcbe4344201f4ea7ae

**Comment by Zidane** [comment]
That shouldn't be it, it only affects migrating old worlds over to us.

I'll investigate this further. Btw, the link to your log does not work for me.

**Comment by jmiahman** [comment]
I just reset the server, should work now

**Comment by jmiahman** [comment]
Looks like with the latest Bleeding builds I have done this is fixed. So I am closing out this ticket. Thanks
