### ISSUE TITLE
[1.9] Can not place water with bucket

### ISSUE THREAD

**Issue by jmiahman** [SpongePowered/SpongeCommon#672]
Using a water bucket I am unable to place water. Once I right click the water will appear for second then disappear and the water bucket will still have water.

**Comment by gabizou** [comment]
Are you doing this in the spawn safe area?

**Comment by jmiahman** [comment]
Nope, that's the same thing I told my son when he reported it to me. I tested it out, along with being able to break and place other blocks just fine in the same area. I'll try Lava as well.

**Comment by jmiahman** [comment]
Lava has the same behavior. I also made sure I removed Essentials, that I was testing just in case there was something with it that was preventing placement and still got the same results.

**Comment by Minecrell** [comment]
Working fine for me.

**Comment by gabizou** [comment]
Is everything checked out to latest 1.9?

**Comment by jmiahman** [comment]
Latest as in about 2-3 hours ago, I can rebuild though and start fresh, not an issue.

**Comment by jmiahman** [comment]
I rebuilt the 1.9 and I am still getting the same issues. Here's the log if it will be of any help. Thanks

http://theloveoflinux.com/latest.log

**Comment by jmiahman** [comment]
This seems to be fixed for me with the latest bleeding builds. So I am closing.
