### ISSUE TITLE
BlockChange not persistent when hitbox can be seen

### ISSUE THREAD

**Issue by clucky** [SpongePowered/SpongeCommon#674]
I am attempting to send a block change to a player via `Viewer#sendBlockChange(...)`. My issue is, if this method is called during an InteractBlockEvent which is cancelled afterwards, and the player can see a hitbox for the block on their end, the block change is immediately undone. I am using BlockRay to retrieve the block instead of InteractBlockEvent's target block, and it works perfectly fine for blocks far away. A vague snippet of my code can be viewed below.

The expected result of this would be for the server to not reset the block for the player, being the interact event is cancelled.

**Example:**
````
public void onInteractSecondary(InteractBlockEvent.secondary event, @Root Player player) {
    ...
    BlockRay<World> blockRay = BlockRay.from(player).filter(BlockRay.continueAfterFilter(BlockRay.onlyAirFilter(),1)).blockLimit(100).build();
				
    Optional<BlockRayHit<World>> hitBlock = blockRay.end();
    if (hitBlock.isPresent()) {
        player.sendBlockChange(...);
        event.setCancelled(true);
    }
}
````

**Comment by gabizou** [comment]
I'm guessing you understand why this happens, right? I didn't realize this was opened until you closed it an hour ago (go go mass notifications on github).

**Comment by clucky** [comment]
Yeah @gabizou , Blood explained why it occurs to me in IRC. It's because Sponge must resubmit the BlockState to the client upon interaction, due to the fact that a mod may have changed it. I, with blood's help, resolved the issue by scheduling the "fake block" to appear 2 ticks after the event occurs.
