### ISSUE TITLE
Add support for per-world maps

### ISSUE THREAD

**Issue by kashike** [SpongePowered/SpongeCommon#686]
`MixinItemEmptyMap`, `MixinItemMap` use dimension id `0` (overworld) for all maps. It should save map data in each world's specific data dir

**Comment by bloodmc** [comment]
@simon816 please look into this.

**Comment by modwizcode** [comment]
I have to comment, having spent extensive time working on the map API implementation. This would be a difficult change to handle. Before maps id's used the overworld (id `0`) provider, I was unable to find a reasonable implementation of the API without leaking through to implementation.

 Considering that players likely might want to display maps from the overworld in the nether and end and all possibilities of those, which is fully supported in vanilla (unless something changed), I think this would be a breaking change too.

**Comment by kashike** [comment]
@modwizcode This is changing vanilla and/or forge behaviour. If I have tons of temporary worlds, my main world's data directory could contain hundreds, if not thousands, of unused maps that I'm unable to clear because I don't know where they come from.

**Comment by modwizcode** [comment]
They have a dimension id attached to them which represents the world they should go with. Maps are only connected to an `ItemStack` through their damage value. The map id's have to be compatible, because that's how vanilla works. This means that to find the `MapView` (some API representation of the map data) I would have to know where to load it. Given any vanilla itemstack their should be no contention of where the map is located and how to load it. I don't have any reference to a World to request a `MapStorage` from which is what we currently mixin to in order to prevent this problem. Otherwise maps created on one world will become different maps when teleported to another world.

**Comment by kashike** [comment]
Solve this issue:
>If I have tons of temporary worlds, my main world's data directory could contain hundreds, if not thousands, of unused maps that I'm unable to clear because I don't know where they come from.

**Comment by simon816** [comment]
How about a mapping that relates MapID to a World.
Something like `World getWorldForMapId(int map)`
When a world is first loaded, it looks for `data/map*.dat` files and hands the IDs it knows about to this mapping (perhaps stored in `DimensionManager` or similar)

**Comment by kashike** [comment]
@simon816 What?

**Comment by simon816** [comment]
I was thinking of a way to lookup what world-specific data file a map's damage value relates to. Maybe I've missed something here

**Comment by modwizcode** [comment]
I don't understand your thousand of map files example. That seems like an unlikely case, map files aren't created per-dimension unless someone wants a map. If a dimension is deleted, then go through and delete any stored maps with that dimId

**Comment by kashike** [comment]
@modwizcode The point is that the dimension id is **not** in the file name. The file name is `map_{map id}.dat`

**Comment by modwizcode** [comment]
It's stored in the file... So it's not hard to go through and check.

**Comment by bloodmc** [comment]
@modwizcode Why do you need a reference to the world to request mapstorage? You can load it yourself if you know the dimension id which would give you enough information to find the path to the file.

**Comment by modwizcode** [comment]
Unfortunately I can't remember. I think it was related to creating the map.
Which should that be a method on World now?
