### ISSUE TITLE
Possibility of having a single ItemStack to merge for larger than normal item stacks on the ground

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#688]
For excessively large amounts of `Item` entities being spawned when chests are broken (think about having over 10k cobblestone worth of items) on the ground, there's a lot of lag that ensues for clients, and usually some minor server degradation due to the excessive requests to merge the entities. It would be feasible to _merge_ the items into one super item entity such that nearby players would still be unable to pick up more than the max stack size, but the entity would be perfectly safe to treat as the merged result, and heavily reduces lag all around.

This is more of a thought that I've had for a while to implement but never bothered.

**Comment by kashike** [comment]
I'm assuming this would be a disableable optimisation mixin?

**Comment by gabizou** [comment]
It would be disabled by default I'd imagine as people would be complaining about it being "broken" ;)

**Comment by Zidane** [comment]
Closing as we're looking into removing item-stack merging as it causes way too many headaches than it fixes.
