### ISSUE TITLE
master won't build.. 

### ISSUE THREAD

**Issue by jmiahman** [SpongePowered/SpongeCommon#697]
It seems master is broken and won't build.. Not sure if that's an issue or not..

http://paste.fedoraproject.org/362249/46230090/

**Comment by simon816** [comment]
It seems like you haven't setup the required workspace.
If you only need to build the project then run `gradle setupCIWorkspace`, for development, run `gradle setupDecompWorkspace`
After that, `gradle build` should work

**Comment by jmiahman** [comment]
Oh, sorry. I didn't have to do that with the 1.9 version for some reason. I'll try it with master.
