### ISSUE TITLE
Split join and leave messages into header, body, footer

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#698]
![image](https://cloud.githubusercontent.com/assets/141554/14994396/ea2bbc12-11ae-11e6-85eb-61ddf2038582.png)

```
private static final String CHANNEL_ARG = "TeamChannel";
    private static final TextTemplate TEMPLATE = TextTemplate.of(
            arg(CHANNEL_ARG)
    );

    @Listener
    public void onChat(final MessageChannelEvent event, @First final Player player){
        final SimpleTextFormatter header = event.getFormatter().getHeader();
        final SimpleTextTemplateApplier stta = new SimpleTextTemplateApplier(TEMPLATE);
        stta.setParameter(CHANNEL_ARG, "DEAD");
        header.insert(0, stta);
        final SimpleTextFormatter body = event.getFormatter().getBody();
        body.insert(0, stta);
        final SimpleTextFormatter footer = event.getFormatter().getFooter();
        footer.insert(0, stta);
```

**Comment by Aaron1011** [comment]
Is this a feature request?

**Comment by ryantheleach** [comment]
I'm not sure if it's a bug or a feature request. Just observed the behaviour and it didn't look right.

If it's working as intended due to the way that the translatable message works, then I guess close, but if it's possible to fix I'd like to see it fixed.

**Comment by kashike** [comment]
@ryantheleach What is the desired output?

**Comment by ryantheleach** [comment]
I would have expected the join / leave message to be 

DEADPlayer933 DEADJoined the game.DEAD 

After reading the documentation. and seeing what chat messages look like.

**Comment by kashike** [comment]
The `Player933 joined the game` part is translated on the client, not the server

**Comment by ryantheleach** [comment]
Yes, but isn't the Player933 a variable / child that can be manipulated?

Could that not be considered the header?

**Comment by kashike** [comment]
`<header><body><footer>`

`<DEAD><DEADPlayer933 joined the game><DEAD>`

**Comment by windy1** [comment]
@ryantheleach 

This is the correct result. The first message has an empty header which is why you're seeing that duplicate there. Parsing messages into head/body is currently only with chat messages, unless it is set explicitly. 

Now what you *could* do is parse the body yourself by removing the part you want as the header from the body and adding it to the header. Consequentially, any plugins that deal with this message afterwards will now have your "custom" header.

**Comment by ryantheleach** [comment]
My understanding is that for join messages it's impossible to make the player name the header without changing the implementation, as it would no longer be a child of the join message translation text.

If this is working as intended there is no feasible way to fix it, and remain compatible with translations.

**Comment by windy1** [comment]
Well if you would like to maintain the compatibility with translations you could try using the join message translation with an empty player argument and then just put the player in the header.
