### ISSUE TITLE
Inventory implementation

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeCommon#70]
I'm not entirely sure that I'm missing something that's been worked on already. But I started trying to implement recipes and realized before I could do that I needed to convert between sponge and vanilla inventory types. Then I discovered that the Inventory has no implementation that I can see.

I would assume someone is already working on this and I wanted to let them show that before I work too much on my hack job of a inventory implementation.

**Comment by me4502** [comment]
@Mumfrey Is working on this

**Comment by simon816** [comment]
@Mumfrey is working on inventory implementation. 
I worked on recipes a bit (experimental). FWIW here's the branch https://github.com/SpongePowered/SpongeCommon/compare/master...simon816:recipe-impl

**Comment by modwizcode** [comment]
Ah excellent thanks. Can someone get this into the milestone that makes sense?
