### ISSUE TITLE
[1.8] EOFException : null @ java.io.DataInputStream:-1 upon sendTo through "BungeeCord" RawDataChannel

### ISSUE THREAD

**Issue by Rhonim** [SpongePowered/SpongeCommon#700]
Currently when trying to do, for example:
```
ChannelBinding.RawDataChannel bungeeChannel = Sponge.getChannelRegistrar().createRawChannel(this, "BungeeCord");

...

bungeeChannel.sendTo(player, channelBuf -> {
                channelBuf.writeString("Connect");
                channelBuf.writeString("destinationServer");
            });

```
the player gets a EOFException : null @ java.io.DataInputStream:-1 and is disconnected from bungee, and never send to the correct server.

**Comment by Deamon5550** [comment]
The issue was a difference between how our ChannelBuf was writing strings (varint followed by data) and how bungeecord tries to read them (short followed by data). I'm writing a fix now.
