### ISSUE TITLE
Pagination breaks with special utf 8 characters

### ISSUE THREAD

**Issue by kinggoesgaming** [SpongePowered/SpongeCommon#708]
For example: any utf8 characters located here -> http://www.utf8-chartable.de/unicode-utf8-table.pl?start=9600&number=128

I have only tested the breakage with the padding. It might not be broken for the header, footer, contents etc...

example image with a `\U25A1` or `□` shows this: https://usercontent.irccloud-cdn.com/file/M9qGA6sy/fixxy.png

however using `|_` works fine, whether i use utf or normal characters: https://usercontent.irccloud-cdn.com/file/BBWMkCx4/betty.png

**Comment by Zidane** [comment]
@ryantheleach 

Can you look into this?

**Comment by ryantheleach** [comment]
I'm chalking this down to a Minecraft bug...
![image](https://cloud.githubusercontent.com/assets/141554/16080419/e3e02ca2-3347-11e6-9920-6b708bfe2496.png)

**Comment by ryantheleach** [comment]
j and k are supposed to represent the starting column and ending column for the variable width bitmap glyphs.
