### ISSUE TITLE
Retrieving Sponge Common from a Repo

### ISSUE THREAD

**Issue by WhippyCleric** [SpongePowered/SpongeCommon#71]
Hi

I am aware this is not really an issue and as such does not belong here but can't find anywhere else to currently ask these types of questions. I am trying to use the ItemStackBuilder implementation from sponge common but I can't find the jar in a repo anywhere. Is there a different repo than the one which contains the API that contains sponge common somewhere I can reference in my pom?

Thanks

**Comment by RobertHerhold** [comment]
You shouldn't be using any classes specific to an implementation. You can access the ItemStackBuilder [from the GameRegistry](https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/GameRegistry.java#L139).

**Comment by WhippyCleric** [comment]
Thanks for the advice, I will try to create an account on Esper for future queries. Issue can be closes now
