### ISSUE TITLE
TextColor has wrong hex value

### ISSUE THREAD

**Issue by ewized** [SpongePowered/SpongeCommon#719]
Acording to: http://minecraft.gamepedia.com/Formatting_codes `AQUA` should be `0x55FFFF` but in https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/registry/type/text/TextColorRegistryModule.java#L73 it is set to `0x00FFFF`.

**Comment by kashike** [comment]
...and re-fixed in https://github.com/SpongePowered/SpongeCommon/commit/c25b4b42a2d36f47ce7e82d1e6f73e006f0affa3.
