### ISSUE TITLE
Prevent Block ticking on edge chunks

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#725]
Traditionally, in Vanilla Minecraft, all blocks of all loaded chunks will have a chance to tick. The unfortunate side effect of this is that there are corner cases where certain blocks (like liquids) will end up ticking and causing random chunk loads/generations because they are simply at the edge of the loaded chunk range. 

In previous server mods, it was common practice to prevent the edge chunks from even considering to tick blocks and entities (CraftBukkit did this and to a greater extent, Spigot does this).

The question though is when in certain circumstances some mods (or to an extent redstone machines rely on this) may rely on neighbor chunk loads to successfully function.

So, I ask:

If there are some general arguments that will suffice to say that neighbor chunk loading during a block tick should still function and cause the ensuing *prevention of edge chunk block ticking* to be ignored **OR** just go ahead and mainline the prevention of edge chunk block ticking to be suppressed.

**Comment by Zidane** [comment]
My biggest thing about Sponge and how its different than the other mod platforms is that we do NOT break Vanilla gameplay, whatsoever.

If this breaks Vanilla redstone gameplay then I think the path is clear.

**Comment by Zidane** [comment]
That being said, that doesn't prevent a mixin config toggle (in the optimizations plugin) for those admins who simply don't care about that functionality working.

**Comment by modwizcode** [comment]
Couldn't this even be done on a per-world level? That would allow servers with a specific world for redstone to optimize the rest of the worlds.

**Comment by bloodmc** [comment]
This has been done in commit

https://github.com/SpongePowered/SpongeCommon/commit/a66367c4d9067b5fcc0c087139aa6e5dccf9376f

I'll handle any issues as they come up.
