### ISSUE TITLE
Items dropped by players have the incorrect spawn cause

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#728]
Currently when a player drops an item, the spawned item has a spawn cause of the Player object, rather than an EntitySpawnCause, which is not consistent with other item spawns triggered by entities.

Edit: This is within the SpawnEntityEvent.

**Comment by bloodmc** [comment]
@DarkArc Drops an item how? I need more info. Are you pressing Q? are you dying?

**Comment by DarkArc** [comment]
Open the inventory, pick up an item, and click outside the GUI to drop the item. I think it's the same thing for the drop key.

---- On Wed, 18 May 2016 09:40:49 -0700 notifications@github.com wrote ----

@DarkArc Drops an item how? I need more info. Are you pressing Q? are you dying?
