### ISSUE TITLE
Explosions still drop blocks with canBreakBlocks off

### ISSUE THREAD

**Issue by modwizcode** [SpongePowered/SpongeCommon#729]
I've been attempting to manually handle rebuilding explosion damage by disabling the explosion's ability to break blocks. Unfortunately this still results in blocks being dropped. While I can manually clean these blocks up, I don't think they should be present after block drops are disabled.

**Comment by modwizcode** [comment]
What this comes down to is that in `MixinExplosion` we cancel the `explosionA` method which does the break. And `explosionB` which handles the sound and block drops is ignored. Either this should also be ignored with `canBreakBlocks` off or we need more options for controlling an explosion. I'm willing to contribute either fix.

**Comment by Zidane** [comment]
Re-test with stable-5 and reply back if still an issue. We'll re-open in the event that it is.
