### ISSUE TITLE
Associate Explosion Creation causes

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#731]
It should be feasible for any time an `Explosion` is created (not through the API), for the `CauseTracker` to construct a cause for the explosion. I can work on the 1.9 version of getting that done, but I believe @bloodmc would know the most to get that implemented in 1.8.9.

**Comment by modwizcode** [comment]
Thanks for creating this, I think you could probably pass it for some of the sub-events like `ExplosionEvent.Detonate` if you set it during the course of processing the explosion.

**Comment by modwizcode** [comment]
See https://github.com/SpongePowered/SpongeCommon/issues/732

**Comment by ryantheleach** [comment]
With https://github.com/SpongePowered/SpongeCommon/issues/732 closed and the Cause Tracker going through several revisions, I'm confident that this issue is also closed.
