### ISSUE TITLE
Error PotionEffectType getID

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#735]
Hi,
In this class "PotionEffectType", the functions getID and getName return the same value.
Example : 
PotionEffectTypes.HEALTH_BOOST return effect.healthBoost

The function getID should be return minecraft:health_boost

**Comment by rexbut** [comment]
Problem solved in commit : https://github.com/SpongePowered/SpongeCommon/commit/71879db08dad1b022041f360c4c01627622e6be8
