### ISSUE TITLE
Remove separation of logic in core mixins

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#736]
@gabizou

The strategy where core logic is separated across several _ mixins (for example, MixinWorld_Effect) is not working out. I REALLY do not like it as I need to open several of these mixins just to see what code Sponge is applying. I literally see no advantage: whoever wants the separation can utilize comments to say what goes where. This separation itself caused me to miss the code from Effect's init which is currently causing the implementation to crash on setting weather.

It makes sense for Mixin plugins but I want the core logic reverted back to one.

**Comment by bloodmc** [comment]
I agree considering this has burned me in the past as well. The code is more readable when everything is within the same file. Instead of having a separate file, we can just use a comment to separate sections of code.

**Comment by Zidane** [comment]
I've done this in master but not completely:

Tracker and Effect have been merged back into World/WorldServer. @gabizou you can clean up my work/change it as you see fit.
