### ISSUE TITLE
Weird Behavior When Using Bolded Titles With PaginationList

### ISSUE THREAD

**Issue by kmecpp** [SpongePowered/SpongeCommon#744]
The bottom of the PaginationList page has an extra character when using a bolded title, tested with the text "Command List" and got this result.

![](http://img.prntscr.com/img?url=http://i.imgur.com/1xARlAq.png)

Code I'm using to create the page:

```
PaginationList.Builder page = Sponge.getServiceManager().provide(PaginationService.class).get().builder();
page.title(Text.of(TextColors.AQUA, TextStyles.BOLD, "Command List");
page.linesPerPage(10);
page.contents(lines);
page.padding(Text.of("-"));
page.sendTo(src);
```

**Comment by Zidane** [comment]
@ryantheleach 

Can you look into this?
