### ISSUE TITLE
[1.9.4] Some right-click interactions broken

### ISSUE THREAD

**Issue by phroa** [SpongePowered/SpongeCommon#745]
Can't place anything while sneaking: the block instantly disappears, count in hotbar decreases, but updates if the stack is moved around in the inventory.

Buckets fire twice, such that you can't place or remove water or lava unless there is a block **behind** the block in question that can be interacted with (crafting table, furnace, other water or lava source).

```
[17:49:32 INFO]: SpongeVanilla
    Minecraft: 1.9.4
    SpongeAPI: 5.0.0-SNAPSHOT-bace84e
    SpongeVanilla: 1.9.4-5.0.0-BETA-0
```

Vanilla client. Video: https://github.com/SpongePowered/SpongeVanilla/files/280809/2016-05-24.18-10-40.zip

**Comment by gabizou** [comment]
Closed with https://github.com/SpongePowered/SpongeCommon/commit/9a2dbba2be4b6ed07154bcac9bd09daf505fb123
