### ISSUE TITLE
Prepend padding for Pagination instead of append.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#748]
Appending the padding on pagination can lead to bad User Experience.

When connected remotely, text being sent does not "focus" the pagination meaning that you can end up with a chat only full of padding, and not seeing the content.

By prepending the padding, the user will at least see the text, and get the idea that more could be seen if chat is given focus.

![image](https://cloud.githubusercontent.com/assets/141554/15554161/d7d53728-2301-11e6-8086-273d0333f28f.png)

**Comment by Zidane** [comment]
@ryantheleach 

Is this resolved? If not, PR a resolution.

**Comment by ryantheleach** [comment]
Will do.
