### ISSUE TITLE
[1.9.4] Connection lost when picking up item

### ISSUE THREAD

**Issue by cindylo** [SpongePowered/SpongeCommon#749]
Whenever a player picks an item up at all in creative or survival on SpongeVanilla bleeding build 30 or 31 it throws this error and kicks them out of the server with internal server error and this error server side. http://pastie.org/10854233

**Comment by JBYoshi** [comment]
Could you split this into two separate issues?

**Comment by cindylo** [comment]
Absolutely

**Comment by gabizou** [comment]
This no longer is an issue for a couple of days.
