### ISSUE TITLE
[1.9.4] Entity spawn cause -- needs two root objects

### ISSUE THREAD

**Issue by phroa** [SpongePowered/SpongeCommon#754]
Depending on what object is the root of the cause in `EntityUniverse#spawnEntities(Iterable, Cause)` (and likely other methods), it either throws
```
java.lang.IllegalArgumentException: PluginContainer must be at the ROOT of a cause!
```
or
```
java.lang.IllegalArgumentException: SpawnEntityEvent MUST have a SpawnCause as the root!
```

This is a fresh bug in 1.9 according to blood.

**Comment by gabizou** [comment]
Closed with https://github.com/SpongePowered/SpongeCommon/commit/610cbc6e66310fb63ffce71bd9393bad6bab02a9
