### ISSUE TITLE
Players can leave their beds and walk around

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#755]
When using a bed (potentially only in a created multi-world environment) players are not put into the normal sleeping state, instead they can continue to walk around, while being classified as in a bed. They can continue to interact with objects within a range, however, they will look like they're standing on their bed.

**Comment by gabizou** [comment]
1.8.9 or 1.9?

**Comment by DarkArc** [comment]
1.8.9

---- On Sat, 28 May 2016 18:18:37 -0700 notifications@github.com wrote ----

1.8.9 or 1.9?

**Comment by bloodmc** [comment]
@DarkArc Can you test older builds to see if this is a new bug as well as test with no other mods or plugins.

Thanks

**Comment by DarkArc** [comment]
I'll test around a bit now, also wanted to make note:

This also appears to affect the setting of RespawnLocationData in the Data API -- I hadn't tried to use it until today, #8 says it is implemented however.

**Comment by DarkArc** [comment]
The culprit is SpongeForge on the client, it broke way back in build spongeforge-1.8.9-1694-3.1.0-BETA-1081.
