### ISSUE TITLE
[1.9.4] CollideEntityEvent not firing for boats

### ISSUE THREAD

**Issue by Grinch** [SpongePowered/SpongeCommon#757]
Works in 1.8.9 SpongeVanilla. Doesn't work in 1.9 SpongeVanilla, Haven't tested 1.8.9 SpongeForge.

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/0e095e3c796279bf2e2d448b9455456a8ac0a0d6.
