### ISSUE TITLE
Command block teleport cast error

### ISSUE THREAD

**Issue by chrismack** [SpongePowered/SpongeCommon#759]
When running this command "tp @a[m=2,r=70] 1570 109 1484" Sponge vanilla throws out a class cast exception. 

Error can be found [here](https://gist.github.com/chrismack/b6cc2a9a56593bd50b6dc9ed52bd97af)
you also get the cast exception when using the command tp @a 1570 109 1484

This was tested on sponge vanilla the latest version as of 01/06/2016 (I haven't had a chance to test on sponge forge but i'm just presuming it will be a common issue)

**Comment by Zidane** [comment]
@chrismack 

Thanks for report. Closed in https://github.com/SpongePowered/SpongeVanilla

**Comment by chrismack** [comment]
@Zidane The error doesn't show but the command doesn't teleport any players
