### ISSUE TITLE
[1.8.9] Dropping items = non-SpawnCause root cause (sometimes)

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#763]
the Cause for SpawnEntityEvent is always supposed to be a SpawnCause object, but in the case of dropping an item, it  is a spawncause if you drag-drop an item out of your inventory screen.

But if you throw an item away with the keyboard drop-key with just the normal hotbar display, the cause isn't caught as a dropped-item:

```
   @Listener
    public void s1(SpawnEntityEvent event) {       
        SpawnCause sc;
        if (event.getCause().root() instanceof SpawnCause) {
            sc = (SpawnCause) event.getCause().root();
        } else {
            System.out.println("The system has a spawn cause root that isnt a spawncause: " + event.getCause().root());
            return;
        }
```
results in:

> The system has a spawn cause root that isnt a spawncause: EntityPlayerMP['BooMod'/134, l='world', x=-41.06, y=67.00, z=267.81]

======
System:  Forge 1.8.9, 1890  SpongeForge 1890-4.1.0-1378 ; api 4.1.0 -51  ZERO client or server Forgemods other than sponge and testplugin

**Comment by bloodmc** [comment]
Fixed in commits https://github.com/SpongePowered/SpongeCommon/commit/8eca553ee8592c67a390d351dbf90306c87b92dc

and

https://github.com/SpongePowered/SpongeCommon/commit/09962ddfd0b2a90ea9f0771ffcda047b11e83ddc
