### ISSUE TITLE
Error DestructEntityEvent Beta 43 [1.9.4] Sponge Vanilla

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#764]
Hi,
the event DestructEntityEvent is launched two times for mobs.
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/tracking/phase/function/PacketFunction.java line 131
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java line 233

**Comment by lesbleu** [comment]
And this event is lauched in every hit on player

**Comment by rexbut** [comment]
Problem solved in 1.9.4-5.0.0-BETA-65

Commit : https://github.com/SpongePowered/SpongeVanilla/commit/9533927767a609fad944344fb813229dc65265ad
