### ISSUE TITLE
BlockTypes are not present in the registry

### ISSUE THREAD

**Issue by Deamon5550** [SpongePowered/SpongeCommon#77]
As seen here [in the registry](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java#L521) BlockTypes are currently not able to be fetched from the GameRegistry.

This issue is blocking the completion of VoxelSniper which we would like for Minecon.

**Comment by ST-DDT** [comment]
Wasn't there a PR with a very long list of block states?
https://github.com/SpongePowered/SpongeAPI/pull/725#issuecomment-111794367
I guess we can use that code to initially fill the map.
But there is still the issue with updating the map. How do we trigger the update?

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/a54ccacee333283dc1579598812ded138980a8a5
