### ISSUE TITLE
[1.9.4] Setting populator objects do not cause chunk refresh

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#770]
Hi, 
when i use the functions placeObject for place a PopulatorObjects. The chunck is not uploaded but the server considered they are a tree.

**Comment by Aaron1011** [comment]
@lesbleu: I'm not quite sure what your issue is. Are you getting an exception when calling a method, or is  someone not functioning properly?

**Comment by rexbut** [comment]
When using this code :
```
if(PopulatorObjects.BIRCH.canPlaceAt(player.getWorld(), block.getX(), block.getY(), block.getZ())) {
	PopulatorObjects.BIRCH.placeObject(player.getWorld(), player.getRandom(), block.getX(), block.getY(), block.getZ());
	return true;
} else {
	player.sendMessage(EEMessages.PREFIX.get() + EEMessages.TREE_NO_CAN.get());
}
```
The tree is added to the world but the player does not see it. It must disconnect and connect to view it.

**Comment by Deamon5550** [comment]
Its probably because the PopulatorObjects are backed by the actual AbstractTree populators from the base game which usually run without sending updates, I can mix in a toggle used by the implementation when actually using them for world gen and let it send the updates for normal uses.

**Comment by lesbleu** [comment]
Fixed on SpongeVanilla Beta-112
