### ISSUE TITLE
Cannot tame Horse in Plugin

### ISSUE THREAD

**Issue by Faithcaio** [SpongePowered/SpongeCommon#773]
```java
horse.offer(Keys.TAMED_OWNER, Optional.of(playerUUID));
```
is not working because the Manipulator is restricted to `EntityTameable` but `EntityHorse` does not extend it

**Comment by gabizou** [comment]
@Faithcaio What this would require is simply providing a new data processor specifically written for horses (since they don't extend `EntityTameable`). If you feel like writing one, might be faster than when I get time to writing one.
