### ISSUE TITLE
removeFirst

### ISSUE THREAD

**Issue by KumaGetsu** [SpongePowered/SpongeCommon#774]
@bloodmc Using SpongeForge 1890, hasn't crashed for a couple days until now. Another removeFirst crash.

Crash-report:
http://paste.ubuntu.com/17047123/

**Comment by KumaGetsu** [comment]
Had these two crash-reports from earlier in the day which never actually crashed the server.

http://paste.ubuntu.com/17047167/
http://paste.ubuntu.com/17047149/

**Comment by gabizou** [comment]
Update SpongeForge please.

**Comment by gabizou** [comment]
I take it back, @bloodmc confirmed it still may be an issue in the latest builds.

**Comment by bloodmc** [comment]
@KumaGetsu try this build

https://www.dropbox.com/s/er1k8b0mgui7e2b/spongeforge-1.8.9-1890-4.2.0-BETA-0.jar?dl=0

I added some debug, paste the stack trace when you see it in logs.

**Comment by bloodmc** [comment]
This is no longer an issue in latest builds.
