### ISSUE TITLE
XP, food level, and other player information not sent on world change

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#777]
When a player changes worlds their status items do not update to show the correct XP, health, or food levels.

**Comment by simon816** [comment]
Been an issue on SpongeVanilla for several months https://github.com/SpongePowered/SpongeVanilla/issues/218

**Comment by gabizou** [comment]
@bloodmc When you get a chance, can you look into resolving this?

**Comment by Zidane** [comment]
Not the best pictures as a I had a skeleton after me (and through the portal even!) but: 

http://imgur.com/a/d801l

Stats updating just fine here on latest SpongeForge master. If you can present a case where it isn't working Dark_Arc, I'll reopen.

**Comment by DarkArc** [comment]
Uh, I don't know if it was ever a problem with portals. Try setting your location to a point in the nether/a custom world via `setLocation`.

I haven't checked in a few days, I'll comment again when I have gotten the chance.
