### ISSUE TITLE
Old global.conf makes /sponge timings fail

### ISSUE THREAD

**Issue by Inscrutable** [SpongePowered/SpongeCommon#779]
After recent updates to the 1.9.4 SpongeVanilla Test server (probably from Beta-37 to Beta-52), the ``/sponge timings`` commands failed to perform as expected (unable to toggle timings or verbose mode on or off, can't get a report), console just repeatedly demanding that timings be turned on. Changing timings to true in the file and using ``/sponge reload -g`` did not help either.
This was fixed as follows: I removed the global.conf and let it regenerate, and suddenly ``/sponge timings on`` works again. There seem to be two places to enable timings in the old global.conf. Here's the [old global.conf file](https://dl.dropboxusercontent.com/u/81927080/OLDglobal.conf) for reference.

**Comment by gabizou** [comment]
@zml2008 you said at one point it's possible to perform upgrades on old configs? We may need to perform such upgrades for bleeding.

**Comment by zml2008** [comment]
Yeah, example of usage in PEX:

Declaring the transformation: https://github.com/PEXPlugins/PermissionsEx/blob/master/permissionsex-core/src/main/java/ninja/leaping/permissionsex/config/ConfigTransformations.java#L51

Applying it: https://github.com/PEXPlugins/PermissionsEx/blob/master/permissionsex-core/src/main/java/ninja/leaping/permissionsex/config/FilePermissionsExConfiguration.java#L70

**Comment by gabizou** [comment]
@zml2008 so we should be versioning our configs for this to work?

**Comment by zml2008** [comment]
Yeah -- generally initial version is considered -1 and counting starts at 0 which is the first transformation.

**Comment by Inscrutable** [comment]
The first line header comment on the old config reads ``1.0``, so that might be a good place to start.

**Comment by Zidane** [comment]
@SpongePowered/developers 

I'm closing this but with some notes:

* When config changes happen in the future, BUMP THE VERSION.
* The commit message in-which config changes occurs, decorate it accordingly! Example: "Bump config to 2.0 for per world pig spawns".
