### ISSUE TITLE
[1.9.4] NPE client crash with Botania "Key of the King's Law"

### ISSUE THREAD

**Issue by klangg** [SpongePowered/SpongeCommon#786]
Reproduce:
forge-1.9.4 - 12.17.0.1954
spongeforge-1.9.4-1954-5.0.0-BETA-1418
Botania-unofficial.r1.8-308
Baubles-1.9.4-1.2.1.0 (required by Botania)

Obtain a Key of the King's Law and a Mana Tablet
Hold down the Use Item button (right mouse), with the Key in hand, until it is drawn back like a bow being fired.
Some projectiles will be fired that will explode on contact with any entity or block.
A collision results in an explosion that damages entities but not blocks.
Upon exploding all clients that can view the event have a client crash.

[Client crash report, client log, and server log](https://gist.github.com/klangg/257c71d5ca1dd67dae5cfee6316ce459)

If the chunk does not stay loaded the client will continue to crash everytime the player reconnects.
This happens in both single- and multi- player.
If spongeforge is removed everything works as intended.

Please let me know if you want more data or if a Botania bug report is needed.

Thanks!

**Comment by Aaron1011** [comment]
@klangg: Where can I download Botania for 1.9?

**Comment by JBYoshi** [comment]
@Aaron1011 https://github.com/williewillus/Botania/releases

**Comment by Aaron1011** [comment]
Ah, I was looking https://github.com/Vazkii/Botania instead.

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeForge/commit/432f1ed75a73af911f28f5ee4ca084318abfa4cf. This issue is resolved in the latest SpongeForge.
