### ISSUE TITLE
[1.9.4] Cannot place blocks while sneaking

### ISSUE THREAD

**Issue by klangg** [SpongePowered/SpongeCommon#787]
When using forge-1.9.4-12.17.0.1954 and spongeforge-1.9.4-1954-5.0.0-BETA-1418 blocks cannot be placed while sneaking. The block appears for a brief moment then disappears. This happens in both single- and multi- player. This works properly with a vanilla client connecting to a spongevanilla-1.9.4-5.0.0-BETA-62 server.

Please let me know if you want more data.

Thanks!

**Comment by gabizou** [comment]
@Aaron1011 did you say you fixed this?

**Comment by gabizou** [comment]
This was fixed in https://github.com/SpongePowered/SpongeForge/commit/2ef1f05a08a1186cd0c5aad696e8716c50125091
