### ISSUE TITLE
Selector parsing produces unexpected results

### ISSUE THREAD

**Issue by Kippers37** [SpongePowered/SpongeCommon#791]
I'm on the most recent commit on the master branch (a628b741b1f3c169db0f676ccccfbb062b1b289a, which I think equals to 4.2.0-BETA-1425) of SpongeForge.

I'm using:
`Set<Entity> entities = Selector.parse(value).resolve(commandSource);`

But this is not producing the results I expect:

**Nearest player selector @p, Kippers standing closer:**
entities = {RegularImmutableSet@9738}  size = 2
 0 = {EntityPlayerMP@9740} "EntityPlayerMP['riebie'/817, l='world', x=180.13, y=77.00, z=-0.69]"
 1 = {EntityPlayerMP@9741} "EntityPlayerMP['Kippers'/1609, l='world', x=184.66, y=76.00, z=0.51]"

**Nearest player selector @p, riebie standing closer:**
entities = {RegularImmutableSet@9831}  size = 2
 0 = {EntityPlayerMP@9792} "EntityPlayerMP['riebie'/3376, l='world', x=185.18, y=76.00, z=0.74]"
 1 = {EntityPlayerMP@9833} "EntityPlayerMP['Kippers'/3788, l='world', x=192.83, y=72.00, z=7.16]"

**Random player selector @r:**
entities = {RegularImmutableSet@9847}  size = 2
 0 = {EntityRabbit@9849} "EntityRabbit['Rabbit'/27, l='world', x=39.12, y=73.00, z=73.30]"
 1 = {EntityZombie@9850} "EntityZombie['Zombie'/4518, l='world', x=196.50, y=44.00, z=114.50]"

@kenzierocks: It seems like there's missing logic in the SelectorResolver.
https://github.com/SpongePowered/SpongeCommon/tree/master/src/main/java/org/spongepowered/common/text/selector

For anyone not familiar with selectors:
http://minecraft.gamepedia.com/Commands#Target_selector_variables

**Comment by kenzierocks** [comment]
Not missing logic, incorrect logic. [This line](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/text/selector/SelectorResolver.java#L367) should be `count >=` instead of `count >`. I'm going to PR a fix for this as well as some cleanup for the selector code.

**Comment by kenzierocks** [comment]
PRs made targeting `bleeding` due to some API changes.

**Comment by Zidane** [comment]
Closing as PR has been made.
