### ISSUE TITLE
Offering potion data to player has to be delayed after RespawnPlayerEvent

### ISSUE THREAD

**Issue by randombyte-developer** [SpongePowered/SpongeCommon#794]
Hello!

I have to delay offering potion data to a player to get it to work. The offering is happening in the RespawnPlayerEvent. [Here](https://forums.spongepowered.org/t/offering-data-to-a-player/13136/6?u=randombyte) is my forum topic and post about it.

Triggered code in RespawnPlayerEvent:
``` kotlin
private fun doBlindnessPunishement(player: Player, seconds: Int) {
        Sponge.getScheduler().createTaskBuilder().execute { ->
            player.getOrCreate(PotionEffectData::class.java).ifPresent {
                player.offer(it.addElement(PotionEffect.of(PotionEffectTypes.BLINDNESS, 1, seconds)))
            }
        }.delayTicks(8).submit(this)
    }
```

**Comment by Aaron1011** [comment]
This issue may be related to https://github.com/SpongePowered/SpongeCommon/issues/454.
