### ISSUE TITLE
[1.9.4] DragonPhases are weird

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#795]
There are various interactions, depending on the state of the DragonFightManager that cause some interesting loss of tracked `EnderCrystal`s. Likewise, when the dragon is respawned, the crystals are still pointing towards the center.

**Comment by Zidane** [comment]
@gabizou 

We need to get this finally resolved as its plagued us for a while...

**Comment by phit** [comment]
any progress?

**Comment by FiveEYZ** [comment]
Still unable to destroy the crystals after re-summoning the dragon.

spongeforge-1.10.2-2171-5.1.0-BETA-1992
forge-1.10.2-12.18.3.2185-universal

turns out it had nothing to do with draconic evo

**Comment by JonoColwell** [comment]
This issue is still occurring, any updates?

@gabizou?

**Comment by FiveEYZ** [comment]
only after changing gamemode to creative are you able to interact with the newly re-spawned crystals 
then anything will work to destroy them even a arrow shoot by someone in creative.

stuff done in survival wont do anything 

the dragon can still be killed and resummoned again, even if the crystals are intact if enough damage is done.

**Comment by EchoF** [comment]
Any word on this issue? It's making it impossible to kill the ender dragon on servers.

**Comment by gabizou** [comment]
Yes, it's being worked on.

**Comment by OldDogy** [comment]
any news on this ? it's been quite a while :/
