### ISSUE TITLE
[1.10.2] Block updates are performed even when notifyNeighbors is set to false

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#796]
If notifyNeighbors is set to false, blocks like torches still fall even though physics should be ignored.
https://github.com/SpongePowered/SpongeAPI/blob/master/src/main/java/org/spongepowered/api/block/BlockSnapshot.java#L123

**Comment by gabizou** [comment]
This is now changed with https://github.com/SpongePowered/SpongeAPI/pull/1315 and you should be able to restore without block physics and notifying neighbors.
