### ISSUE TITLE
[1.9.4] Loss of SpawnCause PLACEMENT for player-based ent-spawn, works in 189

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#797]
Working in 1.8.9: Spawn cause throws a SpawnTypes.PLACEMENT for player-based placing of itemframes/minecarts/armor stands, with a player-object as an additional cause.

In 1.9.4 both SpongeVanilla and SpongeForge, the same scenario only throws SpawnTypes.CUSTOM spawncause as the only cause, no way to pick up it being a player-based spawn cause or who the player is.

I've tried to find the build/commit that might have fixed this in 18..9 for reference, i will continue searching...

**Comment by theboomer** [comment]
Also noticed that SpawnCause BLOCK-SPAWN(ING?) entry, also active in 1.8.9, is no longer working - its all reverted to "Custom" without the player/blocks/etc

**Comment by gabizou** [comment]
Close in favor of #829. Keep one issue open only, don't open multiple issues regarding the same thing.
