### ISSUE TITLE
[1.9.4] Re-create EmptyChunk specifically for ChunkProviderServer when new chunks should not be generated

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#798]
EmptyChunk was removed from server sources in 1.9 due to their lack of use, however, we have a good reason to re-use them for avoiding chunk generation/loading during certain phases. This should be toggle able and @bloodmc would have to provide more details as to exactly *when* we should be using `SpongeEmptyChunk`.

**Comment by bloodmc** [comment]
Yes this is an issue in 1.9+ and I'm probably just going to PR Forge so mods can adapt then we can work from there.

**Comment by gabizou** [comment]
@bloodmc Still doesn't change the fact that we need to introduce it in SC for the sake of SV and common server side, granted, we can piggy back on the forge addition of it for the server sided addition. Just weighing options.

**Comment by bloodmc** [comment]
For SV, we would need an isEmpty method for Chunk so plugins can check that and ignore. Once that is added in API, you can just pass them SpongeEmptyChunk and mimic 1.8.9 flag overrides.

**Comment by bloodmc** [comment]
This has been resolved with a new approach in commit

https://github.com/SpongePowered/SpongeCommon/commit/a66367c4d9067b5fcc0c087139aa6e5dccf9376f
