### ISSUE TITLE
Issue logging pre-gen progress.

### ISSUE THREAD

**Issue by IBGnova** [SpongePowered/SpongeCommon#799]
Hello,
So recently I installed project worlds and project borders to try and pre-gen my world, but it seems there is an issue displaying the progress of the generation in console, or even in the server logs. I was told by the dev of these plugins that I would have to ask you guys about why it wouldn't be displaying properly.

**Comment by Zidane** [comment]
We need more information. Logs, anything. Closing until we get it.

**Comment by IBGnova** [comment]
Latest.log: http://pastebin.com/ZfrRCGiZ
Forge Log: https://www.dropbox.com/s/v72nea75y8f6nlu/fml-server-latest.log?dl=0
This is to show I ran the command: https://gyazo.com/3e4488cad91ebab6eed31c948ab65879
This is just showing it's running(I was the only player on standing still) https://gyazo.com/7cd76405c67b7786fae0d1c8dff2dbfe

**Comment by IBGnova** [comment]
I'm not sure what more info you need, It's just not sending the progress to the logs or the console.

**Comment by Zidane** [comment]
Just ran it myself. Here is my log:

https://gist.github.com/Zidane/14afb3c761e6ab0546023f50643342ec

Try removing all but ProjectBorders and try again.

**Comment by IBGnova** [comment]
...Found out what it was. Enjins EMP plugin is blocking stuff from showing in console.
