### ISSUE TITLE
[1.9.4] Drops Issues Master Ticket

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#803]
This serves as the master issue for the various drops issue so that information is consolidated. All related issues will be closed for this one.

- [x] Dropping items directly from inventory is broke if you are in **creative mode**. @gabizou this screams bad merge of blood's re-written creative inventory action logic
- [ ] Entity death drops get no velocity applied. They are dropping (which is good!) but they are just placed on the ground.
- [x] Pressing Q over a hovered item in the inventory doesn't drop it. It simply deletes it.

@LuxusDarkangel Merged your findings into here.

**Comment by gabizou** [comment]
> Dropping items directly from inventory is broke if you are in creative mode. @gabizou this screams bad merge of blood's re-written creative inventory action logic

So, further testing, Vanilla will drop items if you drop them out of the window, but pressing `Q` to drop an item from the slot inventory while in creative *will delete the item*. Which is it that is broken exactly? I'm guessing that the first is broken, but the second is something I should disagree in fixing.

**Comment by kashike** [comment]
@gabizou I disagree, if pressing `Q` deletes the item it *should* be fixed.

**Comment by Zidane** [comment]
@gabizou @kashike 

If Vanilla singleplayer behaves as @gabizou describes for the latter point, we will not be changing that functionality.

**Comment by gabizou** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/05f91e9e5819846e07d951763e1293a194056586
