### ISSUE TITLE
[1.9.4] Multiple over worlds causes time cycle flickers

### ISSUE THREAD

**Issue by gabizou** [SpongePowered/SpongeCommon#806]
Multiple over worlds existing on the server will still send time updates to clients for the main overworld of other overworld typed worlds, causing flickers of whatever time the other worlds are at with the current one. I can't grab a screenshot of it properly, but it's reproducible with WorldsTest.

**Comment by Zidane** [comment]
Actually was a SpongeVanilla issue, closed in latest builds.
