### ISSUE TITLE
Canceling a scheduler in Asyn

### ISSUE THREAD

**Issue by rexbut** [SpongePowered/SpongeCommon#813]
When you stop a task that with an interval, and sometimes it does not stop.

I realized experimental changes ScheduledTask , and I noticed that two threads can change the same time the State : 

> [01:27:38 INFO]: ScoreBoard Update (type='sidebar') 1 : setState before : RUNNING
> [01:27:38 INFO]: ScoreBoard Update (type='sidebar') 1 : setState before : RUNNING
> [01:27:38 INFO]: ScoreBoard Update (type='sidebar') 1 : setState after : CANCELED
> [01:27:38 INFO]: ScoreBoard Update (type='sidebar') 1 : setState after : SWITCHING

Which cancels the order in the task.

**Comment by Aaron1011** [comment]
@rexbut: Is this an asynchronous task, or a synchronous one?

**Comment by rexbut** [comment]
The task is asynchronous

**Comment by parlough** [comment]
I know this is a little late, but if you or someone else could provide some code which could reproduce this consistently, that would be great.

**Comment by ImMorpheus** [comment]
I'm not able to reproduce this on SF (common updated to https://github.com/SpongePowered/SpongeCommon/commit/beac6def8252c3c6d8804dc3d252fa7396dba9da)

It was probably fixed by https://github.com/SpongePowered/SpongeCommon/commit/6a18b73db169ba1740ed8625b6a7b7a98b534094
