### ISSUE TITLE
Sponge server not initialized on client when connecting to external server.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#814]
While this is normally desired behavior, things like this happen with mods:

https://gist.github.com/gravityfox/36e2b49b870be515ae277b118723e035

While I know the client thread isn't even supposed to touch sponge server, it is, and it looks like it's because of game profile lookups to do player head rendering on the client side.

While the game profile is just one issue, I suspect some investigation should be done on just what exactly the mods might touch from the client thread due to mixins remapping things.

**Comment by simon816** [comment]
I think the redirect `PlayerProfileCache.redirect$onGetGameProfile$0` should ignore client-side requests and just let the vanilla implementation handle the method

**Comment by me4502** [comment]
I agree, running a server thread on the client is not a good fix to the issue, as it shouldn't be called in the first place.
