### ISSUE TITLE
[1.9.4] CreativeInventoryEvent.Drop is fired with null Entity in list

### ISSUE THREAD

**Issue by Aaron1011** [SpongePowered/SpongeCommon#817]
SpongeCommonEventFactory [calls `player#dropItem`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/SpongeCommonEventFactory.java#L589) to get the `EntityItem` to add to the event. However, when item pre-merging is turned on, this method [ends up returning `null`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/entity/EntityUtil.java#L646).

**Comment by DarkArc** [comment]
I think this is the same issue as the one I reported here (though my diagnosis was slightly off):  #809.

**Comment by Aaron1011** [comment]
@DarkArc: Yeah, it's the same issue.

**Comment by Zidane** [comment]
Closing this as it no longer fires with null entries in the list.
