### ISSUE TITLE
Cataloging Currencies

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeCommon#821]
When I attempt to [use GameRegistry to catalog a Currency](https://github.com/pie-flavor/Pieconomy/blob/update/src/main/java/flavor/pie/Pieconomy.java#L117), it throws a [NullPointerException](http://pastebin.com/8sf0k1h0). I am told that it is a one-line fix.

**Comment by JBYoshi** [comment]
https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/registry/SpongeGameRegistry.java#L210

I believe the fix would be changing `of` to `ofNullable`.
