### ISSUE TITLE
Suggestion - Seperate folder for configs

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeCommon#825]
I noticed there is a config option to load mods from a separate directory which is very useful to keep mods/plugins separate (`plugins-dir="${CANONICAL_MODS_DIR}/plugins"`). It would be nice to have a config option for config files too for the same reasons.

Thanks!

**Comment by Nentify** [comment]
Why all the negative responses? It would be a config option and therefore completely optional.

**Comment by Deamon5550** [comment]
This was already brought up and refuted when the plugins-dir config option was being discussed see [this comment and the rest of the thread](https://github.com/SpongePowered/SpongeCommon/issues/427#issuecomment-171418456)

**Comment by Nentify** [comment]
It's not a bit late though. If it's a config, the default will remain as it is. That wouldn't be a problem.

**Comment by Mumfrey** [comment]
This was already discussed and turned down, there is no use-case for moving configs since they're already nicely organised as it is. The argument for plugins dir simply does not apply to configs. If you were to actually state a reason or use-case then it might merit discussion, but since your entire reasoning is

> It would be nice to have a config option for config files too **for the same reasons**

which is patently false since "the same reasons" don't apply, then there is no point being made here and this issue is frivolous. Closing.

**Comment by Nentify** [comment]
I keep my client and server configs in sync. When I update my server, I delete my config folder and unzip my new configs. Likewise with my mod list.

**Comment by Nentify** [comment]
Points being made here and why I think this issue should be re-opened:

- A separate config directory for plugins would be optional and provided to plugins by Sponge (through injection/what have you)
- It keeps plugins and mods separate, two very different things
- It makes it easy to maintain a modpack separate from the server. The two are independent.
- When mod configs change, it's much easier to just delete the config folder and put the new configs in. This is just the same as deleting the mods folder and putting the new mods in.

Thanks for your time and I hope this decision is re-considered.

Thanks!

**Comment by Zidane** [comment]
@Nentify 

I'll ponder this for a bit and render a final decision on the matter with my fellow leaders this evening sometime. I respect you for taking the time to gather your points and post them constructively (we had another issue on this matter/something else and the poster was unwilling to post constructively).

**Comment by majix560** [comment]
I fully heartedly need this to be made a reality.
As the original posted said, it's easier to just delete the mods/config folder when updating the server's mods and config.
I can't just delete my servers config/ directory.
I have to go through it and only delete the mod configs.

**Comment by KasperFranz** [comment]
@Zidane  what did your decision end with :)?
