### ISSUE TITLE
[1.8.9] Invulnerability ticks data has surprising behaviour.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#827]
Tested on SpongeForge : d3c31faa86dad12fd69cf494d0a3974ade985a4e

Setting Invulnerability ticks to Integer.max lets people 1 hit entities, rather then blocking the damage.

Either I'm missing some data that needs setting, or the processor for Invulnerability ticks should probably set whatever needs setting to prevent damage from occuring.

**Comment by bloodmc** [comment]
Does this occur in 1.10.2?
