### ISSUE TITLE
[1.10.2] SpawnCauses almost all meaningless again

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#829]
Related to: #797 the similar result occurs in the 1.10 branch; using spongeforge 2002-1534 and forge2002

The SpawnCause root object in SpawnEntityEvent is returning "CUSTOM" type for most things which in the 1.8.9 version had been correctly matched to their actual cause:
- SPAWN_EGG: for mobs spawned from a handheld egg or dispensed egg
- PLACEMENT: for armor stands, itemframes, pictures
- DISPENSE: for dispenser-based creation of floating boats, tracked minecarts, firecharges???maybe??
- EXPERIENCE: for XP-orbs 
- BREEDING: for an animal just birthed
- FALLING_BLOCK: a solid block turning into a falling block, or spawned into the world at a location
- PROJECTILE: should be for snowballs, chicken eggs, arrows, firecharges/ghast fireball???
- MOB_SPAWNER: for mobs produced by the fire-cage cubes
- TNT_IGNITE: when a tnt-primed entity is spawned  
- ????????????:  when a silverfish is spawned from a monster-egg block

As before, we are left with only WORLD_SPAWNER, DROPPED_ITEM, and PLACEMENT only for respawning player -- I could not find any way to trigger spawns for the other entries from the SpawnTypes enum-set-list-group 

In some cases, the entity type refines the scenario, like custom + falling block entity for a workaround, or custom+ item_frame = item frame placement.
In most other cases, there is no workaround: Custom+Blaze could be a summoned blaze, a blaze-egg cracked open, a blaze-spawner cube triggering them; Custom+Silverfish could be summoned, a silverfish-egg cracked open, a spawnercube from the structure, or the breaking of a mob-block; 

The main problem is that this current code is a step-backwards from the 1.8.9 code that addressed many of these cases, even if its a matter of holding the fort temporarily until regutting the entire cause system...

Also, different issues to post separately perhaps, unless this whole thing is going to be wrapped up in "We dont care - we're replacing it all with something different"....
At no point in time is a spawn event triggered (plus i dont know what Type it should be)  when a mob is being leashed or that leash attached to a post - yet a leash is an entity
When a player is spawned into place when joining the server even though it does trigger when he is re-spawned while playing as PLACEMENT...is this inconsistancy correct??

**Comment by theboomer** [comment]
It is rather frustrating having a half dozen plugins that I have not been able to elevate further than 1.8.9 which are core to my system, when everything else that existed has been able to port upwards and onwards, because the code fixes that made the 1.8.9 version finally give this information were not added to the 1.9 or 1.10 branches...
There keeps beeing talk of "Burn it to the ground, rebuilt it from the ground up, big plans, new ideas, fantastic changes whole thing entirely different" for methods like this, but I beg and plead please, please - unless those grand changes are a few small steps from being completed and pushed as a replacement very soon, can it be possible PLEASE to add these things into the 1.10.2 versions so that at least, we can move all those things forward that depended on this information and have things to work on, while waiting for any super-grand-major explosive-breaking-massive-rewrite changes to come out later?

**Comment by gabizou** [comment]
Yes, everyone is busy with a variety of things, it'll get done when it gets done, it's the top of my priority list of things to fix, but as I mentioned before and others have mentioned in the past, there are times when people's time is limited, and recently, my time has been limited.

That being said, I understand where you're coming from, but there's no need to make it seem like it's the end of the world or that we're abandoning all support. If anything, it's more draining to see comments on issues such as these because it contributes very little to the issue being resolved.

**Comment by theboomer** [comment]
I had to write somethign in order to get a response in order to know if I could do something to help resolve the issue.  If the response is "WE are totally abandoning this approach and are only going to work on alternate replacement code" then there is nothing I can do but wait.  If the response is "We'd love to add those same fixes back in, but it will take hours to find which commits did the job and those are hours best spent elsewhere" then .. I will spend many hours myself instead to identify the exact sponge versions where these events stopped throwing "Custom" for everything and started getting specific, to help identify the commit ids made, so that if it is simply a matter of remerging some of those commits again, then your time has been reduced to virtually nothing.

I'm not a skill level code guru with the skills required to setup to do PRs on the system, but I can contribute what I can in every other way.  So the question is, is it worth MY time and effort to identify the commits that fixed this issue in 1.8.9, or is that information totally worthless and useless and will contribute to absolutely nothing of resovling this issue due to abandoning this approach in favor of a different system (NOTE I SAID ABANDONING **THIS APPROACH**, not just ABANDONING -  there is a big distinction.)

**Comment by Deamon5550** [comment]
It would contribute absolutely nothing because resolving this is not as simple as copying the code from 1.8, the entire cause tracker system has changed and the spawn causes must be changed to match. Asking for progress or if there is anything you can do is fine, just don't be a cunt about it.

**Comment by theboomer** [comment]
Ergo the response is "WE have abandoned the system that would allow for readding this code into the system, and must commit full steam ahead to another alternative system", and thus there is nothing I can to do contribute to it with my time and effort.

Your solution, then Deamon, is to go and SPAM every single open ISSUES list with "What is the current progress on this issue?" (a very non-cunty worded statement, would you not agree, since apparently something I said here in my opening query ranked high on your cuntometer.

Despite the number of times I said PLEASE and I PLEAD in my statement, rather than "Why dont you motherfuckers get off your ass" instead, etc, my statements are somehow rude to people?

**Comment by gabizou** [comment]
Should be fixed in https://github.com/SpongePowered/SpongeCommon/commit/ad9aa8641d465419f0685c69f8f3fd694bc59d83
