### ISSUE TITLE
[1.10.2] Loosen restrictions for flight with motion limits

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeCommon#830]
Patch the "Moved too quickly" check to be forgiving, as Spigot does, for a better user experience.

For reference: [#688](https://github.com/SpongePowered/SpongeForge/issues/688)

**Comment by Aaron1011** [comment]
@bloodmc @Zidane: Should this be a configurable patch, or be always on?

**Comment by bloodmc** [comment]
@Aaron1011 Add a config option for it.

**Comment by Rasgnarok** [comment]
Will this be added in a next version of spongeforge? Currently I can see that we can change an entity's speed, but nothing on  player movement (or vehicles of said players).
I believe it is causing perfomance issues.
