### ISSUE TITLE
tp to a player

### ISSUE THREAD

**Issue by StonerBud** [SpongePowered/SpongeCommon#831]
tp'ing to another player the other player is not able to see me,
even logging out and back in don't fix it, requires a server restart
no errors in console

**Comment by Zidane** [comment]
No information provided about versions or anything. This also works fine for me locally in 1.8.9/1.10.2. Remove all plugins/mods besides Sponge and try again.

**Comment by ryantheleach** [comment]
From IRC:
Stonerbud:  I just upgraded to 1.10.2 - 5.0.0-BETA-1544 today
