### ISSUE TITLE
[1.10.2] [Bug] Redstone Simply doesn't work or crashes.

### ISSUE THREAD

**Issue by LewisLector** [SpongePowered/SpongeCommon#834]
Repeaters Simply do not work alone with comparator crashing a server.

http://pastebin.com/x5Vi67gC

**Comment by Zidane** [comment]
We need a full server log.

**Comment by LewisLector** [comment]
This is a little hard to do since the server doesn't crash. Only a long lag spike of pressing the button triggering the repeater.

**Comment by cartman-2000** [comment]
I had a crash on this just a little bit ago. Using SpongeForge.

Containes crash log and Forge log. Log containers blockphase errors on repeaters around line 14,000.
https://www.dropbox.com/s/7791evwywzi350a/logs.7z?dl=0

**Comment by gabizou** [comment]
It seems like a bad zip, can you re-zip and upload?

**Comment by cartman-2000** [comment]
They're 7z files.

**Comment by LewisLector** [comment]
I found that after powering the comparator and restarting the server it would crash again supplying power to it then after that crash it would be fine until the comparator got power again.

**Comment by gabizou** [comment]
> They're 7z files.

Yes, I know, and they uncompressed to 0kb sized files, hence why I asked for a new zip.



> I found that after powering the comparator and restarting the server it would crash again supplying power to it then after that crash it would be fine until the comparator got power again.

Still doesn't help us as we need the entire server log.

**Comment by cartman-2000** [comment]
I wonder if you had an issue with opening my first archive too?

**Comment by gabizou** [comment]
They're both 404's now, so definitely can't re-download them.

**Comment by gabizou** [comment]
@cartman-2000 If you can provide your full log up to the crash, that'd be great.

**Comment by cartman-2000** [comment]
First one is the crash from teleporting into a jungle biome that has a natural repeater spawn in it. by the looks of it, it crashes in chunk generation when it generates a repeater in a chunk.
https://www.dropbox.com/s/43p847k4xuglrt0/Crash%20logs.zip?dl=0

The second one is from placing down repeaters and comparators.
https://www.dropbox.com/s/40visvnck9ab1ae/Repeater%26comparator%20error..zip?dl=0

This is a base sponge issue, I did test it without any plugins, just having spongeforge as a mod, and the same error occurred.
