### ISSUE TITLE
[1.10.2] Block fading is acting abnormally

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#837]
When in a jungle, and breaking trees, leaves will not despawn until your client disconnects and reconnects, and vines will hang around until broken manually, the leaf fading doesn't trigger the vine's destruction.

**Comment by cartman-2000** [comment]
There's also this too, snow blocks don't fade with the leaves.
http://images.akamai.steamusercontent.com/ugc/267219116277968258/390C21ABFE993CCE2C1F974C3DFEEFBA60B58442/

**Comment by majix560** [comment]
Any idea when this issue is going to be fixed?

**Comment by stricq** [comment]
I'm seeing this issue still happen with 5.0.0-BETA-92.

**Comment by majix560** [comment]
@stricq how exactly, when there is no 5.0.0-BETA-92 version of sponge?

**Comment by stricq** [comment]
Sponge Vanilla.  I downloaded it from their site last weekend.  It's from the "Bleeding" tag.  https://repo.spongepowered.org/maven/org/spongepowered/spongevanilla/?buildTypeId=2
