### ISSUE TITLE
WorldUnloadEvent not being fired when stopping the server.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#839]
Pretty much what it says in the title. Testing with SpongeForge.

I think @Zidane made a commit 6 days ago to fix the event double firing in certain conditions, but now it's not firing at all when the server stops.

**Comment by gabizou** [comment]
@gravityfox is this in SF or SV?

**Comment by kenzierocks** [comment]
It says SpongeForge @gabizou.

**Comment by gabizou** [comment]
And it's verified that it also doesn't work on SV?

**Comment by gravityfox** [comment]
Okay so i have confirmed that this issue is not present in SV.

**Comment by Aaron1011** [comment]
@gravityfox: Yes, please.
