### ISSUE TITLE
[1.8.9] WorldBorder not sent to client after /worldborder set 200

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#842]
Tested on SF 1.8.9 d3c31faa86dad12fd69cf494d0a3974ade985a4e (8 behind)

WorldBorder not sent to client after /worldborder set 200

Tested on single player dev environment on SpongeForge.

Reconnecting shows correct border, attempting to walk through border before reconnecting rubberbands you back.

**Comment by stephan-gh** [comment]
Works fine on latest SpongeForge.
