### ISSUE TITLE
SpongeCommand Formatting [Minor]

### ISSUE THREAD

**Issue by Starza4TW** [SpongePowered/SpongeCommon#844]
Figured this was too small for a PR, just let you guys fix instead.

Just noticed that the /sponge command does not constantly use the newline escape character. 
![2016-07-13_16 42 00](https://cloud.githubusercontent.com/assets/2940976/16819079/c057eef0-4918-11e6-8339-3985331943c6.png)

Unless there is a lack of space, there should be a "\n" added to the end of audit and plugins descriptions in the sponge command's extended description so that it matches the other subcommands.

Also, the command itself has the description "Text description", which probably should be changed.

Class: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/command/SpongeCommand.java

**Comment by Zidane** [comment]
You're free to PR this :) if you would still like too :).

**Comment by Starza4TW** [comment]
Fixed with 84aee0e1a4a27ffb60b50da75f74515975755a37
