### ISSUE TITLE
[SpongeForge - 1563][Pixelmon 4.2.7] Server crash

### ISSUE THREAD

**Issue by OblivionNW** [SpongePowered/SpongeCommon#847]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  Java8CheckerCoremod (Pixelmon-1.8.9-4.2.7-universal.jar)
  SpongeCoremod ([SERVER] SpongeForge-1.8.9-1890-4.2.0-BETA-1563.jar)
Contact their authors BEFORE contacting forge

// Surprise! Haha. Well, this is awkward.

Time: 7/16/16 1:49 PM
Description: Exception ticking world entities

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.Iterators$3.next(Iterators.java:163)
	at org.spongepowered.common.mixin.plugin.entityactivation.ActivationRange.activateChunkEntities(ActivationRange.java:261)
	at org.spongepowered.common.mixin.plugin.entityactivation.ActivationRange.activateEntities(ActivationRange.java:246)
	at net.minecraft.world.WorldServer.handler$onInvokeProfiler$0(WorldServer.java:42)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
	at java.util.ArrayList$Itr.next(ArrayList.java:851)
	at com.google.common.collect.Iterators$3.next(Iterators.java:163)
	at org.spongepowered.common.mixin.plugin.entityactivation.ActivationRange.activateChunkEntities(ActivationRange.java:261)
	at org.spongepowered.common.mixin.plugin.entityactivation.ActivationRange.activateEntities(ActivationRange.java:246)
	at net.minecraft.world.WorldServer.handler$onInvokeProfiler$0(WorldServer.java:42)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:621)

-- Affected level --
Details:
	Level name: Pixelmon
	All players: 15 total; [EntityPlayerMP['bigtee1234'/984138, l='Pixelmon', x=-860.60, y=64.00, z=854.35], EntityPlayerMP['PepinoPT'/1066517, l='Pixelmon', x=6258.74, y=73.00, z=-5223.31], EntityPlayerMP['Nevorex'/1112262, l='Pixelmon', x=16754.14, y=84.00, z=-380.75], EntityPlayerMP['Thantrios'/1210223, l='Pixelmon', x=272.24, y=68.00, z=317.30], EntityPlayerMP['Meeker54'/1292468, l='Pixelmon', x=-1888.57, y=66.00, z=-993.92], EntityPlayerMP['Fearmonger'/1328176, l='Pixelmon', x=16463.73, y=92.00, z=-200.57], EntityPlayerMP['Padooooo'/1017297, l='Pixelmon', x=16778.89, y=85.00, z=-377.69], EntityPlayerMP['McNandinho'/1382897, l='Pixelmon', x=6362.57, y=61.00, z=-4568.00], EntityPlayerMP['Tylokz79'/1399525, l='Pixelmon', x=-877.59, y=64.00, z=936.28], EntityPlayerMP['SnowyBlizzerd'/1401027, l='Pixelmon', x=147.13, y=68.17, z=3549.16], EntityPlayerMP['I_Oblivion_I'/1415202, l='Pixelmon', x=40.37, y=68.00, z=190.50], EntityPlayerMP['HumanKillzone'/1441056, l='Pixelmon', x=-203.09, y=62.00, z=243.22], EntityPlayerMP['Comin4You'/1442568, l='Pixelmon', x=134.83, y=64.00, z=205.31], EntityPlayerMP['FrostyNinja794'/1448210, l='Pixelmon', x=68.32, y=71.00, z=270.47], EntityPlayerMP['MasterMarko404'/1451728, l='Pixelmon', x=-8198.50, y=64.00, z=-529.50]]
	Chunk stats: ServerChunkCache: 5128 Drop: 0
	Level seed: 8980066947109820694
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: 211.00,65.00,256.00 - World: (211,65,256), Chunk: (at 3,4,0 in 13,16; contains blocks 208,0,256 to 223,255,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 18547576 game time, 3410122 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:701)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:344)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:605)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:481)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.8.9
	Operating System: Linux (amd64) version 4.4.0-28-generic
	Java Version: 1.8.0_91, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4863997544 bytes (4638 MB) / 8572502016 bytes (8175 MB) up to 8572502016 bytes (8175 MB)
	JVM Flags: 8 total; -Xmx8192M -Xms8192M -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSIncrementalPacing -XX:ParallelGCThreads=2 -XX:+AggressiveOpts -Xincgc
	IntCache: cache: 1, tcache: 1, allocated: 12, tallocated: 94
	FML: MCP 9.19 Powered by Forge 11.15.1.1890 31 mods loaded, 31 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (minecraft_optimized.jar) 
	UCHIJAAAA	Forge{11.15.1.1890} [Minecraft Forge] (minecraft_optimized.jar) 
	UCHIJAAAA	sponge{1.8.9-1890-4.2.0-BETA-1563} [SpongeForge] ([SERVER] SpongeForge-1.8.9-1890-4.2.0-BETA-1563.jar) 
	UCHIJAAAA	io.github.hsyyid.adminshop{1.8.1} [AdminShop] (AdminShop-1.8.9-1.8.1-universal.jar) 
	UCHIJAAAA	buycraft{SET_BY_MAGIC} [Buycraft] (BuycraftX.jar) 
	UCHIJAAAA	economylite{2.2.1} [EconomyLite] (EconomyLite-v2.2.1.jar) 
	UCHIJAAAA	nuvotifier{2.3.2.2} [NuVotifier] (nuvotifier-universal.jar) 
	UCHIJAAAA	ninja.leaping.permissionsex{2.0-SNAPSHOT} [PermissionsEx] (PermissionsEx-Sponge.jar) 
	UCHIJAAAA	com.enjin.sponge{3.0.9-sponge} [Enjin Minecraft Plugin] (EMPSponge.jar) 
	UCHIJAAAA	pixelmon{4.2.7} [Pixelmon] (Pixelmon-1.8.9-4.2.7-universal.jar) 
	UCHIJAAAA	ivsevs{4.1.0} [IVsEVs] (Evs-Ivs-1.8.9-4.1.0-universal.jar) 
	UCHIJAAAA	foxcore{0.8.0-103} [FoxCore] (FoxCore-0.8.0-103.jar) 
	UCHIJAAAA	foxguard{} [FoxGuard] (FoxGuard-0.18.0-249.jar) 
	UCHIJAAAA	griefprevention{1.0} [GriefPrevention] (GriefPrevention-1.8.9-1.0-29 (1).jar) 
	UCHIJAAAA	de.randombyte.holograms{v1.0.1} [Holograms] (holograms-v1.0.1.jar) 
	UCHIJAAAA	lootcrate{1.1} [lootcrate project] (LootCrate-3.3.jar) 
	UCHIJAAAA	nucleus{0.6.0-SNAPSHOT} [Nucleus] (Nucleus-0.6.0-SNAPSHOT-all.jar) 
	UCHIJAAAA	OBNWPixelExtras{1.0} [OBNWPixelExtras] (OBNWPixelExtras-1.0.jar) 
	UCHIJAAAA	pixelextras{2.1.4} [Pixel Extras] (PixelExtras-1.8.9-2.1.4-universal.jar) 
	UCHIJAAAA	pixelvote{2.0} [Pixel Vote] (PixelVote-2.0.jar) 
	UCHIJAAAA	prism{3.0.0} [Prism] (Prism-3.0.0-beta2-6-g84d50b4-all.jar) 
	UCHIJAAAA	com.gmail.trentech.pjw{0.9.2} [Project Worlds] (projectworlds-4.2.0-0.9.2.jar) 
	UCHIJAAAA	pwnfilter{1.0} [PwnFilter] (PwnFilter-3.5.0.jar) 
	UCHIJAAAA	br.net.fabiozumbi12.rankupper{2.2} [RankUpper] (RankUpper_Sponge.jar) 
	UCHIJAAAA	signedit{0.0.1} [SignEdit] (SignEdit.jar) 
	UCHIJAAAA	skinsrestorer{1.0} [SkinsRestorer] (SkinsRestorer-v12.4.2.jar) 
	UCHIJAAAA	com.gmail.socraticphoenix.sponge.star{1.7.8} [StarAPI] (StarAPI-1.7.8.jar) 
	UCHIJAAAA	com.gmail.socraticphoenix.sponge.voteright{1.1.6} [VoteRight] (VoteRight-1.1.6.jar) 
	UCHIJAAAA	wondertrade{4.3.1} [Wondertrade] (WonderTrade-1.8.9-4.3.1-universal.jar) 
	UCHIJAAAA	worldedit{6.1.1} [WorldEdit] (WorldEdit-Forge-1.8.9-6.1.1.jar) 
	Loaded coremods (and transformers): 
Java8CheckerCoremod (Pixelmon-1.8.9-4.2.7-universal.jar)
  
SpongeCoremod ([SERVER] SpongeForge-1.8.9-1890-4.2.0-BETA-1563.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
	Profiler Position: N/A (disabled)
	Player Count: 19 / 60; [EntityPlayerMP['bigtee1234'/984138, l='Pixelmon', x=-860.60, y=64.00, z=854.35], EntityPlayerMP['PepinoPT'/1066517, l='Pixelmon', x=6258.74, y=73.00, z=-5223.31], EntityPlayerMP['Nevorex'/1112262, l='Pixelmon', x=16754.14, y=84.00, z=-380.75], EntityPlayerMP['Thantrios'/1210223, l='Pixelmon', x=272.24, y=68.00, z=317.30], EntityPlayerMP['Meeker54'/1292468, l='Pixelmon', x=-1888.57, y=66.00, z=-993.92], EntityPlayerMP['Fearmonger'/1328176, l='Pixelmon', x=16463.73, y=92.00, z=-200.57], EntityPlayerMP['Padooooo'/1017297, l='Pixelmon', x=16778.89, y=85.00, z=-377.69], EntityPlayerMP['McNandinho'/1382897, l='Pixelmon', x=6362.57, y=61.00, z=-4568.00], EntityPlayerMP['Tylokz79'/1399525, l='Pixelmon', x=-877.59, y=64.00, z=936.28], EntityPlayerMP['SnowyBlizzerd'/1401027, l='Pixelmon', x=147.13, y=68.17, z=3549.16], EntityPlayerMP['I_Oblivion_I'/1415202, l='Pixelmon', x=40.37, y=68.00, z=190.50], EntityPlayerMP['HumanKillzone'/1441056, l='Pixelmon', x=-203.09, y=62.00, z=243.22], EntityPlayerMP['basstelling'/1445722, l='Spawn', x=11.01, y=73.00, z=-75.87], EntityPlayerMP['Comin4You'/1442568, l='Pixelmon', x=134.83, y=64.00, z=205.31], EntityPlayerMP['FrostyNinja794'/1448210, l='Pixelmon', x=68.32, y=71.00, z=270.47], EntityPlayerMP['Neo2205'/1451557, l='Spawn', x=80.50, y=67.00, z=-43.50], EntityPlayerMP['Gruener_Apfel'/1451608, l='Spawn', x=80.50, y=67.00, z=-43.50], EntityPlayerMP['Fynn630'/1451669, l='Spawn', x=78.18, y=67.00, z=-43.61], EntityPlayerMP['MasterMarko404'/1451728, l='Pixelmon', x=-8198.50, y=64.00, z=-529.50]]
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)

**Comment by Aaron1011** [comment]
I've added [a new config option](https://github.com/SpongePowered/SpongeCommon/commit/773174d44b61e8c5637857906c1b4a361bab0799) to help debug this. Can you upgrade to the latest SpongeForge, and try enabling the config option 'concurrent-entity-checks' under the 'debug' category (it will appear after the first run with the new build). Then, try to reproduce this issue again. You should get a different stacktrace, along with an informative error message, when it happens.

**Comment by OblivionNW** [comment]
OK! I will install that and update 5his ticket as soon as I manage to reproduce the crash bug.

**Comment by bloodmc** [comment]
This is caused by one of your plugins messing with the entity list off the main thread. VoteRight runs everything async and can easily cause this issue if you setup triggers to give players items or spawn entities. Other than that, this is not a sponge issue.

**Comment by OblivionNW** [comment]
I've not got any triggers but I have it give items when they vote, no entities are spawned
