### ISSUE TITLE
[1.10.2] Redstone performance issues.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeCommon#852]
I made three redstone clocks, one of one type and two of another type (to test clocks with repeaters and clocks with redstone torches), made timings in a 1.8.9 SpongeForge server and then a 1.10.2 SpongeForge server, here are the results:

1.8.9: https://timings.aikar.co/v2/?id=259f160ae9964a94b69a2a8e5e940835
1.10.2: https://timings.aikar.co/v2/?id=62a1adb48c134cf5a9bf798ccb783bc3

As you can see, redstone performance is way worse in 1.10.2.

Original SF Issue: [#772](https://github.com/SpongePowered/SpongeForge/issues/772)

**Comment by bloodmc** [comment]
@LuxusDarkangel Please perform another test using the latest builds.

**Comment by LuxusDarkangel** [comment]
Performance is amazing now even aside from redstone, (15~ms in a freshly generated world doing nothing before, 25-30~ with redstone clocks to 6~ ms with redstone clocks)

But repeaters behaves weird now: 
http://i.imgur.com/CjT49GS.png
http://i.imgur.com/NrLrmAU.png

**Comment by bloodmc** [comment]
@gabizou ^
