### ISSUE TITLE
[1.10.2] Protection duplication bug.

### ISSUE THREAD

**Issue by LuxusDarkangel** [SpongePowered/SpongeCommon#853]
Explained it with images here: http://imgur.com/a/N5Rq3

Original SF Issue: [#773](https://github.com/SpongePowered/SpongeForge/issues/773)

**Comment by LuxusDarkangel** [comment]
This bug is totally gamebreaking, any news @kashike?

**Comment by gabizou** [comment]
@LexManos with the latest changes, did anything change?

**Comment by LuxusDarkangel** [comment]
Well, I'm Not lex, but will give it a try and report back in a few minutes.

**Comment by LuxusDarkangel** [comment]
No, keeps happening.
