### ISSUE TITLE
[1.10.2] Teleported to origin on join

### ISSUE THREAD

**Issue by Meronat** [SpongePowered/SpongeCommon#859]
On my MoveEntityEvent listener I am printing the `fromTransform() `and `toTransform()` methods immediately, and it seems that on join for some reason their transform location and rotation are changed from their actual values to 0, 0, 0 then back again. I do not believe this is intended and is causing issues with my plugin.

[The first and second messages are the `fromTransform()` and `toTransform()` from the first call and the third and fourth are them from the second call. ]
![teleportonjoin](https://cloud.githubusercontent.com/assets/18372958/17121078/880364d0-5296-11e6-80b2-d17878d5c654.PNG)

**Comment by Nighteyes604** [comment]
Commenting to confirm I have this issue even not on Join:

I created a command that sets the player's transform to their current transform when run:
`((Player)source).setTransform(((Player)source).getTransform());`

Created a listener to print some debug statements:
```
@Listener
public void playerMove(MoveEntityEvent event, @Getter("getTargetEntity") Player player) {
    getLogger().info(event.toString());
}
```

Results:
1 MoveEntityEvent.Teleport with the correct from and toTransform
2 MoveEntityEvents, one setting them to 0,0,0 the other setting them from 0,0,0
http://pastebin.com/0A2CpR8T
