### ISSUE TITLE
SpongeVanilla 1.10.2 beta 93. Furnace not working.

### ISSUE THREAD

**Issue by GOKUSSL4** [SpongePowered/SpongeCommon#865]
Having issue where furnace does not work. It will not burn fuel.

**Comment by Aaron1011** [comment]
@GOKUSSL4: I'm unable to reproduce this. Are you running any plugins, or did you take any special steps to reproduce this?

**Comment by chrismack** [comment]
@Aaron1011 I had the same issue using Sponge Vanilla 1.10.2-5.0.0-BETA-93 with no plugins installed

**Comment by GOKUSSL4** [comment]
I used without plugins same problem.

**Comment by Zidane** [comment]
@chrismack @GOKUSSL4 

Re-test with latest SV build
