### ISSUE TITLE
Operator bypass whitelist with permission service

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#868]
Hi,
with a permissions service, operators can bypass the whitelist.
It's possible to disable this ?

https://github.com/SpongePowered/SpongeAPI/issues/1311

**Comment by phit** [comment]
confirmed with 7.0.0-BETA-2741

**Comment by ryantheleach** [comment]
~~~I'll take this one for a week, unless you were planning on it @phit .~~~

**Comment by phit** [comment]
go for it 👍

**Comment by Cybermaxke** [comment]
i have already a PR that resolves this issue. But it should be updated.

https://github.com/SpongePowered/SpongeCommon/pull/1012

**Comment by ryantheleach** [comment]
@Cybermaxke would you like to update it, or would you prefer I did it?

**Comment by Cybermaxke** [comment]
I can update it, I don't think that it will need a lot of changes, just some comments and checking if it still works.
