### ISSUE TITLE
Incorrect file permissions

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeCommon#869]
http://pastebin.com/DTdZTAkP

```
luke@play:~/sponge-vanilla$ umask
0002
```

It seems like Sponge is creating files with 600 permissions (folders seem to be the correct permissions). The files should be 664 (-rw-rw-r--). I've linked a paste showing permissions from vanilla Forge, SpongeForge and SpongeVanilla showing the discrepancies. I'm assuming it's either an issue with Sponge, the config software or my setup. My setup works with everything else though and is pretty fresh out of the box, so I'm not sure why only Sponge would be acting up here.

Thanks for your help!

**Comment by Zidane** [comment]
@Nentify 

Correct me if I'm wrong but it seems to be config files that have the wrong perms and those are saved with Configurate.

@zml2008 .

**Comment by Nentify** [comment]
Yes, only Sponge config files are incorrect. Sponge folders, Forge files & folders and vanilla files & folders are correct.

**Comment by Zidane** [comment]
Closing this as it is a Configurate issue. Open it on that repo instead.
