### ISSUE TITLE
MessageChannelEvent.Chat behavior changed

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#870]
Previously `event.getFormatter().getBody()` would return the message, and not include the name. For instance if a user's message in the chat window was:
```
<Dark_Arc> Hi!
```
`event.getFormatter().getBody()` would return:
```
Hi!
````

It now returns:
```
<Dark_Arc> Hi!
```

Instead of using the user's name portion as the header.

**Comment by gabizou** [comment]
Is this happening in both SpongeForge and SpongeVanilla?

**Comment by DarkArc** [comment]
Observed in SF. I assumed it was common, but could be SF specific.

**Comment by DarkArc** [comment]
Got fixed in a recent build.
