### ISSUE TITLE
[1.10.2] UUID uniqueness in spawned entities is not enforced.

### ISSUE THREAD

**Issue by Thutmose** [SpongePowered/SpongeCommon#872]
Vanilla behaviour for 1.9+ enforces that UUIDs in the world are unique.  It does this by checking canAddEntity before spawning the entity.

Without this, if there is a case where a player disconnects badly (say due to bad internet connections/packet corruption issues), then there can be issues where the old player is not properly removed from the mappings, which then causes issues with anything that needs to look up the player by UUID.

I am fairly certain that this is the cause of some players using Pokecube will suddenly be unable to control their pokemobs after they DC due to network issues.  It has also been noticed as ocurring on a Pixelmon server as well, so it is not limited to Pokecube, and both of those mods have completely different ownership systems, the only similarity being that they find the player based on uuid lookups.

These are the places where I noticed sponge adds entities without checking this condition, I am not sure of there are any more:
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L981-L984
https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/world/MixinWorldServer.java#L938-L952

Vanilla checks it in WorldServer.spawnEntityInWorld(Entity entityIn) and WorldServer.loadEntities(Collection<Entity> entityCollection) and canAddEntity forceably removes any stale player entities if the player tries to log back in, and they are still in the world.  For other entities, it denies the spawn of the duplicate.

**Comment by Deathwhitch** [comment]
not sure if this effects mobs or not but my console is being spammed with "[10:50:27] [Server thread/WARN]: Keeping entity Cow that already exists with UUID 96733171-8d39-4cf4-ae52-f164790082d4"

it does this for cows chickens sheep etc. And goes on endlessly even after attempting to kill the mob with commands

**Comment by cartman-2000** [comment]
It would be nice to have an option to remove duplicate entities on the server. That message can get a bit spammy after a while.
