### ISSUE TITLE
BlockSnapshot creator is always empty

### ISSUE THREAD

**Issue by Flibio** [SpongePowered/SpongeCommon#875]
Whenever using the `getCreator` method on a `BlockSnapshot`, the creator always not present, even if I just placed the block. The `BlockSnapshot` was retrieved from a transaction from the `ChangeBlockEvent.Break`. This was tested on SpongeForge build 1655.

**Comment by gabizou** [comment]
@Flibio Can you re-test on latest versions of SF? I'm having some difficulty not getting creator/notifier for block snapshots created for events.

**Comment by Flibio** [comment]
@gabizou: I've retested on the SpongeForge 1686 using a brand new server, but the issue still occurs. The steps taken:

- Joined the brand new server
- `/op Flibio`
- `/gamemode creative`
- Placed a stone block
- Destroyed the stone block
 - The below code outputted empty `Optional`s

Here is the code (the only plugin on the server):

```java
@Plugin(id = "test", name = "Test", version = "1.0.0", description = "Test")
public class Main {

    @Listener
    public void onBreak(ChangeBlockEvent.Break event, @First Player player) {
        for (Transaction<BlockSnapshot> transaction : event.getTransactions()) {
            System.out.println("O:" + transaction.getOriginal().getCreator());
            System.out.println("F:" + transaction.getFinal().getCreator());
        }
    }
}
```

**Comment by gabizou** [comment]
Cannot reproduce in the latest builds.
