### ISSUE TITLE
Cactus damage not working

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeCommon#876]
When bumping into a cactus, you don't get damaged.

Versions: https://gyazo.com/9bb95d11888b4e2f1e360b591109eaf3

**Comment by bloodmc** [comment]
This was fixed in commit
https://github.com/SpongePowered/SpongeCommon/commit/a1ac30c3e9e957c3df6d858885de3b10a6c0a30b

Update to latest.
