### ISSUE TITLE
Client not updated when sign changes.

### ISSUE THREAD

**Issue by mcmacker4** [SpongePowered/SpongeCommon#88]
I have been trying to create a PlayerInteractBlockEvent that changes a sign's text when it is right clicked. It has been impossible. I have been confirmed that there is an error in the implementation.
The following code was ran where *loc* was a valid sign placed in the world. The sign's text didn't change until the player disconnected and reconnected. Also [Here] (https://github.com/SpongePowered/SpongeAPI/issues/752) is a link to another issue where this was discussed.
```java
Optional<TileEntity> opTileEntity = loc.getTileEntity();
if (!opTileEntity.isPresent()) {
    System.out.println("Tile entity doesn't exist");
    return;
}
TileEntity signTile = opTileEntity.get();
Optional<SignData> optSignData = signTile.getOrCreate(SignData.class);
if (optSignData.isPresent()) {
    SignData sign = optSignData.get();
    sign.setLine(0, Texts.of("Some Text"));
    DataTransactionResult result = signTile.offer(sign);
    System.out.println(result);
} else {
    System.out.println("Data unable to be created");
}
```
(code by @simon816 )

**Comment by JBYoshi** [comment]
I'd say wait for #94 and SpongePowered/SpongeAPI#685.

**Comment by JBYoshi** [comment]
@gabizou From looking at [`SignDataProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/data/processor/data/tileentity/SignDataProcessor.java#L148), this doesn't seem to be fixed yet. I think it needs a call to `World.markBlockForUpdate()`.

**Comment by modwizcode** [comment]
That's correct. I used that method in the portals plugin I wrote to fix sign functionality.

**Comment by JBYoshi** [comment]
Pinging @gabizou

**Comment by Aaron1011** [comment]
Fixed in https://github.com/SpongePowered/SpongeCommon/commit/c3c35de85dae415967e4a5ad8c11e477c885f68e.

**Comment by JBYoshi** [comment]
This also needs to be updated in `SignLinesValueProcessor`.
