### ISSUE TITLE
Command blocks & Structure blocks not working

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeCommon#883]
When I do one of the following things I get this error:

* Changing a commandblock between Impulse/Chain/Repeat: 
http://pastebin.com/raw/Hjvny3KK

* Changing a commandblock between Unconditional/Conditional: 
http://pastebin.com/raw/C23qvbQi

* Changing a structure block between Save/Load/Data/Corner mode: 
http://pastebin.com/raw/QpW4tUBe

Spawning in a repeating command block works, and changing a commandblock between Needs redstone/Always active works too. When an error is thrown the command block does not actually change type.

Sponge version: https://gyazo.com/d9feae3b0b65bcb30e58ca655a8598b7

**Comment by Aaron1011** [comment]
Closed in https://github.com/SpongePowered/SpongeCommon/commit/8591dea193446ddd4f57607d1f7e440779c37e42.
