### ISSUE TITLE
[1.8.9] Server Crash/Lockup upon Login Event & Full Server

### ISSUE THREAD

**Issue by Rhonim** [SpongePowered/SpongeCommon#884]
Had about 40-50+ Crashes/lock ups from this so far. I had posted this is SpongeForge previously, but that was before looking into it and realizing it came from SpongeCommon.

http://pastebin.com/m0puTEw7

You cannot reproduce this without Sponge. Looks like its triggered off of a ClientConnectionEvent.Login event being cancelled (i.e. [this line](https://github.com/SpongePowered/SpongeCommon/blob/31fde9f031a5141add3bd24244e96559c0ccbaaa/src/main/java/org/spongepowered/common/mixin/core/server/MixinPlayerList.java#L236)). Which in turn calls [this](https://github.com/SpongePowered/SpongeCommon/blob/master/src/main/java/org/spongepowered/common/mixin/core/server/network/MixinNetHandlerLoginServer.java#L85). Which then goes to close the channel then you end up at awaitUninterruptibly.

If you want to reproduce it, create a ClientConnectionEvent.Login event and have people trying to connect over and over while the server is full.

Before crashing fully is does put the following in console:

```
[22:12:27] [Netty Epoll Server IO #2/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
[22:12:39] [Netty Epoll Server IO #12/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
[22:13:04] [Netty Epoll Server IO #4/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
[22:13:07] [Netty Epoll Server IO #4/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
[22:13:08] [Netty Epoll Server IO #11/ERROR] [FML]: NetworkDispatcher exception
io.netty.handler.timeout.ReadTimeoutException
```

**Comment by bloodmc** [comment]
@simon816 can you look at this?

**Comment by Rhonim** [comment]
For those that are also having issues with this, my current "fix" is to always setCancelled(false) to the Login even then kick the user 1 tick later if the server is full.

**Comment by gabizou** [comment]
My gut feeling is that there's a disconnect occurring when it shouldn't be occurring. Currently, vanilla will disconnect players during the player joining the server (through `NetHandlerPlayServer::update()` when the login state is: `NetHandlerLoginServer.LoginState.READY_TO_ACCEPT`). It seems like Sponge is trying to disconnect clients far too early, basically during the authentication process, before authentication has completed and before the net handler play server has been ticked.

@Rhonim would it be possible to test for similar setups in 1.10? As currently the code seems to have been ported very well to replicate the issue, but I lack enough players to fill a server to the full server status :).

**Comment by Deamon5550** [comment]
@gabizou couldn't you just set the player max to zero and try connecting?

**Comment by gabizou** [comment]
@Deamon5550 I still believe that it has to do with the order of events taking place. It's actually really easy to move the login into the tryAccept of `NetHandlerLoginServer` where the ban lists and server capacity are checked.

**Comment by Rhonim** [comment]
@gabizou Currently don't have a 1.10 setup that would be easy to test on unfortunately. I'll see if I can get something set up in the next few days.

**Comment by Zidane** [comment]
Is this still an issue in the latest builds?

**Comment by Zidane** [comment]
1.8.9 is no longer supported.

Re-test with stable-5 and report back if it still occurs. We'll re-open in the event that it does.
