### ISSUE TITLE
Using item drop all shortcut key from inventory deletes item

### ISSUE THREAD

**Issue by Kippers37** [SpongePowered/SpongeCommon#894]
Originally reported on the SpongeVanilla issue tracker: SpongePowered/SpongeVanilla#263

---

Using a clean installation of SpongeVanilla 1.10.2-5.0.0-BETA-100 without any plugins.

When hovering over an item in the inventory and using the item drop all shortcut key (default CTRL + Q) deletes the item.

In inventory hovering over the item.

![](http://i.imgur.com/QoWaIPu.png)

Pressing the item drop all shortcut key (CTRL + Q), the item is removed from inventory.

![](http://i.imgur.com/pqJ04oS.png)

But does not show up on the ground.

![](http://i.imgur.com/vBGp3Xb.png)

**Comment by bloodmc** [comment]
Unable to reproduce this issue with latest SF build.

**Comment by Minecrell** [comment]
@bloodmc Still happening for me on latest SpongeForge (in dev environment at least).

A full stack of an item in the inventory, then open the inventory (don't press CTRL + Q directly), then hover the item with the mouse pointer and press CTRL + Q. The items don't get dropped for me, they just disappear.

It works fine when you are not in an inventory and just drop the currently selected items in your hotbar.

**Comment by bloodmc** [comment]
Tested latest SF, issue does not occur while hovering over items.
