### ISSUE TITLE
SpawnEntityEvent error w/ GriefPrevention

### ISSUE THREAD

**Issue by Nentify** [SpongePowered/SpongeCommon#896]
Error log: https://www.irccloud.com/pastebin/K3oU9Vkp/

This appears in the console frequently. I'm not entirely sure where the mobs are spawning to trigger it, but can look into it more if the log doesn't provide enough information.

Thanks!

**Comment by Nentify** [comment]
Seems to happen when using a spawn egg inside a GP claim with `entity-spawn: false`. There may be other causes too, but this one was reproducible.

**Comment by gabizou** [comment]
Fixed by https://github.com/SpongePowered/SpongeCommon/commit/ad9aa8641d465419f0685c69f8f3fd694bc59d83
