### ISSUE TITLE
Command signs cause an error

### ISSUE THREAD

**Issue by Bammerbom** [SpongePowered/SpongeCommon#897]
Steps to reproduce:
1. Enter [this command](http://pastebin.com/R9ZumVuG) in a commandblock
2. Activate the commandblock
3. Place the sign
4. Right-click the sign
5. Look at the console and see [this error](http://pastebin.com/ZUrhZmzs)

**Comment by JBYoshi** [comment]
The fix: Change [these lines](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/command/MinecraftCommandWrapper.java#L103-106) to
`CommandHandler handler = SpongeImpl.getServer().getCommandManager();`
