### ISSUE TITLE
Issues with PlayerBreakBlockEvent vs. BlockBreakEvent

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#9]
This applies to both Sponge and SpongeVanilla.

The original implementation of PlayerBlockBreakEvent in Sponge is mixed into BlockEvent.Break from Forge. An API change, at some point, landed and changed the interface; it was granted a Direction facing. This presents a problem because:

* tryHarvestBlock (where Forge fires their event) in ItemInWorldManager has no parameter for the facing direction. 
* tryHarvestBlock is called from multiple spots and therefore cannot be modified in Forge to add that parameter.
* Forge has no distinct "Break" event for a Player. Not an issue for us except that it has no direction parameter which means we can't just mix this for PlayerBreakBlockEvent.

From my very tired perspective (late here), the best way to move forward is to make BlockEvent.Break implement BlockBreakEvent and add another overwrite to ItemInWorldManager for when we know the EnumFacing to fire the player version.

I welcome all thoughts
@SpongePowered/developers

**Comment by bloodmc** [comment]
This is no longer an issue with our new ChangeBlockEvent.
