### ISSUE TITLE
[1.10.2 - Beta 109] DamageTypes not initialized

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#902]
Hi,
When I use the DamageTypes.class during the event DestructEntityEvent, I have this error : 
http://pastebin.com/aRJrF4uc

**Comment by rexbut** [comment]
@gabizou fix the problem in the commit https://github.com/SpongePowered/SpongeCommon/commit/dc02afafbc2ca753539f06214d4357182a1315b9
