### ISSUE TITLE
[1.10.2 - Beta 109] PopularObject : Abstract Method Error

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#904]
Hi,
The result of the function PopulatorObjects.OAK.getId() or PopulatorObjects.OAK.getName() return this error : http://pastebin.com/ixDWgzsC

**Comment by ZephireNZ** [comment]
AbstractMethodError means @Deamon5550 forgot to add `getId()` when he implemented generators ;)
