### ISSUE TITLE
No way to determine source BlockSnapshot for DropItemEvent.Destruct

### ISSUE THREAD

**Issue by Meegooo** [SpongePowered/SpongeCommon#906]
In 1.10 this event always has AIR as a source BlockSnapshot.
http://i.imgur.com/J3RXRwy.png

And for the record, no player in the cause, so this: https://github.com/SpongePowered/SpongeCommon/issues/846

PS. In 1.8.9 it worked correctly http://i.imgur.com/DDiKIDW.png

**Comment by ImMorpheus** [comment]
you again DropItemEvent ?

Duplicate of #732
