### ISSUE TITLE
CommandBlock issue

### ISSUE THREAD

**Issue by Pymous** [SpongePowered/SpongeCommon#907]
Hey !

A few days ago, we were on Build 1684. Today, we updated to Build 1688, and we now have the follow issue when we activate a CommandBlock.

[Stacktrace.txt](https://github.com/SpongePowered/SpongeCommon/files/441157/Stacktrace.txt)

Hope it's not too hard to fix :)

**Comment by Pymous** [comment]
Hey @Aaron1011 , sorry to re-open the issue, but I still have the issue actually with Build 1689 :( 

Here is the stacktrace : 
[CommandBlock.txt](https://github.com/SpongePowered/SpongeCommon/files/444529/CommandBlock.txt)

**Comment by Aaron1011** [comment]
@Pymous: Can you please list the steps you took to cause that?

**Comment by Pymous** [comment]
@Aaron1011 : It's pretty straightforward : 
- I set up the command block (in this case, the command : /minecraft:kill ARGS)
- I add a redstone directing to it
- I add a redstone torche

Bam, spam in my console.

Samething if the trigger is a pressure plate
