### ISSUE TITLE
Scheduler timing is off

### ISSUE THREAD

**Issue by DarkArc** [SpongePowered/SpongeCommon#91]
Currently there is an issue where the task delay will be used as the delay between the initial two iterations of a repeating scheduler.

For instance, the following code will execute once with no delay, then execute with a 1 tick delay, then operate with the correct 1 second delay:
https://github.com/Skelril/Skree/blob/master/src/main/java/com/skelril/skree/service/internal/dropclear/DropClearServiceImpl.java#L199-L202

**Comment by simon816** [comment]
Ah, after a lot of debugging I have found the problem.
The sync scheduler works fine when the time measurement (ticks/wall clock) is the same, but when mixing the two, like in your case a delay in ticks and an interval in seconds, there is a problem - the scheduler switches from ticks to currentTimeMillis, but realizes that the absolute time is passed the threshold in ticks, so will execute again in the next tick cycle.
If my diagnostic is correct I should be able to fix this quite easily.
