### ISSUE TITLE
Add implementation entity AreaEffectCloud 

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#910]
Hi,
Please can you implement all keys and functions of "AreaEffectCloud".

[Issue in SpongeAPI](https://github.com/SpongePowered/SpongeAPI/issues/1343)

**Comment by rexbut** [comment]
Keys : 
- `Key<Value<Color>> COLOR`
- `Key<Value<Float>> AREA_CLOUD_RADIUS`
- `Key<Value<ParticleType>> AREA_CLOUD_PARTICLE`
- `Key<Value<Integer>> AREA_CLOUD_DURATION`
- `Key<Value<Integer>> AREA_CLOUD_WAIT_TIME`
- `Key<Value<Float>> AREA_CLOUD_RADIUS_ON_USE`
- `Key<Value<Float>> AREA_CLOUD_RADIUS_PER_TICK`
- `Key<Value<Integer>> AREA_CLOUD_DURATION_ON_USE`
- `Key<Value<Integer>> AREA_CLOUD_REAPPLICATION_DELAY`
- `Key<ListValue<PotionEffect>> POTION_EFFECTS`
- `Key<MutableBoundedValue<Integer>> AGE`

**Comment by rexbut** [comment]
Implemented in commit https://github.com/SpongePowered/SpongeCommon/commit/6b31d50b91d2d2eb489cad8940759bb7526fc255
