### ISSUE TITLE
DamageEntityEvent does not have a Player cause.

### ISSUE THREAD

**Issue by gravityfox** [SpongePowered/SpongeCommon#911]
I'm not sure if this was intended or not, but grabbing the first Player.class yields nothing when i'm punching a pig.

I know that i could sift through all the causes, but that's not ideal.

**Comment by gabizou** [comment]
Look at `DamageSource`, and the [javadoc](https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/event/entity/DamageEntityEvent.java#L62-L141) that explains in depth virtually everything that went into designing the `DamageEntityEvent` (and similarly the `AttackEntityEvent`).

**Comment by gravityfox** [comment]
I made the issue because It USED to work. I know exactly how I'm supposed to use the damage sources, but the Player cause used to also be thrown in. I was wondering if the removal was intentional or not.

**Comment by gravityfox** [comment]
@gabizou: gabiplz...

**Comment by gravityfox** [comment]
Also if the cause is only in the form of DamageSources, there doesn't seem to be any way of knowing that a player caused damage if they disconnect before the damage occurs. I.E. Shooting an arrow into the sky and disconnecting before it lands on someone.
