### ISSUE TITLE
[Bleeding]  SpawnEvent.chunkLoad doesn't seem to be firing.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#914]
SpawnEvent.chunkLoad doesn't seem to be firing.

Tested on SpongeForge https://github.com/SpongePowered/SpongeForge/commit/3e842c8e8a39669044ebebea967d0086176d4f48

Checked against https://github.com/SpongePowered/SpongeCommon/issues/41 so it should be implemented, just seems like it may have gotten lost in a minecraft update.

**Comment by gabizou** [comment]
@ryantheleach start the game with `-Dmixin.debug.export=true` and zip up the `.mixin.out` folder so that I can see what the output is for loading entities from chunks.

**Comment by ryantheleach** [comment]
[mixin.out.zip](https://github.com/SpongePowered/SpongeCommon/files/450801/mixin.out.zip)
