### ISSUE TITLE
[1.10.2] SpongeForge does not give XP for furnaces

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#921]
Forge-1.10.2--2073
SpongeForge-2073-Beta-1698
NO MODS, no plugins at all.

No furnace smelting processes generate XP when the furnace is emptied.  Gold and iron ore, 64 stack burned to completion used as best control test,  no orbs are spawned, they are not invisible, player xp is not changed, no sound is generated.

Disable SpongeForge and the Forge server DOES generate XP for those items in the furnace.

**Comment by stephan-gh** [comment]
Works fine on the latest SpongeVanilla so this was either fixed or is a SpongeForge problem. Can you test it again using the latest SpongeForge?
