### ISSUE TITLE
[1.10.2] Pages are too long when using Polis + Pagination service

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#927]
Using the 1.10 branch of https://github.com/hsyyid/Polis/blob/1.10/src/main/java/io/github/hsyyid/polis/cmdexecutors/PolisHelpExecutor.java

it quickly becomes apparent that the pagination service is somehow splitting the pages incorrectly. 

![image](https://cloud.githubusercontent.com/assets/141554/18335914/32f5b1d8-75c2-11e6-974f-7d050ea71701.png)

![image](https://cloud.githubusercontent.com/assets/141554/18335924/3dfa0c3c-75c2-11e6-92c3-e38f0cfb0049.png)

Should the pagination service be padding with empty lines maintaining the text as one continuous chunk?
Or is the correct behaviour to truncate the last text and show the remainder on the next page?

**Comment by Zidane** [comment]
@ryantheleach 

Always the tough questions :p.

```
Should the pagination service be padding with empty lines maintaining the text as one continuous chunk?
```

This should be the correct behavior. Can you PR a fix?

**Comment by ryantheleach** [comment]
I'll give it a shot.

**Comment by ryantheleach** [comment]
This may actually be https://github.com/SpongePowered/SpongeCommon/pull/1020/files

**Comment by parlough** [comment]
@ryantheleach Is this fixed? I am assuming so.

**Comment by stephan-gh** [comment]
Pretty sure this is fixed in https://github.com/SpongePowered/SpongeCommon/pull/1020. Comment here if this is still happening :)
