### ISSUE TITLE
Duplication Glitch with 1.8.9 Minecraft

### ISSUE THREAD

**Issue by xChristopher210** [SpongePowered/SpongeCommon#931]
I own a Pixelmon server and I have recently caught a player using a duplication bug using a chest and TNT. You place a chest down and place an item in there. Then ignite TNT right next to it and hold shift and press 1 over and over. This is supposed to pull the item out right before it explodes putting an item with a negative value in your inventory and a item on the ground thats a regular item.

If you succeed and get one item on the ground and have one in your inventory you can just throw items out 24/7 and have another person collecting them. 
https://i.gyazo.com/3fc1bc35ebd2bcd7e4d4dc9ae53872b5.gif

I heard that this is a Minecraft dupe glitch. Thats why I have posted in SpongeCommon rather then SpongeForge. So is there any possible way to fix on Sponge?

Versions:
Pixelmon 4.3.0 Beta 8
Forge 1890
SpongeForge 1963

**Comment by bloodmc** [comment]
1.8.9 is no longer supported. Update to latest SF 1.10.2+ build.
