### ISSUE TITLE
Calling custom events causes ClassCastException

### ISSUE THREAD

**Issue by Wundero** [SpongePowered/SpongeCommon#932]
When I posted an event, which implemented interfaces Event and Cancellable, the server threw a ClassCastException (Cannot cast to AbstractEvent). I looked into the source for my version and [this](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/event/SpongeEventManager.java#L313) is the line causing issues. I recommend replacing the cast with a wrapper event instead, however I am not sure how this would be achieved. The fix on my end is to extend AbstractEvent rather than implement Event, however this seems like the wrong way of solving the issue as I would like to build entirely off of the API.

**Comment by ZephireNZ** [comment]
`AbstractEvent` *is* a part of the API. It has a few key implementations that the sponge implementations expect, namely the `init()` method (useful for events with complex get/set stuff) and a field for the `Order`.

As stated in the javadocs for `AbstractEvent`:

```java
/**
 * An abstract event that can be extended for any and all custom events as
 * necessary.
 */
```

**Comment by Aaron1011** [comment]
As @ZephireNZ said, `AbstractEvent` is a part of the API, and it's required that custom events extend it.
