### ISSUE TITLE
SpongeCommon dependencies are ommited in SF/SV

### ISSUE THREAD

**Issue by kenzierocks** [SpongePowered/SpongeCommon#934]
SpongeCommon relies on `fastutil`, but it is not included in the dependencies of SpongeForge or SpongeVanilla. Some of `fastutil` comes with Minecraft, but Common uses parts that do not, specifically the `IntOpenHashSet`: https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/world/WorldManager.java#L118. This causes an error upon startup when initializing the `WorldManager` in a development environment. The solution would either be to include `fastutil` in the SF/SV dependencies or remove it from Common.

**Comment by Minecrell** [comment]
That must be an issue with your workspace. SV/SF should inherit the dependency from SpongeCommon.
