### ISSUE TITLE
[1.10.2] chiselsandbits

### ISSUE THREAD

**Issue by FiveEYZ** [SpongePowered/SpongeCommon#936]
iia says: Chisels and bits isn't working. I can't chisel anything, nor place any bits.

This error generates while doing whats said above:
[latest.log](https://gist.github.com/FiveEYZ/3ab7e3fb5f6e6531afa0560cb8eca3e1)
[fml-server-latest.log](https://gist.github.com/FiveEYZ/01ef0cc97cbb2a77e8031ae117cca6ba)

using:
Minecraft: 1.10.2
SpongeAPI: 5.0.0-SNAPSHOT-6211516
SpongeForge: 1.10.2-2079-5.0.0-BETA-1727
Minecraft Forge: 12.18.1.2086
chiselsandbits-12.1

**Comment by Minecrell** [comment]
Please report issues with mods on the SpongeForge repo: https://github.com/SpongePowered/SpongeForge/issues
