### ISSUE TITLE
Inventory Offer now has stupid behaviour.

### ISSUE THREAD

**Issue by clienthax** [SpongePowered/SpongeCommon#939]
This has totally broken how inventory offers by changing the child order
Offers now go straight to the armor inv first, then main then hotbar.

While were on this subject, is it even a wise idea to make offers able to go into armor slots anyway?

https://github.com/SpongePowered/SpongeCommon/commit/4e766201fabcfdf3bc6c339f9e92323891b495de#diff-3d584ff230663173b6e23d456acfec56L53

**Comment by Deamon5550** [comment]
To summarize a discussion in irc on this issue: The ordering of offering should be to hotbar > inventory > armor. `Carrier.getInventory()` should continue to return an inventory of all three sections. A new method could be added to Human for `getMainInventory()` and `getArmorInventory()` or something of the like.

**Comment by clienthax** [comment]
@Deamon5550 sounds like a plan

**Comment by Mumfrey** [comment]
> A new method could be added to Human for getMainInventory() and getArmorInventory() or something of the like.

Just... no. This is **exactly** why the whole thing is query based. If you ask for an inventory from a thing, you get the thing's entire Inventory, you then query for the bit you want. Adding individual accessors completely goes against the entire design philosophy of Inventory API.

The insertion is something which is wrong, I don't know what this stuff is that Aaron added but I'll have a look at it.
