### ISSUE TITLE
EntityArchetype's getEntityData() does not work properly

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeCommon#941]
Code: 
```java
ConfigurationNode root = loader.load();
EntityArchetype archetype = EntityArchetype.builder().type(EntityTypes.CREEPER).set(Keys.CREEPER_CHARGED, true).set(Keys.DISPLAY_NAME, Text.of(TextColors.GREEN, "Creepar!")).build();
root.getNode("creeper").setValue(DataTranslators.CONFIGURATION_NODE.translate(archetype.getEntityData()));
loader.save(root);
```
Output:
```hocon
creeper {}
```

**Comment by Deamon5550** [comment]
@gabizou I think the issue with this particular example is that the NbtDataProcessors don't seem to be implemented. The `nbtValueTable` in SpongeDataManager is never set to as far as I can tell.

**Comment by gabizou** [comment]
@Deamon5550 that is correct, there aren't any `NbtDataProcessor`s implemented. It would require opening an issue, just like #8.

**Comment by gabizou** [comment]
Replaced with #950
