### ISSUE TITLE
overworld worldUniqueId is zeros

### ISSUE THREAD

**Issue by mmonkey** [SpongePowered/SpongeCommon#95]
The UUID for the default overworld is 00000000-0000-0000-0000-000000000000.
The nether and end world UUID's are generated as expected.

**Comment by simon816** [comment]
Doesn't happen for me. The only thing I can think of is that the `level_sponge.dat` file is missing the `uuid_most` and `uuid_least` entries. Could be that your world was created before the world creation was added or something. Shouldn't happen on a clean world. Delete `level_sponge.dat` and let it regenerate, it should have a random UUID assigned.

**Comment by mmonkey** [comment]
This is happening in single player.
