### ISSUE TITLE
[1.8.9] Register Modded SoundTypes & Playback custom sounds.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#954]
Currently modded soundtypes are not being registered, nor does it appear to be possible to play custom sounds bundled in resource packs.

**Comment by ryantheleach** [comment]
```
<Waterpicker> Sponge.getRegistry().getAllFor("pixelmon", SoundType.class); is what I used.)
```

**Comment by ZephireNZ** [comment]
In my research, it looks like this is because we hooking into the registry when a sound is added for Forge. Might also need a way to hook into when resource packs get registered too.

**Comment by ZephireNZ** [comment]
Actually , with resource packs at least on the server side, those sounds would never be loaded would they? The server simply gives the client the pack, never actually loading it (and the sounds) itself. Might need to add a SoundTypeBuilder to create a "dummy" sound which can be sent to the client to play.

**Comment by ST-DDT** [comment]
Afaict it is possible to register catalog types already:
https://github.com/SpongePowered/SpongeAPI/blob/bleeding/src/main/java/org/spongepowered/api/GameRegistry.java#L194

But I'm not sure whether we expose a sound type builder or whether this is required at all.

**Comment by ZephireNZ** [comment]
`if registration for that type is supported.`

`SoundRegistryModule` does not implement `AdditionalCatalogRegistryModule` and so doesn't support additional types after it's been initialized.

**Comment by ryantheleach** [comment]
That or introduce the string methods for sending sounds.

**Comment by ZephireNZ** [comment]
I'm going to whip up a PR to add these changes.

**Comment by ZephireNZ** [comment]
Voila: https://github.com/SpongePowered/SpongeCommon/issues/954
