### ISSUE TITLE
ChangeBlockEvent.Place does not contain the ItemStack in the cause

### ISSUE THREAD

**Issue by pie-flavor** [SpongePowered/SpongeCommon#956]
It should contain the ItemStack or an ItemStackSnapshot. The item is literally the cause for the block existing, no?
There is also no way to know which hand was used, so the stack cannot be inferenced; nor is getItemInHand() present at this point.

**Comment by gabizou** [comment]
Version?

**Comment by pie-flavor** [comment]
@gabizou SV 5.0.0-131

**Comment by bloodmc** [comment]
@pie-flavor Is there a reason you cannot simple compare the BlockType placed and BlockType in hand if any? The placement order will always attempt main-hand first followed by offhand. We can add a fix for this event in future but this should be feasible for now.

**Comment by windy1** [comment]
@bloodmc The stack is removed before the event is fired. I had to workaround this issue recently by listening to both the `InteractBlockEvent` and `ChangeBlockEvent.Place` events and caching the stack from the former so I could use it in the latter.

**Comment by pie-flavor** [comment]
@Zidane I had almost forgotten about this, but it should not be closed as it is still true in the latest build (1.11.2-6.0.0-BETA-206).

**Comment by theboomer** [comment]
An addendum to what has been stated, as maybe by now there is knowledge of which hand was used, and we have access to getItemInHand(), but if the player places something from an itemstack of 1 item in hand is empty at this event , and although we can determine what would have been held by what blockstate resulted from placing .... we lose the itemstack/snapshot data .

And sometimes its important to have the data on the itemstack to make the decision to allow or invalidate the transaction or cancel the event.

**Comment by ImMorpheus** [comment]
This should not be necessary anymore as of this commit https://github.com/SpongePowered/SpongeAPI/commit/7b61abce27b52458c1888e07a137562c45840a98

You can now get the ItemStackSnapshot from the context:

```
    @Listener
    public void onChange(ChangeBlockEvent.Place event, @Root Player player) {
        ItemStackSnapshot item = event.getCause().getContext().get(EventContextKeys.USED_ITEM).get();
        player.sendMessage(Text.of(item.getType().getName()));
    }
```
