### ISSUE TITLE
Incorrect double-chest rotation

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeCommon#957]
When making a double chest, if you create it "vertically"/"sideways" (see video), then chest's rotation will be wrong: one invisible block and one ghost block.

Video: https://youtu.be/BmkObOHr0To

Tested in SpongeForge 5.0.0-1492705-SNAPSHOT and SpongeVanilla-1.10.2-5.0.0-BETA-129

**Comment by Aaron1011** [comment]
This is caused by `Block#onBlockAdded` not being called for blocks with a `TileEntity` (e.g. anything that extends `BlockContainer`. I'm looking into a fix.
