### ISSUE TITLE
Math rotation issues with BlockRay

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#96]
The following seems to only ever make you move east, I would have expected it to have teleported the player in the direction that they are facing.

Does the blockLimit get applied before or after the filter? I would have expected it to be applied before the filter, but was unable to debug this further due to the direction bug.
 ```
public class JumpExecutor implements CommandExecutor
{
        public CommandResult execute(CommandSource src, CommandContext ctx) throws CommandException
        {
                if(src instanceof Player)
                {
                        Player player = (Player) src;
                        BlockRayBuilder blockRayBuilder = BlockRay.from(player);
                        BlockRay ray = blockRayBuilder.filter(BlockRay.ONLY_AIR_FILTER).blockLimit(50).build();
                        Optional<BlockRayHit> end = ray.end();
                        BlockRayHit hit = end.get();
                        Location location = new Location(player.getWorld(), hit.getBlockX(), hit.getBlockY(), hit.getBlockZ());
                        player.setLocation(location);
                }
                else if(src instanceof ConsoleSource) {
                        src.sendMessage(Texts.of(TextColors.DARK_RED,"Error! ", TextColors.RED, "Must be an in-game player to use /jump!"));
                }
                else if(src instanceof CommandBlockSource) {
                        src.sendMessage(Texts.of(TextColors.DARK_RED,"Error! ", TextColors.RED, "Must be an in-game player to use /jump!"));
                }
                return CommandResult.success();
        }
}
```

@DDoS

**Comment by DDoS** [comment]
Can you try using a random vector as a direction, see if this is only an issue with retrieving the direction from the player?

**Comment by modwizcode** [comment]
Is this related to the fact that getRotation() from player (which shows the eye rotation), returns a value of -180->180 degrees which isn't really cooperative with our rotation api's?

**Comment by ryantheleach** [comment]
@hsyyid any further luck?

@hsyyid is the original person who discovered the problem, I was just helping them test at the time.

**Comment by DDoS** [comment]
When I first wrote the tracer, I tested it a lot with the `from(Entity)` builder and had no issues with it. It would obtain the player's target block.

**Comment by hsyyid** [comment]
@ryantheleach I haven't tried it out yet. Will later today.

**Comment by DDoS** [comment]
Tested using

    public static void test(Entity e) {
        BlockRay.from(e).filter(BlockRay.ONLY_AIR_FILTER).end().get().getLocation().setBlockType(BlockTypes.GOLD_BLOCK);
    }

Works as expected, a gold block is placed at the cursor position (well, just under because eye location data isn't implemented yet).

**Comment by DDoS** [comment]
I'm going to close this from a lack of response and my test results. Feel free to reopen if you can confirm the bug here is from BlockRay.
