### ISSUE TITLE
[1.10.2 Beta 136] BanIp : NullPointerException

### ISSUE THREAD

**Issue by lesbleu** [SpongePowered/SpongeCommon#964]
Hi,
When I use the function Ban.Ip.getBanSource() and Ban.Ip.getReason(), the function return null or these functions should return an optional.
MixinBanEntry:onInit() is executed or not ?

Error : http://pastebin.com/mEdCpB1C

**Comment by kashike** [comment]
Beta 136 of....? In either case, beta 136 is old. Please update and see if the issue is fixed..

**Comment by rexbut** [comment]
This is the SpongeVanilla 1.10.2-5.0.0-BETA-136, but I also tested with the ongoing bleeding.
