### ISSUE TITLE
Setting block from InteractEvent doesn't fire another event

### ISSUE THREAD

**Issue by Zidane** [SpongePowered/SpongeCommon#965]
```
    @Listener
    public void onInteractBlockSecondaryMainHand(InteractBlockEvent.Secondary.MainHand event, @Root Player player) {
        event.getTargetBlock().getLocation().get().setBlock(BlockTypes.SPONGE.getDefaultState(), Cause.source(this.container).build());
    }
```

Even scheduling a tick later still doesn't @gabizou .

**Comment by bloodmc** [comment]
@Zidane I think it makes more sense to just adjust the API to include a method for replacing the interacted block. Perhaps a transaction like we do with snapshots so a plugin can just set the "custom" block they want to change.

**Comment by Zidane** [comment]
@bloodmc 

We could probably do that to prevent x-amount of event firing. I only noticed this when I was helping someone else with a plugin. Coincidence actually.

**Comment by gabizou** [comment]
Fairly sure at this point it does throw a new event now, especially since listeners flow through the same logic as any other event now. Re-open if it's still an issue these days.
