### ISSUE TITLE
Implementation Request IgniteEntityEvent

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#970]
1.10.2 versions dont have the IgniteEntityEvent fired when events burst into flame from fire, lava or sunlight (skeletons/zombies).  I dont know if this event was ever implimented in 1.8.9 and didn't make it.

DamageEntityEvent only goes so far as a workaround - it only registers living entities suffereing health damage ticks due to fire.

IgniteEntityEvent will capture armor stands being ignited by lava and fire  (as well as prevent need for listening to generic damage for living entities)

**Comment by ImMorpheus** [comment]
I'm working on this. (a WIP PR scheduled for tomorrow)

**Comment by ryantheleach** [comment]
@ImMorpheus What was the resolution on this?

**Comment by parlough** [comment]
https://github.com/SpongePowered/SpongeCommon/pull/1708

**Comment by ImMorpheus** [comment]
PR merged. This can be closed.
