### ISSUE TITLE
Chest sounds not working after opening them

### ISSUE THREAD

**Issue by VcSaJen** [SpongePowered/SpongeCommon#971]
1) Chest open sound works only once for chest, when opening it second and consequential times, it will not work for this particular chest.
2) Chest closing sound works only seven times for chest, when opening it eight and consequential times, it will not work for this particular chest.

This happens only when Sponge is installed, and happens even if Sponge is running without plugins. There is no errors in console at the moment of opening or closing. Tested on SpongeForge-5.0.0-81b2744-SNAPSHOT and SpongeVanilla-1.10.2-5.0.0-BETA-138.

**Comment by Aaron1011** [comment]
@VcSaJen: Note that the behavior will still differ slightly from Vanilla - for performance reasons, Sponge prevents chest tile entities from ticking.

The only effect this has is that the opening sound will always play when you open a chest, and the closing sound will always play when the chest starts to close. In vanilla, the opening sound only plays if the chest has completely closed, and the closing sound will only play when the chest angle drops below 0.5 (e.g. when it becomes halfway closed).
