### ISSUE TITLE
[1.10.2] SpVanilla Nicely formatted sponge errors when exiting beds

### ISSUE THREAD

**Issue by theboomer** [SpongePowered/SpongeCommon#972]
_DISCLAIMER: I posted this in SpongeVanilla where I was then told it was confirmed, but asked to post here in SpongeCommon, though I have not tested any spongeforge versions myself._

My testers were able to reproduce the result - by pressing ESC to exit a bed, or the leave-bed button to leave bed, prior to actually sleeping, the following errors were generated. It appears to be two back-to-back errors for each 'leave bed' action taken.

Replicated with spongevanilla-138 with 0 plugins, and player can be holding an item or empty slot, it still throws errors.

See pastebin link for the **"Exception trying to process over a phase! "** titled , **"java.lang.IllegalStateException: Intended to capture block changes, but there is no list available! Please analyze the current phase context."** error,
and its corresponding **"Exception attempting to capture a block change! "** titled **"java.lang.IllegalStateException: Intended to capture block changes, but there is no list available! Please analyze the current phase context."** error,
in their full beautifully formatted with-info-and-stacktrace glory

http://pastebin.com/tP6NKkP1

**Comment by Aaron1011** [comment]
This isn't actually happening in SpongeForge, due to a Forge bug ([it never properly sets the bed to 'unoccupied'](https://github.com/MinecraftForge/MinecraftForge/blob/1.10.x/patches/minecraft/net/minecraft/block/Block.java.patch#L623)). I'll look into fixing it in Forge, and fixing the Sponge error in both SpongeForge and SpongeVanilla.

**Comment by theboomer** [comment]
Thank you for promptly looking into this, Aaron1011.  I hope its an easy fix.

**Comment by stephan-gh** [comment]
I'm pretty sure this was fixed in https://github.com/SpongePowered/SpongeCommon/commit/f82761129aeb563967754a42dae2b714018f2959
