### ISSUE TITLE
Dump context stack in error handler.

### ISSUE THREAD

**Issue by ryantheleach** [SpongePowered/SpongeCommon#973]
Is it feasible to modify the error handler so the current or previous cause / context is dumped in the error stack?

I feel like with appropriate toString methods defined this could radically help in debugging possible errors and mod interactions.

**Comment by phit** [comment]
closed with https://github.com/SpongePowered/SpongeCommon/commit/b70f7dd01a8996ebc88a460d0c7d5eac29bb3277#diff-7fc5093248c2beeeead9d83365925fa0
