### ISSUE TITLE
[1.10.2] Issue when canceling double shift clicked items

### ISSUE THREAD

**Issue by Rhonim** [SpongePowered/SpongeCommon#974]
Currently having some issues when trying to cancel the moving/removal of items when the player does a shift + double primary click. Some of the items will still move over to the player's inventory even when cancelled.

I tested this using both and old and latest version of sponge forge, all you need to do to reproduce it is put multiple of the same item into a double chest, then cancel the ClickInventoryEvent Event, then shift + double primary click the item in the chest.

Something also to note, if I make any changes to the transactions they are also ignored.

**Comment by caseif** [comment]
This seems to occur when two clicks occur in the same tick. In my environment, a player is shown a custom inventory which is supposed to be immutable. If a player double-clicks an item from their inventory fast enough, it'll disappear completely. If they double-click something from the custom inventory, it'll get duped and moved to their inventory.

**Comment by Aaron1011** [comment]
@bloodmc's code doesn't address the root cause, as it should never be possible to modify an inventory if all `InventoryClickEvent`s are being cancelled. I'll be looking into fixing this.

**Comment by Aaron1011** [comment]
I've reproduced the issue, and noticed something interesting: In Vanilla, there's no such thing as a 'double shift click'. If you're holding down shift, you're unable to double click at all, as the initial click always moves the item to the opposite inventory (e.g. player inv -> chest inv or vice versa), without giving you a chance to click again.

However, if you hold down shift after the first click, but before the second click, nothing happens - the item remains on your cursor, and neither a shift click or a double click action is performed.

**Comment by caseif** [comment]
I replicated it by simply shift-clicking the item repeatedly. Of course, I'm not sure whether the item is clicked the second time or if it's simply the (temporarily) empty slot that's clicked. In the latter case, it may be easier to determine exactly why the bug is occurring.
