### ISSUE TITLE
[1.10.2] Error when using the AssetManager in GameStartedServerEvent (Sponge not Initialized)

### ISSUE THREAD

**Issue by me4502** [SpongePowered/SpongeCommon#977]
Here's the stacktrace,

http://pastebin.com/fZ0FxKUs

The code I'm using specifically, inside the event handler, is

```
Asset books = CraftBookPlugin.<CraftBookPlugin>inst().getContainer().getAsset("bookshelf/books.txt").get();
        Path path = new File(CraftBookPlugin.inst().getWorkingDirectory(), "bookshelf/books.txt").toPath();

        if (Files.notExists(path)) {
            try {
                books.copyToFile(path);
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        try {
            bookLines = Files.readAllLines(path).toArray(new String[0]);
        } catch (IOException e) {
            e.printStackTrace();
        }
```

This occurs when using [SpongeVanilla 72084b0](https://github.com/SpongePowered/SpongeVanilla/commit/72084b03a3e46e255dc8392c97e1648133d9bba7)

**Comment by me4502** [comment]
Okay - tried with a fresh clone of SV, still the same. Tried a fresh clone of SF, it worked. I'm thinking this may be SV only.

**Comment by Minecrell** [comment]
I can imagine that this is a SV only problem. Looking at the stack trace it looks like just another class loader problem. I added a classloader exception for `PluginContainer` to fix https://github.com/SpongePowered/SpongeVanilla/issues/268, on the other hand it will now try to find the `Game` instance that is only initialized within the Launch classloader.

I really need to cleanup this classloader mess so problems like this stop happening.
