### ISSUE TITLE
Keys.CAN_PLACE_AS_BLOCK doesn't actually work

### ISSUE THREAD

**Issue by simon816** [SpongePowered/SpongeCommon#981]
In [`CanPlaceAsBlockValueProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/data/processor/value/entity/CanPlaceAsBlockValueProcessor.java#L52) and [`FallingBlockDataProcessor`](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/data/processor/multi/entity/FallingBlockDataProcessor.java#L61)
It sets the field `canSetAsBlock`, which is an incorrectly named field
(See https://github.com/ModCoderPack/MCPBot-Issues/issues/285)

I'm not sure if setting this value should also stop the fallingblock from despawning when it hits a block because that would be a useful feature. (Basically I want to be able to move a fallingblock freely without worrying about it suddenly despawning when it touches a block beneath).

Also, the value is not persisted in the NBT so it will loose it's value on a server restart.

**Comment by me4502** [comment]
I noticed this issue the other day when porting CraftBook's BetterPhysics over. It appears the value is just inverted.

**Comment by kashike** [comment]
https://github.com/SpongePowered/SpongeCommon/commit/6f8b39afdaaa693041e6658e1e0b1a9604a5d3a4
